syncfusion-content/maui-docs

MAUI/ListView/filtering.md

MAUI-1445 Update filtering.md

---

MAUI/ListView/working-with-sflistview.md
maui-toc.html

Added working-with-listview.md file for MAUI ListView.

MAUI-1444: Adding working-with-sflistview topic in UG

---

MAUI/ListView/getting-started.md

Have added note to know that winui is not support in MAUI ListView

MAUI-1444 - WinUI not supported added for MAUI ListView

---

MAUI/Introduction/maui-cross-platform-ui.md

MAUI-1605 Updated the supported platforms status of cross platform controls

MAUI-1605 Updated the supported platforms status of cross platform controls

---

MAUI/Scheduler/load-on-demand.md

Resolved syntax error in load-on-demand file.

MAUI-1459-Resolved syntax error in load-on-demand  file.

---

MAUI/Range-Selector/basic-features.md
MAUI/Range-Selector/divider.md
MAUI/Range-Selector/dragbehavior.md
MAUI/Range-Selector/events.md
MAUI/Range-Selector/getting-started.md
MAUI/Range-Selector/interval.md
MAUI/Range-Selector/labels.md
MAUI/Range-Selector/thumb-and-overlay.md
MAUI/Range-Selector/ticks.md
MAUI/Range-Selector/tooltip.md
MAUI/Range-Selector/track.md
MAUI/Range-Slider/basic-features.md
MAUI/Range-Slider/divider.md
MAUI/Range-Slider/dragbehavior.md
MAUI/Range-Slider/events.md
MAUI/Range-Slider/getting-started.md
MAUI/Range-Slider/interval.md
MAUI/Range-Slider/labels.md
MAUI/Range-Slider/thumb-and-overlay.md
MAUI/Range-Slider/ticks.md
MAUI/Range-Slider/tooltip.md
MAUI/Range-Slider/track.md

Updated the code snippets in range selector and changed the code orders in UG contents

MAUI-1472: Updated the code snippet and changed the order of the properties

---

MAUI/ListView/filtering.md
MAUI/ListView/grouping.md
MAUI/ListView/item-size-customization.md
MAUI/ListView/mvvm.md
MAUI/ListView/selection.md
MAUI/ListView/viewappearance.md
MAUI/ListView/working-with-sflistview.md

Resolve typo mistakes in KB and add SeeAlso content in UG

MAUI-1635:Resolve typo mistakes in KB and add SeeAlso content in UG

---

MAUI/ListView/getting-started.md
MAUI/ListView/header-and-footer.md
MAUI/ListView/scrolling.md

Changed the code as per the review correction.

MAUI-1577: GettingStarted review corrections.

---

MAUI/Scheduler/agenda-view.md
MAUI/Scheduler/appointments.md
MAUI/Scheduler/day-week-views.md
MAUI/Scheduler/getting-started.md
MAUI/Scheduler/header-view.md
MAUI/Scheduler/load-on-demand.md
MAUI/Scheduler/month-view.md
MAUI/Scheduler/timeline-views.md

Updated UG review correction for SfScheduler.

MAUI-1459-Updated UG review correction for SfScheduler.

---

maui-toc.html

I have fixed the effects sub category title issue in SfEffectsView.

MAUI-1677 Fixed the effects sub category title issue in SfEffectsView

---

MAUI/Scheduler/appointments.md
MAUI/Scheduler/load-on-demand.md

Updated UG review correction for SfScheduler.
https://syncfusion.sharepoint.com/sites/Install/SitePages/Support-for-showing-the-H3-tags.aspx

MAUI-1459-Updated UG review correction for SfScheduler. 

---

MAUI/Scheduler/agenda-view.md
MAUI/Scheduler/appointments.md
MAUI/Scheduler/date-navigation-restriction.md
MAUI/Scheduler/day-week-views.md
MAUI/Scheduler/header-view.md
MAUI/Scheduler/load-on-demand.md
MAUI/Scheduler/month-view.md
MAUI/Scheduler/timeline-views.md

Updated scheduler breaking API's and API's link for new properties.

WINUI-2403-[MAUI]Updated scheduler breaking API's and API's link for new properties.

---

MAUI/ListView/Migration.md
MAUI/ListView/migration.md
maui-toc.html

Added the documentation for Migration UG for MAUI ListView

MAUI-1635: Migration UG - ListView

---

MAUI/Barcode-Generator/getting-started.md

Getting started sample link added in barcode control

MAUI-1725: Getting started sample link added in barcode control

---

MAUI/Scheduler/agenda-view.md
MAUI/Scheduler/appointments.md
MAUI/Scheduler/date-navigation-restriction.md
MAUI/Scheduler/day-week-views.md
MAUI/Scheduler/events.md
MAUI/Scheduler/getting-started.md
MAUI/Scheduler/header-view.md
MAUI/Scheduler/load-on-demand.md
MAUI/Scheduler/localization.md
MAUI/Scheduler/month-view.md
MAUI/Scheduler/time-zone.md
MAUI/Scheduler/timeline-views.md

Updated code highlights for the Maui Scheduler control.

MAUI-1686-Updated code highlights for the Maui Scheduler control.

---

MAUI/Barcode-Generator/migration.md
maui-toc.html

Hi @sheiksyedm,
I have prepared MD document for the Xamarin Barcode to .Net MAUI Barcode Generator. Can you please review and merge this.
Regards,
Ragul S V

MAUI-1951: How to migrate from Xamarin Forms Barcode control to .NET MAUI Barcode control.

---

MAUI/Scheduler/migration.md
maui-toc.html

* Assembly Name
* Namespaces
* Properties
* Events
* Enums
* Classes
* Methods
* SchedulerAppointment
* SchedulerAppointmentMapping
Regards,
Muniappan S

MAUI-1844 Migrating MAUI SfScheduler from Xamarin SfSchedule.

---

MAUI/Radial-Gauge/migration.md
maui-toc.html

Hi @sheiksyedm,
I have prepared MD document for the Xamarin Circular Gauge to .Net MAUI Radial Gauge. Can you please review and merge this.
Regards,
Ragul S V

MAUI-1800: How to migrate from Xamarin Forms CircularGauge control to .NET MAUI RadialGauge control.

---

MAUI/Badge-View/Migration.md
MAUI/Effects-View/Migration.md
MAUI/TabView/Migration.md
maui-toc.html

Updated the UG content for migration from Xamarin.Forms to MAUI for SfTabView, SfBadgeView and SfEffectsView.

MAUI-1881 Updated the UG content for migration from Xamarin.Forms to MAUI for SfTabView, SfBadgeView and SfEffectsView.

---

MAUI/Scheduler/migration.md

- Assembly Name
- Namespaces
- Properties
- Events
- Enums
- Classes
- Methods
- SchedulerAppointment
- SchedulerAppointmentMapping
- MonthView
- DayView
- TimelineView
- SchedulerTimeRegion
- AppointmentTextStyle
- CellStyle
- HeaderView
- ViewHeaderSettings
- WeekNumberStyle
Regards,
Muniappan S

MAUI-1844 -Alignment issue fixed.

---

MAUI/Linear-Gauge/migration.md
maui-toc.html

Hi @sheiksyedm,
I have prepared the migration document for SfLinearGauge. Can you please review and merge this.
Regards,
Ragul S V

MAUI-1950: How to migrate from Xamarin Forms LinearGauge control to .NET MAUI LinearGauge control.

---

MAUI/ListView/migration.md

MAUI-1635 Migration UG

---

MAUI/Scheduler/migration.md

- Assembly Name
- Namespaces
- Properties
- Events
- Enums
- Classes
- Methods
- SchedulerAppointment
- SchedulerAppointmentMapping
- MonthView
- DayView
- TimelineView
- SchedulerTimeRegion
- AppointmentTextStyle
- CellStyle
- HeaderView
- ViewHeaderSettings
- WeekNumberStyle
Regards,
Muniappan S

MAUI-1844-Upcoming features list added.

---

MAUI/Barcode-Generator/migration.md
MAUI/Linear-Gauge/migration.md
MAUI/Radial-Gauge/migration.md

Hi @sheiksyedm,
I have completed the review changes in the migration ocument of the SfLinearGauge, SfRadialGauge and Barcode. Can you please review and merge this.
Regards,
Ragul S V

MAUI-1951: How to migrate from Xamarin Forms to .NET MAUI.(SfLinearGauge, SfRadialGauge and Barcode)

---

MAUI/Cartesian-Charts/Migration/Migrate-SfChart-to-SfCartesianChart.md

Modified migration document file name and location.
Alter APIs and code snippet.

MAUI-1807 Updated ug for migrating MAUI SfCartesianchart from Xamarin SfChart

---

MAUI/Scheduler/migration.md
maui-toc.html

- Assembly Name
- Namespaces
- Properties
- Events
- Enums
- Classes
- Methods
- SchedulerAppointment
- SchedulerAppointmentMapping
- MonthView
- DayView
- TimelineView
- SchedulerTimeRegion
- AppointmentTextStyle
- CellStyle
- HeaderView
- ViewHeaderSettings
- WeekNumberStyle
- Upcoming Features
Regards,
Muniappan S

MAUI-1844 -[Hotfix] Migration code changes added.

---

MAUI/Scheduler/migration.md

I have updated the content for Migration in MAUI Scheduler.  Please review this and let me know if you have any concerns.
Regards,
Muniappan S

MAUI-1844-Review changes updated.

---

MAUI/Cartesian-Charts/Migration/Chart-API-Migration.md
MAUI/Cartesian-Charts/Migration/Migrate-From-Xamarin.md
maui-toc.html

MAUI-1807 Changed migration ug content.

MAUI-1807 Changed migration ug content.

---

MAUI/Range-Selector/migration.md
MAUI/Range-Slider/migration.md
MAUI/Slider/migration.md
maui-toc.html

Hi Team,
I have added a UG document for the Migration steps from the Xamarin Forms SfRangeSlider to .NET MAUI Slider, RangeSlider, and DateTime RangeSelector. Kindly review the content and merge the changes.
Regards,
Praveen G.

MAUI-2021-Added migration from xamarin forms to .NET Maui Sliders md files

---

MAUI/Scheduler/migration.md

MAUI-1692-UGDocumentMAUI-Documentation updated.

---

MAUI/Scheduler/migration.md

MAUI-1692-UGContent-Code snippet added.

---

MAUI/Scheduler/migration.md

MAUI-1692-UGContent-Changes committed.

---

MAUI/ListView/filtering.md
MAUI/ListView/getting-started.md
MAUI/ListView/grouping.md
MAUI/ListView/header-and-footer.md
MAUI/ListView/item-size-customization.md
MAUI/ListView/layouts.md
MAUI/ListView/loadmore.md
MAUI/ListView/mvvm.md
MAUI/ListView/right-to-left.md
MAUI/ListView/scrolling.md
MAUI/ListView/selection.md
MAUI/ListView/sorting.md
MAUI/ListView/viewappearance.md
MAUI/ListView/working-with-sflistview.md

Resolved automation errors due to MAUI-ListView UG documents

MAUI-1750 Adding TabTitle and highlighting the codes

---

MAUI/Scheduler/migration.md

I have added the example codes for the Appointment text style and cell style, please review the code changes and let me know if you have any concerns.
Regards,
Muniappan S

MAUI-1844 Appointment text style and cell style example codes added.

---

MAUI/Cartesian-Charts/Migration/Migrate-From-Xamarin.md

Modified migration document file name and location.
Alter APIs and code snippet.

MAUI-2046 Updated ug for migrating MAUI SfCartesianchart from Xamarin SfChart

---

MAUI/Circular-Charts/Migrate-From-Xamarin.md
maui-toc.html

Included migration document for SfCircularChart
Alter APIs and code snippet.

MAUI-2046 Updated ug for migrating MAUI SfCircularChart from Xamarin SfChart

---

MAUI/Scheduler/migration.md

I have fixed the alignment issue, please review the code changes and let me know if you have any concerns.
Regards,
Muniappan S

MAUI-1844-Alignment changes done

---

MAUI/Scheduler/migration.md

I have updated the example codes, please review the code changes and let me know if you have any concerns.
Regards,
Muniappan S

MAUI-1844- Example Code changes added.

---

MAUI/Range-Selector/migration.md
MAUI/Range-Slider/migration.md
MAUI/Slider/migration.md
maui-toc.html

Hi Team,
I have added a UG document for the Migration steps from the Xamarin Forms SfRangeSlider to .NET MAUI Slider, RangeSlider, and DateTime RangeSelector. Kindly review the content and merge the changes.
Regards,
Praveen G.

MAUI-2021: Moved migration documents of Maui Sliders from development to hotfix-v20.1.0.47

---

MAUI/Scheduler/migration.md

I have updated the example codes, please review the code changes and let me know if you have any concerns.
Regards,
Muniappan S

MAUI-1844- Code changes added

---

MAUI/Scheduler/migration.md

I have updated the example codes, please review the code changes and let me know if you have any concerns.
Regards,
Muniappan S

MAUI-1844- Code changes added.

---

MAUI/Badge-View/Migration.md
MAUI/Effects-View/Migration.md
MAUI/TabView/Migration.md

MAUI-1881 Migration review changes

---

MAUI/Badge-View/Migration.md
MAUI/Effects-View/Migration.md
MAUI/TabView/Migration.md
maui-toc.html

UG changes in Migration File on BadgeView, EffectsView, and TabView.

MAUI-1550 UG content changes

---

MAUI/Cartesian-Charts/migration.md
MAUI/Circular-Charts/migration.md

Changed Support and feedback header.
Changed the content some for migration.

MAUI-2046 Updated ug for migrating MAUI Chart from Xamarin SfChart

---

MAUI/Range-Selector/migration.md
MAUI/Range-Slider/migration.md
MAUI/Slider/migration.md

Hi  @MeikandaNayanar,
I have updated the Migration steps from the Xamarin Forms SfRangeSlider to .NET MAUI Slider, RangeSlider, and DateTime RangeSelector. 
@laksmipriyamurugesan I have created a task for content review and also attached the changes as a document. Kindly review it. 
**Task Link:** https://syncfusion.atlassian.net/browse/DOC-4387
Regards,
Praveen G.

MAUI-2021: Updated Maui Sliders migration document

---

MAUI/Range-Selector/migration.md
MAUI/Range-Slider/migration.md
MAUI/Slider/migration.md

Hi @MeikandaNayanar,
I have updated the content review changes in the Migration steps from the Xamarin Forms SfRangeSlider to .NET MAUI Slider, RangeSlider, and DateTime RangeSelector. Kindly check the changes and merge them.
Regards,
Praveen G.

MAUI-2152: Updated Maui Sliders migration document content review changes

---

MAUI/TabView/Migration.md

TabView upcoming features were added.

MAUI-2166 TabView_NewFeatureHotfix

---

MAUI/TabView/Migration.md

MAUI-2166 TabView_NewFeature_Dev

---

MAUI/Scheduler/migration.md
maui-toc.html

XAMARIN-43309-SfScheduler Migration documentation is updated

XAMARIN-43309-SfScheduler Migration documentation is updated

---

MAUI/Scheduler/migration.md
maui-toc.html

XAMARIN-43309-SfScheduler Migration documentation is updated[hotfix]

XAMARIN-43309-SfScheduler Migration documentation is updated[hotfix]

---

MAUI/Cartesian-Charts/Area.md
MAUI/Cartesian-Charts/Column.md
MAUI/Cartesian-Charts/DataLabels.md
MAUI/Cartesian-Charts/Fastline.md
MAUI/Cartesian-Charts/Getting-Started.md
MAUI/Cartesian-Charts/Line.md
MAUI/Cartesian-Charts/Scatter.md
MAUI/Cartesian-Charts/Selection.md
MAUI/Cartesian-Charts/Tooltip.md

Removed the series on the cartesian chart. 
Added notes on the place while using series.

MAUI-2173 Revamp chart ug document.

---

MAUI/Cartesian-Charts/Axis/Types.md
MAUI/Circular-Charts/DoughnutChart.md
MAUI/Circular-Charts/Getting-Started.md
MAUI/Circular-Charts/PieChart.md
MAUI/Circular-Charts/Tooltip.md

Removed the series on the circular chart.
Added notes on the place while using series.

MAUI-2173 Revamp chart ug document

---

MAUI/ListView/filtering.md
MAUI/ListView/getting-started.md
MAUI/ListView/grouping.md
MAUI/ListView/scrolling.md
MAUI/ListView/selection.md
MAUI/ListView/sorting.md

Analyzed all the APIs link in MAUI ListView UG and Resolved all the broken API links in MAUI ListView UG

MAUI-2213-Resolve broken API links in MAUI ListView UG

---

MAUI/ListView/sorting.md

added property name in sortdescriptor

MAUI-1313 Items are not added in CustomSortingOrder in runtime.

---

MAUI/Range-Selector/events-and-commands.md
MAUI/Range-Slider/events-and-commands.md
MAUI/Slider/events-and-commands.md
maui-toc.html

Hi Team,
I have added Ug documentation for the Sliders(SfSlider, SfRangeSlider, and SfRangeSelector) commands support. Please review the content and merge this PR.
Regards,
Praveen G.

MAUI-2362 Added UG documentation for Sliders command support

---

MAUI/Busy-Indicator/AnimationType.md
MAUI/Busy-Indicator/Getting-Started.md
MAUI/Busy-Indicator/IndicatorColor.md
MAUI/Busy-Indicator/Migration.md
MAUI/Busy-Indicator/Set-Header.md
MAUI/Busy-Indicator/Sizing.md

.NET MAUI SfBusyIndicator UG review changes are mentioned in the following PR: https://github.com/syncfusion-content/maui-docs/pull/345#pullrequestreview-1013450549.
All of the review changes mentioned in the above PR have been addressed, and changes have been made.

MAUI-2299 Need to do review changes provided by content team

---

MAUI/Converters/Converters.md
maui-toc.html

MAUI-2379 Review changes committed for converters UG

---

MAUI/Licensing/licensing-faq/Is-an-internet-connection-required-for-Syncfusion-Essential-Studio-license-validation.md
MAUI/Licensing/licensing-faq/how-to-upgrade-from-trial-version-after-purchasing-a-license.md
MAUI/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md
MAUI/Licensing/licensing-faq/where-can-i-get-a-license-key.md

Adding Licensing for Syncfusion in .NET MAUI

MAUI-2400 Changes in Licensing FAQ

---

MAUI/DataGrid/Getting-started.md

I have updated the UG content after the review changes.

MAUI-2386 - Review Changes for MAUI DataGrid

---

MAUI/Introduction/maui-cross-platform-ui.md

I have updated Cross Platform UI file in MAUI platform

MAUI-2386- Updated Cross platform-UI file

---

MAUI/Avatar-view/Content-type.md
MAUI/Avatar-view/Getting-Started.md
MAUI/Avatar-view/customization.md
MAUI/Avatar-view/how-to.md
MAUI/Avatar-view/visualstyles.md

Alignment changes made in the following files
- Getting Started
- Customization
- Visual Styles
- Content Type
- How To

MAUI-2290 Alignment changes

---

MAUI/Avatar-view/Content-type.md
MAUI/Avatar-view/Getting-Started.md
MAUI/Avatar-view/customization.md
MAUI/Avatar-view/how-to.md
MAUI/Avatar-view/visualstyles.md

MAUI-2290 Review changes in Avatar view

---

MAUI/Maps/bubble.md
MAUI/Maps/data-labels.md
MAUI/Maps/getting-started.md
MAUI/Maps/legend.md
MAUI/Maps/markers.md
MAUI/Maps/overview.md
MAUI/Maps/selection.md
MAUI/Maps/shape.md
MAUI/Maps/tooltip.md

I have updated a content in MAUI maps. Could you please review it?
Regards,
Shalini.

MAUI-2286 : Content review changes for Maps.

---

MAUI/Scheduler/calendar-types.md
MAUI/Scheduler/day-week-views.md
MAUI/Scheduler/migration.md
MAUI/Scheduler/month-view.md
MAUI/Scheduler/timeline-views.md

MAUI-2359-MAUIUGDocument-Migration topic updated.

---

MAUI/Licensing/licensing-faq/how-to-upgrade-from-trial-version-after-purchasing-a-license.md
MAUI/Licensing/overview.md

IN-18200-UG-Link-changes-maui-hotfix

---

MAUI/ListView/scrolling.md

Added ScrollBarVisibility property of MAUI ListView
Content Reviewed task: https://syncfusion.atlassian.net/browse/MAUI-2422

MAUI-2422 : Added ScrollBarVisibility property of MAUI ListView

---

MAUI/Maps/migration.md

Hi @vigneshrameshsync,
I have updated the changes in migration document. Can you please review and merge this.
Regards,
Ragul S V

MAUI-2481: How to migrate from Xamarin Forms Maps control to .NET MAUI I Maps control.

---

MAUI/Scheduler/calendar-types.md
MAUI/Scheduler/resource-view.md

Highlighted the important properties.

MAUI-2359-MAUIUGDocument-Highlighted the important properties.

---

MAUI/Scheduler/resource-view.md

MAUI-2359-MAUIUGDocument-Resource code added.

---

MAUI/DataGrid/Column-sizing.md

Text Alignment corrected and committed

MAUI-2409 Prepare UG document for Column Sizing Feature

---

MAUI/Avatar-view/Content-type.md
MAUI/Avatar-view/Getting-Started.md
MAUI/Avatar-view/Migration.md
MAUI/Avatar-view/Overview.md
MAUI/Avatar-view/customization.md
MAUI/Avatar-view/how-to.md
MAUI/Avatar-view/visualstyles.md
MAUI/Busy-Indicator/AnimationType.md
MAUI/Busy-Indicator/Duration.md
MAUI/Busy-Indicator/Getting-Started.md
MAUI/Busy-Indicator/IndicatorColor.md
MAUI/Busy-Indicator/Make-Busy-Animation-Idle.md
MAUI/Busy-Indicator/Migration.md
MAUI/Busy-Indicator/Set-Header.md
MAUI/Busy-Indicator/Sizing.md

API links added for properties in AvatarView and SfBusyIndicator.

MAUI-2548 Added API links for SfAvatarView and SfBusyIndicator

---

MAUI/Maps/migration.md
maui-toc.html

Hi @vigneshrameshsync,
I have prepared MD document for the Xamarin SfMaps to .Net MAUI SfMaps. Can you please review and merge this.
Regards,
Ragul S V

MAUI-2481: How to migrate from Xamarin Forms Maps control to .NET MAUI Maps control.

---

MAUI/Avatar-view/Getting-Started.md

MAUI-2548 Added API links for SfAvatarView and SfBusyIndicator 

---

MAUI/Scheduler/resource-view.md

MAUI-2359-MAUIUGDocument-API links updated.

---

MAUI/Maps/migration.md

Hi @vigneshrameshsync,
I have completed the .Net MAUI map migration document content review changes. Can you please review and merge this.
Content Review task link: https://syncfusion.atlassian.net/browse/DOC-4539
Reagards,
Ragul S V

MAUI-2481: Map migration document content review changes.

---

MAUI/DataGrid/migration.md

I have updated the code alignment for Migration document for MAUI DataGrid.

MAUI-2406 - Migration UG content for MAUI DataGrid

---

MAUI/Scheduler/appointments.md

Recurrence helper method added.
Content review task: https://syncfusion.atlassian.net/browse/DOC-4560

MAUI-2359-UGImages-Recurrence helper method added.

---

MAUI/Radial-Gauge/axes.md
MAUI/Radial-Gauge/content-pointer.md
MAUI/Radial-Gauge/pointers.md
MAUI/Radial-Gauge/range-pointer.md
MAUI/Radial-Gauge/shape-pointer.md

To add the missing API links for the respective properties in MAUI linear gauge and radial gauge controls.

MAUI-2750 : Add missing APIs in MAUI linear gauge and radial gauge controls

---

MAUI/ListView/loadmore.md
MAUI/ListView/selection.md

Made API Correction in ListView UG

MAUI-2755 Correct the APIs in ListView UG

---

MAUI/ListView/working-with-sflistview.md

XAMARIN-43879 Added note for longpress interaction in maui ListView.
Content reviewed by @Chrispineagunja .

XAMARIN-43879 Added note for longpress interaction in maui ListView.

---

MAUI/ProgressBar/migration.md
maui-toc.html

I have prepared migration document for the maui progress bar control. please review it.
Regards,
Balachandar.

MAUI-3111 : Prepare migration document for progress bar control.

---

MAUI/Maps/migration.md

Hi @vigneshrameshsync 
I have prepared migration document for the sublayer in MAUI Maps control. please review it?
Regards,
Shalini

MAUI-3132 : Prepare migration document for sublayer in MAUI Maps control.

---

MAUI/Scheduler/reminders.md
maui-toc.html

Provide  Reminder Alert  event to notify the reminder for scheduler appointments.
**Purpose/benefits of the feature**
This feature is used to remind the scheduler appointment before appointment's start time by using scheduler event ReminderAlertOpening event. 
**Use cases**
This feature is used to notify the scheduler reminder before the appointment start time and it can be use by enabling local notification or popup.
**What problem it solves?**
**Do competitors have this this feature? If possible, add comparison and also share relevant links. Anyhow, this should be available in requirements doc which you can link** 
https://syncfusion.sharepoint.com/:w:/r/sites/MAUI/_layouts/15/Doc.aspx?sourcedoc=%7BA4F3EE73-A7DF-4063-8B8B-3D389CB8F728%7D&file=MAUI-2266%20%E2%80%93%20Scheduler%20Reminder. …

MAUI-2937-Appointment reminder in scheduler

---

MAUI/Maps/migration.md

Hi @vigneshrameshsync 
I fixed the UG title rendering issue. Could you please review it and let me Know if you have any concerns?
Regards,
Shalini Ashokan.

MAUI-3132 : Fixed H2 title rendering issue on maps migration document.

---

MAUI/ListView/item-size-customization.md
MAUI/ListView/loadmore.md
MAUI/ListView/migration.md
MAUI/ListView/mvvm.md
MAUI/ListView/viewappearance.md
MAUI/ListView/working-with-sflistview.md

Changed the name of the Property 
ItemData -> DataItem
isBusy-> is LazyLoading

MAUI-1860 : Modified the ListView UG API

---

MAUI/Autocomplete/Migration.md
MAUI/Autocomplete/Selection.md
MAUI/ComboBox/Migration.md

Added "Customizations in Drop-Down"
Updated Multiple selection from "Multiple Selection with Tokens and Delimiter"  in Migration page of Autocomplete and ComboBox control.

MAUI-3102 Update upcoming features in migration page in Autocomplete and ComboBox

---

MAUI/Maps/legend.md
MAUI/Maps/migration.md
MAUI/Maps/tooltip.md

Hi @vigneshrameshsync,
I have updated the API reference links for tooltip and legend customization related UG document.

MAUI-3167 API reference links updated for tooltip and legend customization

---

MAUI/Scheduler/reminders.md

Added API Links for scheduler reminders.

MAUI-2937- Added API link for Appointment Reminders 

---

MAUI/TabView/Tab-Item-Customization.md

The tab tags were added to the Image Text Spacing property

MAUI-3142 Tabs tags added

---

MAUI/TabView/Tab-Item-Customization.md

The tab tags were added to the Image Text Spacing property

MAUI-3142 Tabs tag added

---

MAUI/CircularProgressBar/Animation.md
MAUI/CircularProgressBar/Overview.md
MAUI/LinearProgressBar/Overview.md

I have added bullet syntax for the overview pages and added the missed API reference links.
regards,
Balachandar.

MAUI-3155 : Added bullets for the overview page key features.

---

MAUI/Scheduler/accessibility.md
MAUI/Scheduler/reminders.md

API links added for tapped event

MAUI-2937-Added-Tapped-Event-API-Links

---

MAUI/Scheduler/reminders.md

Added scheduler and custom reminder sample links.

MAUI-2937-Added reminder sample links

---

MAUI/Cartesian-Charts/Appearance.md
MAUI/Cartesian-Charts/Axis/Types.md
MAUI/Circular-Charts/Appearance.md
MAUI/Circular-Charts/DoughnutChart.md
maui-toc.html

MAUI-3153 Update logarithmic axis content

---

MAUI/Cartesian-Charts/Selection.md
maui-toc.html

Add selection behavior UG for cartesian chart.

MAUI-1858 Move selection behavior for cartesian chart UG to hotfix

---

MAUI/Scheduler/reminders.md

API link changes done for reminders

MAUI-2937-Reminder API link changes

---

MAUI/Maps/migration.md

I have added the asterisk for the renamed API in migration document for MAUI Map control.
Regards,
Balachandar.

MAUI-3213 : Asterisk added for the renamed API in migration document for MAUI Map control.

---

MAUI/ListView/migration.md

Included IsBusy,IsLazyLoading API changes in Migration topic.

MAUI-1860 : Included IsBusy,IsLazyLoading API changes.

---

MAUI/Scheduler/accessibility.md
MAUI/Scheduler/reminders.md

MAUI-3314-Add the API link for UG documentation

MAUI-3314-Add the API link for UG documentation

---

MAUI/Scheduler/reminders.md

MAUI-2937- Reminder Corrections updated

---

MAUI/Scheduler/calendar-types.md

MAUI-3314-Modified the code snippet alignment

MAUI-3314-Modified the code snippet alignment

---

MAUI/ListView/migration.md

Resolved Migration UG alignment issue

XAMARIN-44046 : Resolved the UG alignment issue

---

MAUI/Barcode-Generator/one-dimensional-symbology.md
MAUI/Linear-Gauge/getting-started.md
MAUI/Radial-Gauge/axes.md
MAUI/Radial-Gauge/getting-started.md

-Corrected code snippet indent issues in 3 controls

MAUI-3397 : Fixed the indent issues in gauges UG

---

MAUI/System-Requirements.md

Updated the requirements document for MAUI

MAUI-3102 Updated the requirements document for MAUI

---

MAUI/Funnel-Charts/Getting-Started.md
MAUI/Funnel-Charts/Overview.md
MAUI/Pyramid-Charts/Getting-Started.md
MAUI/Pyramid-Charts/Overview.md
maui-toc.html

Preparing UG document for funnel and pyramid charts
Referred the circular chart help document.
This UG document helps the user understand the pyramid and funnel charts.
None
None
None
Not Applicable
Not Applicable
None
None

MAUI-3668 Created the UG folder for Pyramid and Funnel charts.

---

MAUI/Cartesian-Charts/Appearance.md
MAUI/Cartesian-Charts/Area.md
MAUI/Cartesian-Charts/Axis/Axisline.md
MAUI/Cartesian-Charts/Axis/Gridlines.md
MAUI/Cartesian-Charts/Axis/Ticklines.md
MAUI/Cartesian-Charts/Axis/Types.md
MAUI/Cartesian-Charts/Column.md
MAUI/Cartesian-Charts/Fastline.md
MAUI/Cartesian-Charts/Getting-Started.md
MAUI/Cartesian-Charts/Line.md
MAUI/Cartesian-Charts/Scatter.md
MAUI/Cartesian-Charts/Tooltip.md
MAUI/Cartesian-Charts/Zooming-and-panning.md
MAUI/Cartesian-Charts/migration.md
MAUI/Circular-Charts/Appearance.md
MAUI/Circular-Charts/DoughnutChart.md
MAUI/Circular-Charts/Explode.md
MAUI/Circular-Charts/Getting-Started.md
MAUI/Circular-Charts/PieChart.md
MAUI/Circular-Charts/Tooltip.md

Changed improper code for MAUI Chart

WINUI-3165 - Change improper codes in MAUI Chart UG

---

MAUI/Cartesian-Charts/Axis/Range-padding.md
MAUI/Cartesian-Charts/Axis/Types.md
MAUI/Cartesian-Charts/DataLabels.md
MAUI/Cartesian-Charts/Selection.md
MAUI/Cartesian-Charts/migration.md
MAUI/Circular-Charts/Selection.md
MAUI/Circular-Charts/migration.md

Committed the changes by adding proper redirect links.

WINUI-3163-Committed the changes by adding proper redirect links

---

MAUI/Circular-Charts/Appearance.md
MAUI/Circular-Charts/DoughnutChart.md
MAUI/Circular-Charts/Explode.md
MAUI/Circular-Charts/PieChart.md
MAUI/Circular-Charts/Tooltip.md
MAUI/Circular-Charts/migration.md

WINUI-3165 - Ensured improper code in MAUI Chart

---

MAUI/Cartesian-Charts/Axis/Types.md

changed the opposed axis to the opposite side

XAMARIN-44343 - MAUI chart axis type correction

---

MAUI/Funnel-Charts/migration.md
MAUI/Pyramid-Charts/migration.md
maui-toc.html

Created the migration page for pyramid and funnel charts.
Referred the circular chart migration page - https://help.syncfusion.com/maui/circular-charts/migration
This UG document helps to guide the user to understand the feature.
None
None
None
Not Applicable
Not Applicable
None
None

MAUI-3668 Migration page for pyramid and funnel charts

---

MAUI/Circular-Charts/migration.md

Modified the migrate page circular chart UG document

MAUI-3834 Modified the migrate page in circular chart

---

MAUI/Cartesian-Charts/migration.md
MAUI/Circular-Charts/migration.md

Modified the migrate page of cartesian chart

MAUI-3834 Modified the migrate page of cartesian chart

---

MAUI/Funnel-Charts/migration.md

Funnel chart compilation issue fix.

MAUI-3668 Funnel UG compilation issue fix

---

MAUI/Pyramid-Charts/migration.md

updated the migration page for pyramid chart

MAUI-3668 Updated the migration doc

---

MAUI/PDF-Viewer/Getting-Started.md
MAUI/PDF-Viewer/Magnification.md
MAUI/PDF-Viewer/Open-a-Document-From-URL.md
MAUI/PDF-Viewer/Open-a-Document.md
MAUI/PDF-Viewer/Open-a-Password-Protected-Document.md
MAUI/PDF-Viewer/Overview.md
MAUI/PDF-Viewer/Page-Navigation.md
MAUI/PDF-Viewer/UI-Customization.md
maui-toc.html

Added UG for other features in the new PDF Viewer control.

MAUI-3897: Add UG for the new PDF Viewer control.

---

MAUI/Cartesian-Charts/migration.md

Resolve the cartesian migrate page issues

MAUI-3834 [UG] Resolve the cartesian migrate page issues

---

MAUI/Funnel-Charts/Appearance.md
MAUI/Funnel-Charts/migration.md
MAUI/Pyramid-Charts/Appearance.md
MAUI/Pyramid-Charts/migration.md

Aligned the code snippet for migration and data label guidelines

MAUI-3936 Aligned the code snippet

---

MAUI/DataForm/Overview.md
MAUI/DataForm/getting-started.md
maui-toc.html

I have included the following contents for Getting Started in MAUI DataForm:
* Key features
* Creating an application using the .NET MAUI DataForm
* Register the handler
* Creating data object
* Set data object to data form
* Defining editors

MAUI-3715-Included UG for Getting Started in MAUI DataForm

---

MAUI/TextInputLayout/Migration.md

Added the ContainerBackground API changes in SfTextInputLayout Migration page in UG

MAUI-4026 Update the migration page in SfTextinputlayout UG

---

MAUI/DataForm/migration.md
maui-toc.html

I have included the following contents for Localization and RTL in MAUI DataForm:
* Namespaces 
* Initialize control
* Classes 
* Properties
* Enums
* Events
* Methods
* Upcoming Features

MAUI-3858-Included UG for Migrate from Xamarin.Forms in MAUI DataForm 

---

MAUI/DataForm/migration.md
maui-toc.html

Reviewed PR : https://github.com/syncfusion-content/maui-docs/pull/686
I have included the following contents for Localization and RTL in MAUI DataForm:
* Namespaces 
* Initialize control
* Classes 
* Properties
* Enums
* Events
* Methods
* Upcoming Features

MAUI-3858-Included UG for Migrate from Xamarin.Forms in MAUI DataForm

---

MAUI/PDF-Viewer/Getting-Started.md
MAUI/PDF-Viewer/Magnification.md
MAUI/PDF-Viewer/Open-a-Document-From-URL.md
MAUI/PDF-Viewer/Open-a-Document.md
MAUI/PDF-Viewer/Open-a-Password-Protected-Document.md
MAUI/PDF-Viewer/Overview.md
MAUI/PDF-Viewer/Page-Navigation.md

Updated UG for the new PDF Viewer control.

MAUI-3897: Update UG for the new PDF Viewer control. #723

---

MAUI/Rating/Migration.md

Addressed the review changes for rating in the staging website

MAUI-4031 Addressed the review changes for rating

---

MAUI/DataForm/migration.md

Included review changes for Migrate from Xamarin.Forms in MAUI DataForm
Content Review Task: https://syncfusion.atlassian.net/browse/DOC-5030

MAUI-3981-Included review changes for Migrate from Xamarin.Forms in MAUI DataForm

---

MAUI/Funnel-Charts/Appearance.md
MAUI/Funnel-Charts/Getting-Started.md
MAUI/Funnel-Charts/migration.md
MAUI/Pyramid-Charts/Appearance.md
MAUI/Pyramid-Charts/Getting-Started.md

Added the sample for getting started guideline.

MAUI-3936 Added the sample for getting started guideline

---

MAUI/Cartesian-Charts/Getting-Started.md
MAUI/Cartesian-Charts/migration.md
MAUI/Circular-Charts/Getting-Started.md

The migration page for the cartesian chart has been updated, and the cartesian and circular chart getting started samples have been added. 

MAUI-3834 [UG] Updated the migration page and added getting started samples

---

MAUI/DataForm/grouping.md
maui-toc.html

Included changes for title and grouping in  DataForm UG

MAUI-3981-Included changes in DataForm UG

---

MAUI/Calendar/getting-started.md

- Comments addressed for Getting started UG content

MAUI-3661-Getting Started UG for .Net MAUI Calendar

---

MAUI/DataForm/Data-annotations.md
MAUI/DataForm/Validation.md
MAUI/DataForm/getting-started.md
MAUI/DataForm/layout.md

Hi @Jeyasri-Murugan,
I have resolved syntax error in MAUI DataForm. So please review and share your suggestions.
Regards,
Karthick M.

MAUI-3722-Resolved syntax error in MAUI DataForm.

---

MAUI/DataForm/Data-annotations.md
MAUI/DataForm/Validation.md
MAUI/DataForm/getting-started.md
MAUI/DataForm/layout.md

Hi @Jeyasri-Murugan,
I have resolved syntax error in MAUI DataForm. So please review and share your suggestions.
Regards,
Karthick M.

MAUI-3722-[Master branch]Resolved syntax error in MAUI DataForm. 

---

MAUI/DataForm/Data-annotations.md
MAUI/DataForm/Validation.md
MAUI/DataForm/getting-started.md
MAUI/DataForm/layout.md

Resolved syntax error in MAUI DataForm. So please review and share your suggestions.

MAUI-3722-[Hotfix]Resolved syntax error in MAUI DataForm.

---

MAUI/DataForm/Data-annotations.md

MAUI-3923 - [Master] Fixed DataForm syntax issues

---

MAUI/DataForm/Data-annotations.md

MAUI-3923 - [Development] Fixed DataForm syntax issues

---

MAUI/DataForm/Data-annotations.md

MAUI-3923 - [Hotfix] Fixed DataForm syntax issues

---

MAUI/DataForm/Data-annotations.md
MAUI/DataForm/Validation.md
MAUI/DataForm/getting-started.md
MAUI/DataForm/layout.md
MAUI/DataForm/migration.md

Updated dataform content alignment issues

MAUI-3923 - [Hotfix] Fixed DataForm content alignment issues

---

MAUI/DataForm/grouping.md
maui-toc.html

Included changes in DataForm  Grouping and title

MAUI-3981-[Hotfix] Included changes in DataForm

---

MAUI/Maps/migration.md
MAUI/Maps/shape-sublayer.md
MAUI/Maps/tile-layer.md
MAUI/Maps/zoom-pan.md

Hi @vigneshrameshsync 
I have added a API reference links for new APIs in tile layer. Could you please review it?
Regards,
Shalini Ashokan.

MAUI-3959 : Added API reference links for tile layer

---

MAUI/Calendar/migration.md

- Calendar Migration alignment updated.

MAUI-3671 Development - Migration alignment updated.

---

MAUI/DataGrid/data-binding.md

MAUI-3815 UG for Maintain Scroll Position

MAUI-3815 UG for Maintain Scroll Position

---

MAUI/DataGrid/Getting-started.md

MAUI-3815 Removed the DataGrid builder in  Getting-started

MAUI-3815 Removed the DataGrid builder in  Getting-started

---

MAUI/DataForm/Data-annotations.md
MAUI/DataForm/getting-started.md

Fixed alignment issue in getting started, overview and DataAnnotations

MAUI-3982 - Fixed alignment issues in DataForm

---

MAUI/ListView/emptyview.md

Added API link for Maui ListView EmptyView feature

MAUI-1723 : Added API link for Maui ListView EmptyView feature

---

MAUI/PDF-Viewer/Open-a-Document-From-Local-Storage.md
MAUI/PDF-Viewer/Open-a-Document.md
MAUI/PDF-Viewer/Open-a-Password-Protected-Document.md
maui-toc.html

Updated UG with the other features for the new PDF Viewer control.

MAUI-3897: Update UG for the new PDF Viewer control.

---

MAUI/Autocomplete/UI-Customization.md
MAUI/Avatar-view/customization.md
MAUI/Badge-View/Migration.md
MAUI/ComboBox/UI-Customization.md
MAUI/Rating/Appearance-Customization.md
MAUI/Rating/Appearance-and-Styling.md
MAUI/Rating/Getting-Started.md
MAUI/Rating/Migration.md
MAUI/Rating/Overview.md
MAUI/Rating/Precision-Mode.md
MAUI/Rating/Rating-Shape.md
MAUI/Rating/Restrict-User-Selection.md

MAUI-4032 API links added for Rating

---

MAUI/Backdrop/getting-started.md
MAUI/Backdrop/header-configuration.md

I have added the missed API links for backdrop UG. Please review it.
Regards,
Balachandar.

MAUI-3958 : Added missed API links for backdrop page UG.

---

MAUI/ListView/scrolling.md

Added API reference for CanMaintainScrollPosition API.

xamarin-44440 : Added API reference for CanMaintainScrollPosition API.

---

MAUI/ListView/scrolling.md

Added API reference to CanMaintainScrollPosition API

Xamarin-44440 : Added API reference to CanMaintainScrollPosition API

---

MAUI/Cartesian-Charts/Area.md

Added API link in area series marker support

MAUI-2853 [UG] Added API link in area series marker support

---

MAUI/ListView/swiping.md

Added the Reset SwipeView Automatically Heading

MAUI-3901 : Added the Reset SwipeView Automatically Heading

---

MAUI/Common/migration.md
MAUI/Introduction/MAUI-cross-platform-UI.md

* Aligned the controls in the migration document based on the volume releases.
* Added a release control UG link in the Introduction document and Arranged the alignments.

MAUI-2819 Updated the Introduction and Migration Documents.

---

MAUI/Autocomplete/UI-Customization.md
MAUI/Avatar-view/customization.md
MAUI/Badge-View/Migration.md
MAUI/ComboBox/UI-Customization.md
MAUI/Rating/Appearance-Customization.md
MAUI/Rating/Appearance-and-Styling.md
MAUI/Rating/Getting-Started.md
MAUI/Rating/Migration.md
MAUI/Rating/Overview.md
MAUI/Rating/Precision-Mode.md
MAUI/Rating/Rating-Shape.md
MAUI/Rating/Restrict-User-Selection.md

API links added for Rating to hotfix

MAUI-4032 API links added for Rating to hotfix

---

MAUI/TextInputLayout/Assistive-Labels.md
MAUI/TextInputLayout/Container-Type.md
MAUI/TextInputLayout/Custom-Font.md
MAUI/TextInputLayout/Custom-Icons.md
MAUI/TextInputLayout/Fixed-Hint-Position.md
MAUI/TextInputLayout/Getting-Started.md
MAUI/TextInputLayout/How-To.md
MAUI/TextInputLayout/Migration.md
MAUI/TextInputLayout/States-And-Colors.md
MAUI/TextInputLayout/Supported-input-views.md

Added API reference link for SfTextInputLayout control UG

MAUI-4030 Added API reference link for SfTextInputLayout control UG

---

MAUI/PDF-Viewer/Getting-Started.md
MAUI/PDF-Viewer/Magnification.md
MAUI/PDF-Viewer/Open-a-Document-From-Local-Storage.md
MAUI/PDF-Viewer/Open-a-Document-From-URL.md
MAUI/PDF-Viewer/Open-a-Document.md
MAUI/PDF-Viewer/Open-a-Password-Protected-Document.md
MAUI/PDF-Viewer/Overview.md
MAUI/PDF-Viewer/Page-Navigation.md
MAUI/PDF-Viewer/UI-Customization.md

Updated UG with the API links in the new PDF Viewer control.

MAUI-3897: Update UG with the API links in the new PDF Viewer control.

---

MAUI/TextInputLayout/Custom-Font.md
MAUI/TextInputLayout/States-And-Colors.md

Corrected the API name in SfTextInputLayout UG

MAUI-4026 Error Correction in the States and Colors page SfTextInputLayout UG

---

MAUI/TextInputLayout/States-And-Colors.md

Changed the spelling error of focused word in SfTextInputLayout control.

MAUI-4026 Correct the spelling error in SfTextInputLayout UG

---

MAUI/DataForm/Validation.md
MAUI/DataForm/grouping.md
MAUI/DataForm/layout.md
MAUI/DataForm/localization.md
MAUI/DataForm/right-to-left.md

Included renaming changes of DataForm images

MAUI-4127- Included changes in DataForm UG images 

---

MAUI/DataGrid/Getting-started.md

MAUI-3815 - Include the Getting Started Video for MAUI DataGrid

MAUI-3815 - Include the Getting Started Video for MAUI DataGrid

---

MAUI/PDF-Viewer/Getting-Started.md
MAUI/PDF-Viewer/Migration.md
maui-toc.html

Updated PDF Viewer UG with the Xamarin migration page.

MAUI-3897: Update PDF Viewer UG with the Xamarin migration page

---

MAUI/Calendar/overview.md
maui-toc.html

- Added the toc file path and Cleared the Overview UG errors

MAUI-3660-OverView_UG_Updated_and_TOC_File_Added

---

MAUI/Common/migration.md
MAUI/Introduction/MAUI-cross-platform-UI.md

* Updated the Pdf Viewer migration page link.

MAUI-4123 Updated PDF Viewer Migration Page Link.

---

MAUI/Calendar/views.md

MAUI-3662-Views_UG_Content_Updated_MAUI_Calendar

---

MAUI/Cartesian-Charts/migration.md
MAUI/Circular-Charts/migration.md

MAUI- Added the cartesian and circular chart known issue

MAUI-4338- Added the cartesian and circular chart known issue

---

MAUI/Calendar/date-restrictions.md
MAUI/Calendar/getting-started.md
MAUI/Calendar/headers.md
MAUI/Calendar/migration.md
MAUI/Calendar/overview.md
MAUI/Calendar/views.md

- Added the API Links to the migration and Getting started UG

MAUI-3661-Added_API_Links_For_Migration_and_Getting_started_UG

---

MAUI/Demos/Demo.md

Added documentation for the iOS Sample browser

MAUI-4027 Added documentation for iOS Sample browser

---

MAUI/Calendar/migration.md
MAUI/Calendar/selections.md
maui-toc.html

- Calendar migration UG syntax errors updated.

MAUI-3669 Calendar UG syntax errors updated.

---

MAUI/Common/migration.md
MAUI/Demos/Demo.md

Changed the SfNumericTextBox release details.

MAUI-4123 Update the MAUI Controls Release Detail.

---

maui-toc.html

Updated UG displayed order of PDF Viewer control.

MAUI-3897: Update UG displayed order of PDF Viewer.

---

MAUI/DataGrid/Getting-started.md

Issue fix in MAUI DataGrid getting started video

MAUI-4416 Issue fix in MAUI DataGrid getting started video

---

maui-toc.html

I have updated the UG sample list based on alphabetical order. Please review the changes and let me know of any concerns.
Regards,
Muniappan S

MAUI-4439- UG sample list updated with alphabetical order

---

MAUI/Scheduler/getting-started.md

I have added the MAUI Scheduler Tutorial video in the Getting started UG. PLease review this and let me know any concerns.
Regards,
Muniappan S

MAUI-4439- MAUI Scheduler Tutorial video added in the UG

---

MAUI/Calendar/migration.md

- Migration API Link has modified

MAUI-4016-Migration_API_Link_Syntax_Modified

---

MAUI/Barcode-Generator/getting-started.md

- Barcode UG you tube video link updated in Getting started

MAUI-3661-Barcode_UG_Video_Link_Updated

---

MAUI/SignaturePad/getting-started.md

Video link added for Signature Pad in Getting started page

MAUI-4459 Video link added for Signature Pad in Getting started page

---

MAUI/Slider/getting-started.md

Added video link in slider ug.

MAUI-3952 Added video link in slider ug

---

MAUI/Autocomplete/Getting-Started.md
MAUI/SignaturePad/getting-started.md

UG Video added for Autocomplete and syntax correction in SignaturePad

MAUI-4459 UG video link added for Autocomplete control to hotfix

---

MAUI/ListView/getting-started.md

Updated GettingStarted video tutorial details in UG - ListView

MAUI-4511 : Update GettingStarted video tutorial details in UG - ListView

---

MAUI/DateTime-Slider/getting-started.md

Added video link in date-time slider ug.

MAUI-3952-Added video link in date-time slider ug

---

MAUI/Maps/vector-layers/arc-layer.md
MAUI/Maps/vector-layers/circle-layer.md
MAUI/Maps/vector-layers/line-layer.md
MAUI/Maps/vector-layers/polygon-layer.md
MAUI/Maps/vector-layers/polyline-layer.md

Hi @sheiksyedm 
I have updated UG document for MAUI Maps Vector Layer. I flip a latitude and longitude property. So I update UG code examples for vector layer. Could you please review it and let me know if you have any concerns?
Regards,
Shalini Ashokan.

MAUI-4606: Updated the UG document for Maui Maps Vector layer

---

MAUI/System-Requirements.md

Made changes in System Requirements as it need to be up to date

MAUI-4657 System Requirement changes in documentation

---

MAUI/TextInputLayout/Getting-Started.md

UG video link added for TextInputLayout control

MAUI-4459 UG video link added for TextInputLayout control

---

MAUI/Upgrade/how-to-upgrade.md

Hi @Aishwarya-Ganesan,
Please review permanent changes for Maui.
Regards,
Sharly A.

SEO-3353 - Maui changes

---

MAUI/ComboBox/Getting-Started.md
MAUI/Rating/Getting-Started.md

UG video link added for ComboBox and Rating

MAUI-4459 UG video link added for ComboBox and Rating

---

MAUI/Calendar/getting-started.md
MAUI/Radial-Gauge/getting-started.md

Added the Getting started You tube video Link for .NET MAUI Radial gauge and calendar control.

MAUI-4767-GettingStarted_Video_Link_Added_For_.NET_MAUI_RagialGauge_Calendar_Control

---

MAUI/Badge-View/Getting-Started.md
MAUI/Effects-View/Getting-Started.md

Video link added for Badge View and Effects View

MAUI-4657 Video link added for Badge View and Effects View

---

MAUI/ListView/viewappearance.md

Update UG for MouseHover support in .NET MAUI ListView

MAUI-4761 : Update UG for MouseHover support in .NET MAUI ListView

---

MAUI/System-Requirements.md

Update System Requirements for .NET MAUI

MAUI-4657 Update System Requirements

---

MAUI/Cartesian-Charts/migration.md

Added the known issue in migration .

MAUI-3684-Prepare-UG-for-box-and-whisker-series-support-in-MAUI-chart

---

MAUI/DataGrid/migration.md

I have updated the MAUI SfDataGrid Upcoming features list.

MAUI-5020-Updated SfDatagrid feature list

---

MAUI/Popup/migration.md
maui-toc.html

Prepared Migration UG for Popup Control

MAUI-5238 : Prepare Migration UG for Popup Control

---

MAUI/PDF-Viewer/Right-To-Left.md
maui-toc.html

Right to left UG documentation is added for .NET MAUI PDF Viewer

MAUI-4910: RTL UG documentation

---

MAUI/Introduction/MAUI-cross-platform-UI.md

Description:
Added new controls in the Introduction page below-mentioned list items:
MISCELLANEOUS - Shimmer
Editors - Masked Entry
Layout - Popup

MAUI-4293 Adding MaskedEntry,Shimmer and Popup controls in the list

---

MAUI/PDF-Viewer/Open-a-Document.md
MAUI/PDF-Viewer/Text-Search.md
maui-toc.html

Updated UG for text search feature

MAUI-4903: Text search UG documentation

---

MAUI/Popup/Popup-Events.md
MAUI/Popup/getting-started.md
MAUI/Popup/migration.md
maui-toc.html

Prepared UG for Popup Events and Commands in .NET MAUI popup

MAUI-5238 : Prepare UG for Popup Events and Commands in .NET MAUI popup

---

MAUI/PDF-Viewer/Document-Outline.md

Resolved the Encoding error reported in the Document-Outline.md file reported by core team
https://helpstaging.syncfusion.com:14038/error/03-22-2023/05/maui.txt

MAUI-4909: Resolved the Encoding error in PDF Viewer UG

---

MAUI/Popup/migration.md

Resolved the syntax error on Migration UG

MAUI-5238 Resolve the syntax error on Migration UG

---

MAUI/Common/migration.md
MAUI/Masked-Entry/Migration.md

Hi Team,
I Changed the common UG pages based on Vol 1 2023, kindly review and merge the same
Regards

MAUI-4293 Common UG page changes in Vol 1 2023

---

MAUI/PDF-Viewer/Keyboard-Shortcuts.md

Corrected the highlightings of the keyboard key names.

MAUI-4935 : UG documentation for bookmarks, TOC and keyboard shortcuts

---

MAUI/PDF-Viewer/UI-Customization.md

MAUI-4903: UG syntax error is resolved

MAUI-4903: UG syntax error is resolved [PDF Viewer]

---

MAUI/Popup/popup-size.md

MAUI-5183: Highlight the properties.

---

MAUI/Popup/layout-customizations.md
MAUI/Popup/popup-positioning.md

Highlighted APIs in Table for MAUI Popup UG

MAUI-5239 : Highlighted APIs in Table for MAUI Popup UG

---

MAUI/Scheduler/getting-started.md

I have added the youtube video for the MAUI Scheduler getting started. As per the website team guideline, I have updated it. Please review this and let me know of any concerns.
Reference: https://syncfusion.sharepoint.com/sites/Install/SitePages/Maui-Read-Me.aspx
Regards,
Muniappan S

MAUI-4914- MAUI Scheduler getting started video added

---

MAUI/Shimmer/built-in-views.md
MAUI/Shimmer/getting-started.md
MAUI/Shimmer/migration.md

- Shimmer UG and migration document updated

MAUI-5194-Development- Shimmer UG Updated

---

MAUI/Shimmer/built-in-views.md
MAUI/Shimmer/getting-started.md
MAUI/Shimmer/migration.md

- Shimmer UG and migration document updated

MAUI-5194-Master - Shimmer UG Updated

---

MAUI/DataGrid/Stacked-Header.md
MAUI/DataGrid/Summaries.md
MAUI/DataGrid/freeze-panes.md
MAUI/DataGrid/scrolling.md

API reference links have been added to the following new datagrid UG documentations,
* Freeze panes
* Stacked Headers
* Summaries
* Scrolling

MAUI-4940 - [Others] Provided the api reference link for the new APIs.

---

MAUI/DataForm/floating-label-layout.md
MAUI/DataForm/layout.md
MAUI/DataForm/migration.md

Added API links for DataForm Floating label layout

MAUI-5164-Added API links for DataForm Floating label layout

---

MAUI/Circular-Charts/migration.md
MAUI/Funnel-Charts/migration.md
MAUI/Pyramid-Charts/migration.md

Added required changes in the migration pages.
- Regarding the ToggleSeriesVisibility property support in circular chart, funnel chart and pyramid chart.

MAUI-5208-Added required changes in the migration pages.

---

MAUI/Popup/Popup-Events.md
MAUI/Popup/getting-started.md
MAUI/Popup/layout-customizations.md
MAUI/Popup/migration.md
MAUI/Popup/popup-positioning.md
MAUI/Popup/popup-size.md

Added API links for MAUI Popup UG

MAUI-5256 : Add API links for MAUI Popup UG

---

MAUI/visual-studio-integration/download-and-installation.md
MAUI/visual-studio-integration/overview.md
MAUI/visual-studio-integration/template-studio.md

Changed the platform name and  component name

MAUI-4945- Updated the MAUI Extensions UG

---

MAUI/DataForm/DataForm-settings.md
MAUI/DataForm/Editing.md
MAUI/DataForm/Validation.md
MAUI/DataForm/floating-label-layout.md
MAUI/DataForm/getting-started.md
MAUI/DataForm/grouping.md
MAUI/DataForm/layout.md
MAUI/DataForm/migration.md
MAUI/DataForm/right-to-left.md

Added example code changes in DataForm

MAUI-5174-Added example code changes in DataForm 

---

MAUI/Masked-Entry/Culture.md
MAUI/Masked-Entry/Formatting-Value.md
MAUI/Masked-Entry/Getting-Started.md
MAUI/Masked-Entry/Mask-Types.md
MAUI/Masked-Entry/Migration.md
MAUI/Masked-Entry/Overview.md
MAUI/TextInputLayout/Supported-input-views.md

Description:
Added API links for SfMaskedEntry and SfTextInputLayout(Supported Input View)

MAUI-5242-Adding API reference link in SfMaskedEntry control

---

MAUI/Scheduler/appointments.md
MAUI/Scheduler/calendar-types.md
MAUI/Scheduler/date-navigation-restriction.md
MAUI/Scheduler/day-week-views.md
MAUI/Scheduler/getting-started.md
MAUI/Scheduler/header-view.md
MAUI/Scheduler/load-on-demand.md
MAUI/Scheduler/migration.md
MAUI/Scheduler/month-view.md
MAUI/Scheduler/resource-view.md
MAUI/Scheduler/timeline-views.md

Added Scheduler example code syntax changes

MAUI-5164-Added Scheduler example code syntax changes

---

MAUI/DateTime-Range-Selector/getting-started.md
MAUI/DateTime-Range-Slider/getting-started.md

Added video link in date-time range slider ug.

MAUI-3952-Added video link in date-time range slider ug

---

MAUI/Popup/localization.md
MAUI/Popup/styles.md
MAUI/Popup/working-with-mvvm.md

Resolved Page not found error in MAUI Popup UG

MAUI-5282 : Resolved Page not found error in MAUI Popup UG

---

MAUI/Popup/styles.md

Added note for CornerRadius property.

MAUI-5125: Add note for Corner Radius property.

---

MAUI/Calendar/date-restrictions.md

- I have made the code corrections in Date restriction UG for calendar

MAUI-4755-Updated .NET MAUI Calendar UG

---

MAUI/Calendar/customizations.md

- Fixed error in .NET MAUI Calendar UG customization

MAUI-4755-Fixed error in UG for .NET MAUI Calendar

---

MAUI/Calendar/customizations.md

- Fixed error in .NET MAUI Calendar UG customization

MAUI-4755 Fixed error in UG for .NET MAUI Calendar

---

MAUI/Popup/getting-started.md

825535: Remove unwanted content.

---

MAUI/PDF-Viewer/Document-Outline.md

Hi @Aishwarya-Ganesan,
Worked on Bing report issues, so merge these changes
Regards,
Gowthaman

SEO-3615-bing-issues

---

MAUI/Popup/styles.md

Cleared the UG error in MAUI Popup/styles.md

MAUI-5282 : Clear the UG error in MAUI Popup/styles.md

---

MAUI/Common/migration.md

.NET MAUI Switch control changed from Volume 2 2023 to Volume 3 2023

Volume changed for the Switch control

---

MAUI/DataGrid/columns.md
MAUI/DataGrid/filtering.md
MAUI/DataGrid/sorting.md

The video of the columns and sorting is not shown properly and add video in filtering.
**Before changes**

825066 -[Others] Changes In UG.

---

MAUI/DataGrid/Column-sizing.md
MAUI/DataGrid/Row-height-Customization.md
MAUI/DataGrid/conditional-styling.md
MAUI/DataGrid/freeze-panes.md
MAUI/DataGrid/styling.md

Upload the video of the Row height customization, Column sizing, Freeze pane, Styling and conditional styling.

825066 -[Others] Updates In UG.

---

MAUI/Busy-Indicator/Getting-Started.md

829135-BusyIndicator_gettingStartedVideo

829135-BusyIndicator_gettingStartedVideo

---

MAUI/Shimmer/getting-started.md

- Added the you tube getting started video for the Shimmer control.

MAUI-4755-Hotfix-Shimmer UG Getting started video added

---

MAUI/Effects-View/Customization.md
MAUI/Funnel-Charts/migration.md
MAUI/Installation/Installation-Errors.md
MAUI/Installation/mac-installer/how-to-download.md
MAUI/Installation/offline-installer/how-to-download.md
MAUI/Installation/offline-installer/how-to-install.md
MAUI/Installation/web-installer/how-to-download.md
MAUI/Installation/web-installer/how-to-install.md
MAUI/Introduction/Overview.md
MAUI/Licensing/how-to-generate.md
MAUI/Licensing/licensing-errors.md
MAUI/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md
MAUI/Licensing/licensing-faq/where-can-i-get-a-license-key.md
MAUI/Licensing/overview.md

Hi @Girija-Rajendran,
Worked on redirection related fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-Redirection-tool-fixes

---

MAUI/PDF-Viewer/DocumentLoadNotifications.md
MAUI/PDF-Viewer/Hyperlink-Navigation.md
MAUI/PDF-Viewer/Localization.md
MAUI/PDF-Viewer/Open-a-Document.md
MAUI/PDF-Viewer/Open-a-Password-Protected-Document.md
MAUI/PDF-Viewer/Right-To-Left.md
MAUI/PDF-Viewer/Text-Search.md
MAUI/PDF-Viewer/UI-Customization.md

Description : 
Update content changes in UG documentation for following feature in Maui PDFViewer.
1. Document load notifications
2. Localization
3. Hyperlink Navigation
4. Text Search
5. Right to Left
6. Customize the loading indicator
7.  Handling password request
8. Opening a PDF document with annotations

832848 : Update content changes in UG documentation for provided features

---

MAUI/PDF-Viewer/Right-To-Left.md

Description:
Update content changes in UG documentation for  RTL feature
1.Right to Left

832848 : Update content changes in UG documentation for RTL feature

---

MAUI/Accordion/migration.md
MAUI/Expander/migration.md
maui-toc.html

Preview of Expander:
Preview of Accordion:

MAUI Expander & Accorion - added Migration guidelines.

---

MAUI/PDF-Viewer/Text-Selection.md

The Content review corrections are appended in the UG documentation contents.
Content review task link: https://dev.azure.com/Syncfusion-General/Documentation/_workitems/edit/757196

823731: UG documentation for text selection feature in .NET MAUI PDF Viewer

---

MAUI/PDF-Viewer/Text-Selection.md

Added separate topic for Copying the selected text in text selection feature

823731: PDF Viewer UG modifications

---

maui-toc.html

Update html chart changes

---

MAUI/PDF-Viewer/Document-Link-Annotations.md

Description : 
Removed Limitation in Documentation Link Annotations in Maui PDFViewer

833379 : Remove Limitation in Documentation Link Annotations

---

MAUI/Accordion/getting-started.md
MAUI/Expander/getting-started.md

Added Expander Events topic - SfExpander

Added Expander Events and Accordion topics

---

MAUI/DataForm/Editors.md
MAUI/Scheduler/drag-and-drop-appointments.md

Review changes added for Maui Scheduler and DataForm

829469 - Review changes added for Maui Scheduler and DataForm 

---

MAUI/Expander/appearance.md
MAUI/Expander/getting-started.md

Added Expander sample links in UG

831668 : Added Expander sample links in UG

---

MAUI/Accordion/appearance.md
MAUI/Accordion/bindablelayout.md
MAUI/Accordion/getting-started.md

Added Accordion sample links in UG and Done BindableLayout code changes

831668 : Added Accordion sample links in UG

---

maui-toc.html

I have added ImageEditor order in toc file

MAUI-834670 ImageEditor TOC file updated

---

maui-toc.html

I have fixed a tag issue on TOC file. Could you please review and merge it?
Regards,
Shalini.

MAUI-834670 Fix a tag issue on TOC file

---

MAUI/Calendar/calendar-identifier.md

- Updated the sample tag for calendar identifier UG

MAUI-5440-Development-Calendar UG updated

---

MAUI/Calendar/calendar-identifier.md

- Updated the sample tag for calendar identifier UG

MAUI-5440-Master-Calendar UG updated

---

MAUI/ImageEditor/Effects.md
MAUI/ImageEditor/getting-started.md

I have fixed a tag issue on MAUI image editor. Could you please review and merge it?
Regards,
Shalini.

MAUI-834670 Fix a tag issue on MAUI image editor.

---

MAUI/Cartesian-Charts/Candle.md

Updated the end tag for candle series

TASK-834623 Updated the End Tag

---

maui-toc.html

Hi Team,
Make changes in the page path in html page, kindly review and merge the same.
Regards

833946 Fixed the numeric entry page link issue - dev

---

MAUI/Common/migration.md

Hi Team, 
I have changed the release timeline for Treeview control in .NET MAUI. Kindly review and merge the same
Regards

833946 Changed the release timeline for Treeview control - dev

---

MAUI/NumericEntry/Getting-Started.md

Hi Team
I have fixed the invalid byte sequence in UTF-8 in NumericEntry getting started page
Regards

833947 Fixed invalid byte sequence in UTF-8 in NumericEntry Getting Started Page - hotfix

---

MAUI/Chips/Chips Types.md
MAUI/Chips/Customization.md

Updated the Closing tabs in Chip UG Documentation.

831962- Updated the Closing tabs in Chip UG Documentation.

---

MAUI/Calendar/calendar-identifier.md

- API Link added to the Calendar Identifier UG file.

MAUI-5440-Added API link to the Calendar identifier UG

---

MAUI/ImageEditor/crop.md
MAUI/ImageEditor/getting-started.md
MAUI/ImageEditor/imagefilter.md
MAUI/ImageEditor/migration.md
MAUI/ImageEditor/transformation.md

[Hotfix] Update Maui ImageEditor's API Links

MAUI 833923 - [Hotfix] Update Maui ImageEditor's API Links

---

MAUI/Chips/Migration.md
maui-toc.html

Migration content added for chip control.

Migration added for chip control

---

MAUI/Chips/Migration.md
maui-toc.html

Migration content added for chip control.

Migration added for chips control

---

MAUI/ListView/item-drag-and-drop.md
MAUI/ListView/migration.md
maui-toc.html

Prepared ItemReordering UG in .NET MAUI ListView

UG DOCUMENTATION 831881:Prepare ItemReordering UG in .NET MAUI ListView

---

MAUI/DataForm/DataForm-settings.md
MAUI/DataForm/Editors.md
MAUI/DataForm/migration.md
MAUI/Scheduler/drag-and-drop-appointments.md
MAUI/Scheduler/migration.md

API links added for Maui DataForm and Scheduler

835034 - API links added for Maui DataForm and Scheduler 

---

MAUI/PDF-Viewer/Migration.md
MAUI/PDF-Viewer/Text-Selection.md

Description :
Update the API Links in UG documentation in Maui PDFViewer.
1. Migration
2. Text Selection

832848 : Update API Links in Text Selection and Migration 

---

MAUI/Common/migration.md
MAUI/NumericEntry/Migration.md

Description:
Here I have added the volume 2 release controls Migration Page link in the common folder.

835314-Adding-API-links-in-SfNumericEntry-UG-documentation

---

MAUI/Common/migration.md
MAUI/NumericEntry/Migration.md

Description:
Here I have added the volume 2 release controls Migration Page link in the common folder.

835314-Add-API-links-in-SfNumericEntry-UG-documentation

---

MAUI/Chips/Customization.md

Modified the Chip width request.

Modified the Chip width request.

---

MAUI/ComboBox/Filtering.md
MAUI/ComboBox/Searching.md

Added C sharp code for Filtering and Searching xaml contents.

835292-ComboBox_UG_Documentation

---

MAUI/ComboBox/Filtering.md
MAUI/ComboBox/Searching.md

Added code snippets for Filtering and Searching md files.

835292-ComboBox_UG

---

MAUI/Calendar/migration.md
MAUI/Shimmer/custom-view.md

- Shimmer UG updated
**Custom view:**
https://github.com/syncfusion-content/maui-docs/assets/105035937/301ddbc5-f59d-4a31-8a16-c801eb4a9123
**Shimmer view:**
https://github.com/syncfusion-content/maui-docs/assets/105035937/09eda32d-96f8-42fd-8f88-9be8cfcd372b

MAUI-5440-Shimmer UG updated

---

MAUI/DataGrid/editing.md
MAUI/DataGrid/grouping.md
MAUI/DataGrid/summaries.md
maui-toc.html

829272 -[Others] UG Correction.

---

MAUI/Autocomplete/UI-Customization.md
MAUI/ComboBox/UI-Customization.md

Added Cursor Position contents in Autocomplete and ComboBox md files.

835395_Cursor_Position_ug

---

MAUI/Common/migration.md

Description:
Here I have changed the expected release volume of SfSwitch contol.

835314-Modified expected release version for .NET MAUI SfSwitch control from Vol 3 to Vol 4 2023

---

MAUI/PDF-Viewer/Gesture-Events.md
maui-toc.html

UG documentation content is added for tapped event support provided in PDF Viewer

835052: UG for tapped event in PDF Viewer

---

MAUI/ImageEditor/events.md
MAUI/ImageEditor/getting-started.md
MAUI/ImageEditor/migration.md
MAUI/ImageEditor/overview.md
MAUI/ImageEditor/reset.md
MAUI/ImageEditor/save.md
MAUI/ImageEditor/shape.md
MAUI/ImageEditor/zooming.md

Hi @karthikraja-arumugam,
I have completed a content review changes for zoom in Maui image editor control. Could you please review it and let me know if you have any concerns?
Regards,
Shalini.

MAUI 829675 - Content review changes for Zoom in image editor.

---

MAUI/DataForm/Editors.md

Added changes for Maui DataForm numeric and masked text editor

835034 - Added changes for Maui DataForm 

---

MAUI/ImageEditor/reset.md
MAUI/ImageEditor/save.md
MAUI/ImageEditor/undo-redo.md
maui-toc.html

I have prepared content  for undo redo in Maui image editor control. Could you please review it and let me know if you have any concerns?
Regards,
Shalini.

MAUI 829675 - UG for Undo Redo action on MAUI image editor.

---

MAUI/Accordion/getting-started.md
MAUI/Expander/getting-started.md

Accordion and Expander UG correction Done

831881:Accordion and Expander UG correction Done

---

MAUI/DataGrid/summaries.md

Had Updated the content of UG.

836780 - [Others] UG Content Corrections

---

MAUI/Common/migration.md

Hi Team, 
Changed the timeline for SfCarousel and SfPullToRefresh controls in .NET MAUI. Kindly review and merge the same
Regards

Changed the timeline for SfCarousel and SfPullToRefresh controls in .NET MAUI

---

MAUI/DataForm/Editors.md

I have added the youtube video for the MAUI DataForm DataEditors. As per the website team guideline, I have updated it. Please review this and let me know of any concerns.
Reference: https://syncfusion.sharepoint.com/sites/Install/SitePages/Maui-Read-Me.aspx
Regards,
Muniappan S

829506- MAUI DataForm Data Editors video added

---

MAUI/DataForm/Editors.md

Added the correct UG link for SfNumericEntry control in the Data editors section of the MAUI DataForm UG

Added the correct UG link for SfNumericEntry in the MAUI DataForm UG

---

MAUI/PDF-Viewer/Keyboard-Shortcuts.md
MAUI/PDF-Viewer/Migration.md
MAUI/PDF-Viewer/Overview.md
MAUI/PDF-Viewer/Save-a-Document.md
maui-toc.html

Updated the PDF Viewer ug documentation  with respect to the newly added annotation features
1. Migration, 
2. Overview 
3. keyboard shortcuts

823696: UG documentation for the annotations support in PDF Viewer

---

MAUI/PDF-Viewer/Add-Remove-Modify-Annotations.md
MAUI/PDF-Viewer/Annotation-Collection.md
MAUI/PDF-Viewer/Annotations-Overview.md
MAUI/PDF-Viewer/Import-Export-Annotations.md
MAUI/PDF-Viewer/Ink.md
MAUI/PDF-Viewer/Lock-Unlock.md
MAUI/PDF-Viewer/Save-a-Document.md
MAUI/PDF-Viewer/Select-Deselect-Annotations.md
MAUI/PDF-Viewer/Shapes.md
MAUI/PDF-Viewer/Stamps.md
MAUI/PDF-Viewer/Text-Markups.md
MAUI/PDF-Viewer/Undo-Redo.md

Code alignment issues found in the staging link are fixed.

823696: UG documentation for the annotations support in PDF Viewer [Code alignment issues are fixed]

---

MAUI/ComboBox/Filtering.md
MAUI/ComboBox/Searching.md
MAUI/NumericEntry/Formatting.md
MAUI/NumericEntry/Migration.md
maui-toc.html

Conflicts resolved in master branch for tool controls

Conflicts resolved in master branch for tool controls

---

MAUI/PDF-Viewer/Add-Remove-Modify-Annotations.md
MAUI/PDF-Viewer/Annotation-Collection.md
MAUI/PDF-Viewer/Import-Export-Annotations.md
MAUI/PDF-Viewer/Ink.md
MAUI/PDF-Viewer/Keyboard-Shortcuts.md
MAUI/PDF-Viewer/Lock-Unlock.md
MAUI/PDF-Viewer/Save-a-Document.md
MAUI/PDF-Viewer/Select-Deselect-Annotations.md
MAUI/PDF-Viewer/Shapes.md
MAUI/PDF-Viewer/Stamps.md
MAUI/PDF-Viewer/Text-Markups.md

Code Alignment issues are fixed in PDF Viewer

823696 : Alignment issues are fixed in PDF Viewer

---

MAUI/Maps/bubble.md
MAUI/Maps/data-labels.md
MAUI/Maps/legend.md
MAUI/Maps/markers.md
MAUI/Maps/shape-sublayer.md
MAUI/Maps/shape.md
MAUI/Maps/tile-layer.md
MAUI/Maps/tooltip.md
MAUI/Maps/zoom-pan.md

Hi @Sasikumar3595 
Added the youtube video for the MAUI maps control. Please review this and let me know of any concerns.
Regards,
Indumathi R

835280-MapsVideo-Youtube video updated.

---

MAUI/PDF-Viewer/Add-Remove-Modify-Annotations.md
MAUI/PDF-Viewer/Annotation-Collection.md
MAUI/PDF-Viewer/Annotations-Overview.md
MAUI/PDF-Viewer/Document-Link-Annotations.md
MAUI/PDF-Viewer/DocumentLoadNotifications.md
MAUI/PDF-Viewer/Gesture-Events.md
MAUI/PDF-Viewer/Hyperlink-Navigation.md
MAUI/PDF-Viewer/Import-Export-Annotations.md
MAUI/PDF-Viewer/Ink.md
MAUI/PDF-Viewer/Keyboard-Shortcuts.md
MAUI/PDF-Viewer/Lock-Unlock.md
MAUI/PDF-Viewer/Right-To-Left.md
MAUI/PDF-Viewer/Save-a-Document.md
MAUI/PDF-Viewer/Select-Deselect-Annotations.md
MAUI/PDF-Viewer/Shapes.md
MAUI/PDF-Viewer/Stamps.md
MAUI/PDF-Viewer/Text-Markups.md
MAUI/PDF-Viewer/Text-Search.md
MAUI/PDF-Viewer/Text-Selection.md
MAUI/PDF-Viewer/UI-Customization.md
MAUI/PDF-Viewer/Undo-Redo.md
maui-toc.html

Committing the missing changes in the hotfix branch and alignment improvements

823696 : Gesture event inclusion and alignment changes for PDF Viewer

---

MAUI/PDF-Viewer/Add-Remove-Modify-Annotations.md
MAUI/PDF-Viewer/Annotation-Collection.md
MAUI/PDF-Viewer/Annotations-Overview.md
MAUI/PDF-Viewer/Document-Link-Annotations.md
MAUI/PDF-Viewer/DocumentLoadNotifications.md
MAUI/PDF-Viewer/Gesture-Events.md
MAUI/PDF-Viewer/Hyperlink-Navigation.md
MAUI/PDF-Viewer/Import-Export-Annotations.md
MAUI/PDF-Viewer/Ink.md
MAUI/PDF-Viewer/Keyboard-Shortcuts.md
MAUI/PDF-Viewer/Lock-Unlock.md
MAUI/PDF-Viewer/Right-To-Left.md
MAUI/PDF-Viewer/Save-a-Document.md
MAUI/PDF-Viewer/Select-Deselect-Annotations.md
MAUI/PDF-Viewer/Shapes.md
MAUI/PDF-Viewer/Stamps.md
MAUI/PDF-Viewer/Text-Markups.md
MAUI/PDF-Viewer/Text-Search.md
MAUI/PDF-Viewer/Text-Selection.md
MAUI/PDF-Viewer/UI-Customization.md
MAUI/PDF-Viewer/Undo-Redo.md
maui-toc.html

Reverts syncfusion-content/maui-docs#1350

Revert "823696 : Gesture event inclusion and alignment changes for PDF Viewer"

---

MAUI/Maps/shape-sublayer.md
MAUI/Maps/vector-layers/line-layer.md

Hi @Sasikumar3595 
Added the youtube video for the MAUI maps control. Please review this and let me know of any concerns.
Regards,
Indumathi R

835280-MapsVideo-Youtube video updated with timings.

---

MAUI/PDF-Viewer/Annotations-Overview.md
MAUI/PDF-Viewer/Keyboard-Shortcuts.md
maui-toc.html

Hotfix merge conflicts were resolved. 
Conflict PR link: https://github.com/syncfusion-content/maui-docs/pull/1356

823696: Hotfix merge conflicts were resolved

---

MAUI/PDF-Viewer/Add-Remove-Modify-Annotations.md
MAUI/PDF-Viewer/Annotation-Collection.md
MAUI/PDF-Viewer/Gesture-Events.md
MAUI/PDF-Viewer/Import-Export-Annotations.md
MAUI/PDF-Viewer/Ink.md
MAUI/PDF-Viewer/Lock-Unlock.md
MAUI/PDF-Viewer/Migration.md
MAUI/PDF-Viewer/Save-a-Document.md
MAUI/PDF-Viewer/Select-Deselect-Annotations.md
MAUI/PDF-Viewer/Shapes.md
MAUI/PDF-Viewer/Stamps.md
MAUI/PDF-Viewer/Text-Markups.md
MAUI/PDF-Viewer/Undo-Redo.md

Description : 
Update the API Links in UG documentation in Maui PDFViewer.
1. Migration Document
2. Annotation Collection
3. Select and Deselect Annotations
4. Add, Remove and Edit Annotations
5. Lock and Unlock Annotations
6. Import and Export Annotations
7. Undo and Redo
8. Save a Document
9. Annotations

840625 : Update the API Links in UG documentation in Maui PDF Viewer.

---

MAUI/PDF-Viewer/Migration.md

Description :
Update the API Links in UG documentation in Maui PDFViewer.
1. Migration Document

Update the API Links in UG documentation in Maui PDF Viewer.

---

MAUI/PDF-Viewer/Ink.md
MAUI/PDF-Viewer/Lock-Unlock.md
MAUI/PDF-Viewer/Text-Markups.md

PDF Viewer master branch merge conflicts are resolved

PDF Viewer master branch merge conflicts are resolved

---

MAUI/PDF-Viewer/Add-Remove-Modify-Annotations.md
MAUI/PDF-Viewer/Keyboard-Shortcuts.md
MAUI/PDF-Viewer/Select-Deselect-Annotations.md
maui-toc.html

UG content improvements for PDF Viewer
* TOC prioriization.
* Key board short cuts page SEO improvements.
* Content corrections

838177: UG content improvements for PDF Viewer

---

MAUI/PDF-Viewer/Ink.md
MAUI/PDF-Viewer/Lock-Unlock.md
MAUI/PDF-Viewer/Migration.md
MAUI/PDF-Viewer/Text-Markups.md

Description :
Update the changes for Ink, Lock-Unlock, Migration and Text-Markups document
1. Migration Document
2. Ink Annotation 
3. Textmarkup Annotation

840363 : Update the changes for Ink, Lock-Unlock, Migration and Text-Markups documents.

---

MAUI/PDF-Viewer/Add-Remove-Modify-Annotations.md
MAUI/PDF-Viewer/Select-Deselect-Annotations.md

Resolved the conflicting changes in master branch

[PDF Viewer] Resolved the conflicting changes in master branch

---

maui-toc.html

I have updated toc file  in Maui image editor control. Could you please review it and let me know if you have any concerns?
Regards,
Devanathan

[Dev]Update Toc file for ImageEditor

---

maui-toc.html

I have updated toc file  in Maui image editor control. Could you please review it and let me know if you have any concerns?
Regards,
Devanathan

[Hotfix]Update Toc file for ImageEditor

---

maui-toc.html

I have updated toc file  in Maui image editor control. Could you please review it and let me know if you have any concerns?
Regards,
Devanathan

[Master]Update Toc file for ImageEditor

---

MAUI/PDF-Viewer/Add-Remove-Modify-Annotations.md
MAUI/PDF-Viewer/Select-Deselect-Annotations.md

Updated the following missing changes in the UG live website.
1. Add, remove and edit annotations.
2. Select and deselect annotations

[PDF Viewer] Updated the missing changes in the live website

---

maui-toc.html

Missing changes in the TOC of master branch is added

[PDF Viewer] Master toc changes

---

MAUI/PDF-Viewer/Annotation-Collection.md
MAUI/PDF-Viewer/Annotations-Overview.md
MAUI/PDF-Viewer/Document-Link-Annotations.md
MAUI/PDF-Viewer/DocumentLoadNotifications.md
MAUI/PDF-Viewer/Gesture-Events.md
MAUI/PDF-Viewer/Hyperlink-Navigation.md
MAUI/PDF-Viewer/Import-Export-Annotations.md
MAUI/PDF-Viewer/Right-To-Left.md
MAUI/PDF-Viewer/Save-a-Document.md
MAUI/PDF-Viewer/Shapes.md
MAUI/PDF-Viewer/Stamps.md
MAUI/PDF-Viewer/Text-Search.md
MAUI/PDF-Viewer/Text-Selection.md
MAUI/PDF-Viewer/UI-Customization.md
MAUI/PDF-Viewer/Undo-Redo.md

We could see some of the hotfix changes are not moved in the master branch. So committing the changes manually

[PDF Viewer] Master UG content changes

---

MAUI/Maps/bubble.md
MAUI/Maps/data-labels.md
MAUI/Maps/legend.md
MAUI/Maps/markers.md
MAUI/Maps/shape-sublayer.md
MAUI/Maps/shape.md
MAUI/Maps/tile-layer.md
MAUI/Maps/tooltip.md
MAUI/Maps/vector-layers/line-layer.md
MAUI/Maps/zoom-pan.md

Hi @Sasikumar3595 
Added the youtube video for the MAUI maps control. Please review this and let me know of any concerns.
I was refered the DataGrid reference md file and they are using same iframe id.
**conditional styling:**
The [SfDataGrid](https://help.syncfusion.com/cr/maui/Syncfusion.Maui.DataGrid.html) allows you to customize the style of the individual cells and rows based on the requirements. 
To get start quickly with apply conditional styling in .NET MAUI DataGrid, you can check on this video:
<style>#**MAUIDataGridVideoTutorial**{width : 90% !important; height: 400px !important }</style> <iframe id='**MAUIDataGridVideoTutorial**' src="https://www.youtube.com/embed/1HHHz5isIM4?start=504"></iframe>
**Freeze panes.md**
To get start quickly with freeze rows and columns in .NET …

835280-MapsVideoLink-Youtube video link attached.

---

MAUI/ListView/viewappearance.md
MAUI/Popup/getting-started.md

Added video for Popup and Listview appearance

Added video for Popup and Listview appearance

---

MAUI/DataGrid/Column-sizing.md
MAUI/DataGrid/Column-types.md
MAUI/DataGrid/Getting-started.md
MAUI/DataGrid/Row-height-Customization.md

Hi @Girija-Rajendran 
|--|--|
|Task Category| .NET MAUI DataGrid|
|UX task| NA|
|Interlinking PR link| Interlinking -https://github.com/syncfusion-content/maui-docs/pull/1393|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/175104|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-DataGrid---Finalized-Money-Keywords-Status.aspx|
|.net maui datagrid|10-100 |Omit -10FT|To improve our FT experience |added CSS classes alignment format, images aligned in zigzag form, added documentation & Example links, unwanted space …

SEO-175104 - .NET MAUI Grid

---

MAUI/NumericEntry/Getting-Started.md
MAUI/TabView/Getting-Started.md
MAUI/TabView/Nested-Tabs.md

Video Link Added for Tab View and Numeric Entry Control.

Video Link Added for Tab View and Numeric Entry Control

---

MAUI/DataGrid/conditional-styling.md

- Adding conditional styling image for all the summaries

844883 - [Others] UG Corrections.

---

MAUI/PDF-Viewer/Getting-Started.md
MAUI/PDF-Viewer/Keyboard-Shortcuts.md

|--|--|
|Task Category|.NET MAUI PDF Viewer
|Content Task Link/Mail Screenshot|https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/760818|
|UX task|NA|
|Interlinking|PR - https://github.com/syncfusion-content/maui-docs/pull/1399|
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/175097/|
|Excel/SharePoint link|https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-PDF-Viewer---Money-Keywords.aspx|
|.net maui pdf viewer|10-100 |1FT|To move FT to the first position |Changed the content alignment, improved some content|
|.net maui pdf viewer control|0-10 |1FT |To improve the FT …

SEO-175097 .NET PDF Viewer Interlinking

---

MAUI/ListView/getting-started.md
MAUI/ListView/overview.md
MAUI/ListView/selection.md

Hi @Girija-Rajendran ,
|--|--|
|Task Category| .NET MAUI ListView|
|UX task| NA|
|Interlink PR link| Interlink -https://github.com/syncfusion-content/maui-docs/pull/1396
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/175118
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-ListView---Money-Keywords.aspx
|.net maui listview|10-100 |3FT|To improve our FT experience |added CSS classes alignment format, images aligned in zigzag form, added documentation & Example links, unwanted space removed. |
|.net maui listview …

SEO-175118-.NET-MAUI-ListView-Interlink

---

MAUI/Cartesian-Charts/Axis/Title.md
MAUI/Cartesian-Charts/migration.md

Update for MAUI Chart UG migration

846842 Update for MAUI Chart UG migration

---

MAUI/TreeView/migration.md
maui-toc.html

Migration from Xamarin documentation for .NET MAUI TreeView.

Migration from Xamarin documentation for .NET MAUI TreeView

---

MAUI/Cartesian-Charts/Zooming-and-panning.md

Updated UG document for selection zooming support in .NET MAUI

843020 Updated UG document for selection zooming support in .NET MAUI

---

MAUI/TreeView/getting-started.md
MAUI/TreeView/overview.md
maui-toc.html

Added Overview and Getting started UG.

Documentation for Treeveiw Overview and GettingStarted UG

---

MAUI/TreeView/data-population.md
maui-toc.html

Added code changes for DataPopulation UG

Added code changes for DataPopulation UG

---

MAUI/Cartesian-Charts/migration.md
MAUI/Circular-Charts/migration.md
MAUI/Funnel-Charts/migration.md
MAUI/Pyramid-Charts/migration.md

846842  - Chart UG Migration update

---

MAUI/Popup/migration.md
MAUI/TreeView/getting-started.md

Fixed the review correction in treeview and popup

---

MAUI/TreeView/appearance.md
MAUI/TreeView/data-population.md
MAUI/TreeView/getting-started.md
MAUI/TreeView/scrolling.md
maui-toc.html

Added TreeView appearance and scrolling UG documentation

Implemented UG documentation for treeview appearance and scrolling

---

MAUI/Cartesian-Charts/Axis/Title.md

Updated LabelExtent support in UG development

846842  Updated LabelExtent support in UG development

---

MAUI/CheckBox/Event.md
MAUI/CheckBox/Getting-Started.md
MAUI/CheckBox/Overview.md
MAUI/CheckBox/Visual-Customization.md
MAUI/CheckBox/VisualStates.md
MAUI/RadioButton/Event.md
MAUI/RadioButton/Getting-Started.md
MAUI/RadioButton/Grouping.md
MAUI/RadioButton/Overview.md
MAUI/RadioButton/Visual-Customization.md
MAUI/RadioButton/VisualStates.md

- Added Radio Button and CheckBox UG content.

Made review changes in UG.

---

MAUI/ImageEditor/events.md
MAUI/ImageEditor/save.md

I have added UG content for image browse and save picker feature.

MAUI 843540 - Added UG content for image editor Save and browse picker

---

MAUI/TreeView/appearance.md
MAUI/TreeView/scrolling.md

Resolved the syntax error

---

MAUI/ImageEditor/getting-started.md
MAUI/ImageEditor/toolbar-customization.md
maui-toc.html

I have improved a toolbar UG content.

MAUI 843542 - Improves Toolbar UG on image editor.

---

MAUI/CheckBox/Event.md
MAUI/CheckBox/Getting-Started.md
MAUI/CheckBox/Overview.md
MAUI/CheckBox/Visual-Customization.md
MAUI/CheckBox/VisualStates.md
MAUI/Radio-Button/Event.md
MAUI/Radio-Button/Getting-Started.md
MAUI/Radio-Button/Grouping.md
MAUI/Radio-Button/Overview.md
MAUI/Radio-Button/Visual-Customization.md
MAUI/Radio-Button/VisualStates.md

- Adjusted the User Guide content for Radio Button and CheckBox controls based on the changes provided by the content reviewer.

Maui - User Guide Refinements for Radio Button and CheckBox Controls: Incorporating Content Reviewer Changes.

---

MAUI/Segmented-Control/customization.md
MAUI/Segmented-Control/disabled-segment.md
MAUI/Segmented-Control/display-mode.md
MAUI/Segmented-Control/getting-started.md
MAUI/Segmented-Control/layout.md
MAUI/Segmented-Control/migration.md
MAUI/Segmented-Control/overview.md
MAUI/Segmented-Control/right-to-left.md
MAUI/Segmented-Control/selection.md
maui-toc.html

##Description
Added Maui Segmented control UG content

841443 - Added Maui Segmented control UG content

---

MAUI/DataForm/DataForm-settings.md
MAUI/DataForm/Editors.md
MAUI/DataForm/getting-started.md
MAUI/DataForm/layout.md
MAUI/DataForm/migration.md
MAUI/Scheduler/appointments.md
MAUI/Scheduler/getting-started.md
MAUI/Scheduler/migration.md

Maui scheduler data form content changes added

843228 - Maui Scheduler and DataForm content changes added

---

MAUI/Button/Migration.md

In this PR I have addressed changes Button migration page.

Addressed Changes in Button Migration Page

---

MAUI/Scheduler/appointments.md
MAUI/Scheduler/getting-started.md
MAUI/Segmented-Control/customization.md
MAUI/Segmented-Control/disabled-segment.md
MAUI/Segmented-Control/display-mode.md
MAUI/Segmented-Control/migration.md
MAUI/Segmented-Control/selection.md

Added Changes for Maui Scheduler and Segmented Controls

841443 - Added Changes for Maui Scheduler and Segmented Controls

---

MAUI/Popup/popup-animations.md
MAUI/TreeView/appearance.md
MAUI/TreeView/data-population.md
MAUI/TreeView/getting-started.md

Fixed the automation break issue

---

MAUI/Button/Migration.md

In this PR I have addressed the issue of Page not opening.

 Resolving the issue of the page not opening.

---

MAUI/CheckBox/Event.md
MAUI/CheckBox/Migration.md
MAUI/CheckBox/Visual-Customization.md
MAUI/Radio-Button/Migration.md

- Addressed the content-related issues in UG.

Maui -  Addressed the content-related issues in UG.

---

MAUI/Scheduler/appointments.md
MAUI/Segmented-Control/customization.md
MAUI/Segmented-Control/disabled-segment.md
MAUI/Segmented-Control/getting-started.md
MAUI/Segmented-Control/layout.md
MAUI/Segmented-Control/migration.md
MAUI/Segmented-Control/overview.md
MAUI/Segmented-Control/populating-segment-items.md
MAUI/Segmented-Control/selection.md
maui-toc.html

Added Maui Segmented Control Changes

841443 - Added Maui Segmented Control Changes

---

MAUI/Picker/migration.md
maui-toc.html

Migration document for the Picker from Xamarin to MAUI.

MAUI-843845-Migration from Xamarin to MAUI

---

MAUI/Button/Getting-Started.md
MAUI/Common/migration.md
MAUI/Introduction/MAUI-cross-platform-UI.md

Hi Team, 
Updated the common pages for Vol 3 2023 releases
Regards

Updated common pages for .NET MAUI Vol 3 2023 release

---

MAUI/Scheduler/appointments.md
MAUI/Segmented-Control/customization.md
MAUI/Segmented-Control/disabled-segment.md
MAUI/Segmented-Control/getting-started.md
MAUI/Segmented-Control/layout.md
MAUI/Segmented-Control/migration.md
MAUI/Segmented-Control/overview.md
MAUI/Segmented-Control/selection.md

Added changes for Maui Segmented Control

8421443 - Added changes for Maui Segmented Control

---

MAUI/Scheduler/appointments.md
MAUI/Segmented-Control/customization.md
MAUI/Segmented-Control/disabled-segment.md
MAUI/Segmented-Control/getting-started.md
MAUI/Segmented-Control/layout.md
MAUI/Segmented-Control/migration.md
MAUI/Segmented-Control/overview.md
MAUI/Segmented-Control/selection.md

Added changes for Maui Segmented control

841443- Added changes for Maui Segmented control

---

MAUI/Picker/data-template-selector.md
MAUI/Picker/migration.md

- Picker UG md file Issue resolved
- API Links Added.
- This MR derived from following MR: https://github.com/syncfusion-content/maui-docs/pull/1522

MAUI-843845-Picker API links added and UG Issue Fixed

---

MAUI/DatePicker/getting-started.md
MAUI/DateTimePicker/getting-started.md
MAUI/Picker/getting-started.md
MAUI/TimePicker/getting-started.md

Hi @Nijamudeen-Mohamed 
I have added notes for MAUI Picker , Datepicker, TimePicker and DateTimePicker UG ., Please review this changes and let me know any concerns.
Regards,
Muniappan S

841952-Notes added for picker control

---

MAUI/DatePicker/customizations.md

- Date picker front error issue fixed

MAUI-761078-Date picker UG issue fixed

---

MAUI/Common/migration.md
MAUI/Introduction/MAUI-cross-platform-UI.md

In this PR I have changed the Common  Migration page and Introduction UI Page.

Modified Common migration page and Introduction UI page.

---

maui-toc.html

Hi all,
- With this PR, we have added DocIO & Presentation controls in MAUI platform UG.
Regards,
Dharanitharan A

ES-846833-Add DocIO & Presentation controls in MAUI platform UG-hotfix

---

MAUI/Cartesian-Charts/Axis/Title.md
MAUI/Cartesian-Charts/Get-the-touch-position-in-chart.md
MAUI/Cartesian-Charts/Tooltip.md
MAUI/Cartesian-Charts/Transform-axis-value-to-pixel-value-and-vice-versa.md
MAUI/Cartesian-Charts/Zooming-and-panning.md

**Feature description**
Update the API reference for the APIs released in Volume 3 main release

MAUI-848170-Update User Guide APIs for Vol 3 API Reference Links_New

---

MAUI/Popup/popup-animations.md
MAUI/Popup/popup-positioning.md
MAUI/Popup/styles.md
MAUI/TreeView/Item-height-customization.md
MAUI/TreeView/appearance.md
MAUI/TreeView/data-population.md
MAUI/TreeView/expand-collapse.md
MAUI/TreeView/getting-started.md
MAUI/TreeView/migration.md
MAUI/TreeView/mvvm.md
MAUI/TreeView/overview.md
MAUI/TreeView/right-to-left.md
MAUI/TreeView/scrolling.md
MAUI/TreeView/selection.md
MAUI/TreeView/working-with-treeview.md

Added api links for maui treeView and popup

Added API links for Maui treeView and popup

---

MAUI/Button/Migration.md

In this PR I have added API Iinks in Button migration page.

Added API links in Button migration page

---

MAUI/CheckBox/Migration.md
MAUI/Radio-Button/Migration.md

- Revised API links within the migration file.

MAUI - Revised API links within the migration file

---

MAUI/Common/migration.md

In this PR I have changed the changed the Switch control release status.

Changing the Switch control release status

---

MAUI/Common/migration.md

In this PR I have changed the changed the Switch control release status.

Changing Switch release status

---

MAUI/Picker/data-template-selector.md
MAUI/Picker/dealing-with-column-header.md
MAUI/Picker/dealing-with-columns.md
MAUI/Picker/dealing-with-header-and-footer.md
MAUI/Picker/events.md
MAUI/Picker/migration.md
MAUI/Picker/populating-items.md

- Picker UG content improved. This MR derived from following MR: https://github.com/syncfusion-content/maui-docs/pull/1553

MAUI-843845-Picker UG content improved

---

MAUI/TreeView/migration.md

Fixed the issues in migration.

Fixed the issues in ug migration

---

MAUI/Picker/migration.md

Syntax error addressed for picker control.

MAUI-843845-Picker UG syntax error addressed

---

MAUI/DataGrid/selection.md

Added the API for CellRightTapped event.

Add API for CellRightTapped.

---

MAUI/Range-Selector/getting-started.md

Hi @Girija-Rajendran,
|--|--|
|Task Category| .NET MAUI Range Selector|
|UX task| NA|
|Interlinking PR link| Interlinking -https://github.com/syncfusion-content/maui-docs/pull/1459|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/175652/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Range-Selector---Money-Keywords.aspx|
|.net maui range selector|0-10 |1FT|To improve our FT experience |added CSS classes, alignment format, renamed and aligned images in zigzag form, added documentation, and code example |
|.net maui …

SEO-175652 .NET MAUI Range Selector Interlinking

---

MAUI/Barcode-Generator/getting-started.md
MAUI/Barcode-Generator/one-dimensional-symbology.md
MAUI/Barcode-Generator/overview.md
MAUI/Barcode-Generator/two-dimensional-symbology.md

Hi @Girija-Rajendran ,
|--|--|
|Task Category| .NET MAUI Barcode Generator|
|UX task| NA|
|Interlink PR link| Interlink -https://github.com/syncfusion-content/maui-docs/pull/1486
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/175690
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Barcode-Generator---Money-Keywords.aspx
|.net maui barcode generator|0-10 |1FT|improved on page changes |added CSS classes alignment format, images aligned in zigzag form, added documentation & Example links|
|net maui qr code …

SEO-175690 .NET MAUI Barcode Generator Interlink

---

MAUI/Chips/Getting-Started.md

Getting started sample link added in ug.

Getting started sample link added in chip

---

MAUI/Chips/Getting-Started.md

Getting started sample link added in ug.

Chip sample link added in ug

---

MAUI/Slider/getting-started.md

Hi @Girija-Rajendran 
|--|--|
|Task Category| .NET MAUI Slider|
|UX task| NA|
|Interlinking PR link| Interlinking -https://github.com/syncfusion-content/maui-docs/pull/1468|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/175684|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Slider---Finalized-Money-Keywords-Status(1).aspx|
|.net maui slider|10-100 |Omit -10FT|To improve our FT experience |added CSS classes alignment format, images aligned in zigzag form, added documentation & Example links, unwanted space removed. …

SEO-175684 - .NET MAUI Slider int

---

MAUI/Range-Slider/getting-started.md

Hi @Girija-Rajendran 
|--|--|
|Task Category| .NET MAUI Range Slider|
|UX task| NA|
|Interlinking PR link| Int -https://github.com/syncfusion-content/maui-docs/pull/1579|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/176122/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Range-Slider---Finalized-Money-Keywords-Status.aspx|
|.net maui range slider|0-10 |Omit -10FT|To improve our FT experience |added CSS classes alignment format, images aligned in zigzag form, added documentation & Example links, unwanted space …

SEO-176122 - .NET MAUI Range Slider

---

MAUI/Picker/migration.md

- Picker UG Syntax Issue Resolved

MAUI-843845-Picker UG Syntax Issue Resolved

---

MAUI/CheckBox/Migration.md
MAUI/Radio-Button/Migration.md

- In the migration file, extraneous spaces have been removed, and a link has been added for reference.

MAUI - Addressed changes in Migration file.

---

MAUI/Common/migration.md

Hi Team, 
Updated Timeline for .NET MAUI Controls in Common Migration page.
Regards

Updated Timeline for .NET MAUI Controls in Common Migration page - hotfix

---

MAUI/Common/migration.md

Hi Team, 
Updated Timeline for .NET MAUI Controls in Common Migration page.
Regards

Updated Timeline for .NET MAUI Controls in Common Migration Page - dev

---

MAUI/Segmented-Control/migration.md

Added Maui Segmented Control upcoming feature changes

841443 - Added Maui Segmented Control upcoming feature changes

---

MAUI/System-Requirements.md

Hi Team, 
Added .NET 8.0 support details in the .NET MAUI Requirement page in UG documentation. Kindly review and merge the same.
Regards

Added .NET 8.0 support details in .NET MAUI Requirement Page UG - development

---

MAUI/System-Requirements.md

Hi Team, 
Added .NET 8.0 support details in the .NET MAUI Requirement page in UG documentation. Kindly review and merge the same.
Regards

Added .NET 8.0 support details in .NET MAUI Requirement Page UG - hotfix

---

MAUI/DatePicker/getting-started.md
MAUI/DateTimePicker/getting-started.md
MAUI/Picker/getting-started.md
MAUI/TimePicker/getting-started.md

- In all the picker controls, I have removed the Pop nuget added content.

MAUI-5440-Hotfix-Picker controls UG updated

---

MAUI/Common/migration.md

Hi Team, 
Changed release timeline for MAUI SfParallaxView control, kindly review and merge the same
Regards
Anandhan  Rajagopal

Changed release timeline for MAUI SfParallaxView control - development

---

MAUI/Common/migration.md

Hi Team,
Changed release timeline for MAUI SfParallaxView control, kindly review and merge the same
Regards

Changed release timeline for MAUI SfParallaxView control - hotfix

---

maui-toc.html

Hi All,
Modify the TOC file for DocIo and Presentation Product.
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh

ES-851567 Modify TOC File

---

MAUI/DateTimePicker/customizations.md
MAUI/TimePicker/customizations.md

- Updated the picker controls content

MAUI-5440-Picker control images updated

---

MAUI/Accordion/getting-started.md

Added Getting Started Video link for Accordion Control

Added Getting Started Video link for Accordion Control

---

maui-toc.html

Hi All,
Modify the TOC file for DocIo and Presentation Product.
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh

ES-851567 Modify TOC File 

---

MAUI/Scheduler/getting-started.md

Hi @Jeyasri-Murugan ,
I have updated the UG documentation. Kindly review it.
Regards,
Rishvanth C K

845742-UG content correction.

---

MAUI/PDF-Viewer/Migration.md

Removed the invalid feature from the upcoming features list in Maui PDF viewer

Remove unwanted item from the upcoming features list in Maui PDF viewer

---

maui-toc.html

I have added XlsIO control UG redirect links.

854120-XlsIOChanges

---

MAUI/ImageEditor/crop.md
MAUI/ImageEditor/events.md
MAUI/ImageEditor/getting-started.md
MAUI/ImageEditor/imagefilter.md
MAUI/ImageEditor/localization.md
MAUI/ImageEditor/migration.md
MAUI/ImageEditor/overview.md
MAUI/ImageEditor/reset.md
MAUI/ImageEditor/save.md
MAUI/ImageEditor/shape.md
MAUI/ImageEditor/text.md
MAUI/ImageEditor/toolbar-customization.md
MAUI/ImageEditor/transformation.md
MAUI/ImageEditor/undo-redo.md
MAUI/ImageEditor/zooming.md

Hi Team, 
I have resolved the image editor UG page loading issue.

MAUI 854666 - Image editor UG page loading issue resolved

---

MAUI/Accordion/appearance.md
MAUI/Expander/appearance.md

Included VisualState feature details of Expander and Accordion control.

835112- Updated Expander and Accordion UG.

---

MAUI/visual-studio-integration/template-studio.md

I have modified the UG content

EXT-1775- I have modified the UG

---

MAUI/Button/Migration.md
MAUI/TextInputLayout/Migration.md

Hi Team, 
Added known issues details in .NET MAUI SfTextInputLayout control, kindly review and merge the same.
Reference: 
SfButton - https://github.com/dotnet/maui/issues/18671
SfTextInputLayout - https://github.com/dotnet/maui/issues/18103
Thanks and regards

857438 Added known issues details in .NET MAUI SfTextInputLayout control

---

MAUI/Button/Migration.md
MAUI/TextInputLayout/Migration.md

Hi Team,
Added known issues details in .NET MAUI SfTextInputLayout control, kindly review and merge the same.
hotfix PR: https://github.com/syncfusion-content/maui-docs/pull/1689
Thanks and regards

857438 Added known issues details in .NET MAUI SfTextInputLayout control - development

---

MAUI/Accordion/appearance.md
MAUI/Expander/appearance.md
MAUI/Pull-to-Refresh/migration.md
maui-toc.html

Added Migration UG for PullToRefresh control and content change for Expander and Accordion.

Added Migration UG for PullToRefresh control and content change for Expander and Accordion.

---

MAUI/Segmented-Control/customization.md
MAUI/Segmented-Control/disabled-segment.md
MAUI/Segmented-Control/getting-started.md
MAUI/Segmented-Control/layout.md
MAUI/Segmented-Control/migration.md
MAUI/Segmented-Control/overview.md
MAUI/Segmented-Control/populating-segment-items.md
MAUI/Segmented-Control/right-to-left.md
MAUI/Segmented-Control/selection.md

Maui Segmented Control front matter portion platform name changed

860165 - Maui Segmented Control front matter portion platform name changed

---

MAUI/Button/Getting-Started.md
MAUI/CheckBox/Getting-Started.md
MAUI/Radio-Button/Getting-Started.md

In this PR I have added YouTube video links in Button, RadioButton, and CheckBox control's UG content.

860576 - Adding YouTube Video link in Button, CheckBox and RadioButton control's UG content

---

MAUI/DataForm/DataForm-settings.md

Hi @Aishwarya-Ganesan 
Fixed page not found issue links in our UG page. Please check and merge the same.
Thanks,
Mallika

SEO-178147: Fixed Page Not found issue links

---

MAUI/Cartesian-Charts/Trackball.md

Added UG for trackball created event.

848789 Prepare UG document for trackball label created event support

---

MAUI/Cards/migration.md

Migration alignment change for cards.

MAUI-859689-Migration Alignment Changes For Cards

---

MAUI/Cartesian-Charts/Add-custom-labels.md
MAUI/Cartesian-Charts/Customize-each-chart-axis-label.md
maui-toc.html

Updated content review changes for Add-custom-labels.md and Customize-each-chart-axis-label.md in MAUI/Cartesian-Charts

857119 _Updated content review changes for  visible label support UG in .net MAUI Cartesian chart

---

MAUI/ImageEditor/getting-started.md
MAUI/ImageEditor/migration.md
MAUI/ImageEditor/text.md

Updated UG content for image editor control.
**Topics**.
Getting started
Known issue
Double tap to activate editing.

MAUI-860107: Updated UG content for Maui ImageEditor

---

MAUI/ImageEditor/accessibility.md
MAUI/ImageEditor/text.md

Updated UG staging correction for Maui ImageEditor control.
Content review task : https://dev.azure.com/Syncfusion-General/Documentation/_workitems/edit/763371

MAUI-860107: Updated UG staging correction for Maui ImageEditor

---

MAUI/NavigationDrawer/Duration.md
MAUI/NavigationDrawer/Events.md
MAUI/NavigationDrawer/Getting-Started.md
MAUI/NavigationDrawer/Main-Content.md
MAUI/NavigationDrawer/Migration.md
MAUI/NavigationDrawer/Navigation-Pane-Sides.md
MAUI/NavigationDrawer/Overview.md
MAUI/NavigationDrawer/Side-Pane-Content.md
MAUI/NavigationDrawer/Side-Pane-Sizing.md
MAUI/NavigationDrawer/Swipe-Gesture.md
MAUI/NavigationDrawer/Toggle-Animations.md
maui-toc.html

Prepare UG documentation for the .NET MAUI Navigation drawer.

859492 - Prepare UG documentation for the .NET MAUI Navigation drawer.

---

MAUI/PDF-Viewer/Shapes.md

Header added to enable or disable drawing mode for shapes

PDF Viewer MAUI UG changes

---

MAUI/Cartesian-Charts/Customize-each-chart-axis-label.md

Updated {% endtabs %} in Customize-each-chart-axis-label.md file.

857119_Updated tag in document for visible label support in .NET MAUI Cartesian chart

---

MAUI/Masked-Entry/Migration.md
MAUI/Switch/Migration.md

Hi Team,
In this PR, I have updated UG document content for SfSwitch and SfMaskedEntry control. Please review and merge the same.
Regards,

MAUI-860218-Updated UG Documentation for New .NET MAUI SfSwitch and SfMaskedEntry Control

---

MAUI/Autocomplete/Selection.md
MAUI/Autocomplete/UI-Customization.md
MAUI/ComboBox/UI-Customization.md

UG content changed for dropdown opened event in SfAutocomplete

UG content changed for dropdownopened event in SfAutocomplete

---

MAUI/Cartesian-Charts/Add-custom-labels.md
MAUI/Cartesian-Charts/Customize-each-chart-axis-label.md
MAUI/SunburstChart/CenterView.md
MAUI/SunburstChart/DataLabels.md
MAUI/SunburstChart/Getting-Started.md
MAUI/SunburstChart/Migration.md
MAUI/SunburstChart/Sunburst-Chart.md
MAUI/SunburstChart/Tooltip.md

- Updated the UG document code snippet.

861775- Update MAU charts UG document Review changes for cartesian chart and sunburst chart.

---

MAUI/Pull-to-Refresh/customization.md

Resolved automation staging error

Resolved automation staging error in Pull-to-Refresh/customization.md

---

MAUI/Cards/Customization.md
MAUI/Cards/Events.md
MAUI/Cards/getting-started.md
MAUI/Cards/migration.md

Add upcoming feature for cards control.

MAUI-859689-Add Upcoming Feature For Cards

---

MAUI/Carousel-View/Transformation.md
MAUI/Switch/Events.md
MAUI/Switch/Getting-Started.md
MAUI/Switch/Migration.md
MAUI/Switch/customization.md
MAUI/Switch/states.md

Hi Team,
In this PR, I have updated UG document content for SfSwitch and SfCarousel controls. Please review and merge the same.
Regards,

MAUI-860218-Updated UG Documentation for New .NET MAUI SfSwitch and SfCarousel Controls

---

MAUI/Carousel-View/Animation.md
MAUI/Carousel-View/Linear-Arrangement.md
MAUI/Carousel-View/LoadMore.md
MAUI/Carousel-View/Migration.md
MAUI/Carousel-View/Populating-Data.md
MAUI/Carousel-View/SwipeEvents.md
MAUI/Carousel-View/Transformation.md
MAUI/Carousel-View/UIVirtualization.md
MAUI/Carousel-View/getting-started.md
MAUI/Carousel-View/how-to.md

In this PR I have added Links to the SfCarousel UG content page.

862798 - Updated API Links in SfCarousel UG documentation

---

MAUI/DataForm/accessibility.md
MAUI/Scheduler/accessibility.md
MAUI/Scheduler/agenda-view.md
MAUI/Segmented-Control/accessibility.md
MAUI/Segmented-Control/selection.md
maui-toc.html

I have added an accessibility topic for Dataform and Segmented controls and added an accessibility description in Scheduler control.

MAUI 862727 - Added accessibility for Dataform and Segmented control

---

MAUI/Cartesian-Charts/Add-custom-labels.md
MAUI/Cartesian-Charts/Trackball.md
MAUI/SunburstChart/CenterView.md
MAUI/SunburstChart/DataLabels.md
MAUI/SunburstChart/Getting-Started.md
MAUI/SunburstChart/Migration.md
MAUI/SunburstChart/Sunburst-Chart.md
MAUI/SunburstChart/Tooltip.md

Updated the API reference links for the following:
Features:
- Visible Label Support
- Trackball created event
Control:
- Sunburst Chart

862700 -[Hotfix] Updated the API reference Links in MAUI for Volume 4 Released control and features
