MAUI/Avatar-view/customization.md, MAUI/Chips/Customization.md, MAUI/NumericEntry/Getting-Started.md, MAUI/NumericEntry/UpDown-Button.md
Add the API links to the New Features
=> 862772 - Add the API links to the New Features

MAUI/Avatar-view/customization.md, MAUI/Chips/Customization.md, MAUI/NumericEntry/Getting-Started.md, MAUI/NumericEntry/UpDown-Button.md
Add the API links to the New Features
=> 862772 - Add the API links to the New Features.

MAUI/Cards/Customization.md, MAUI/Cards/Events.md, MAUI/Cards/getting-started.md, MAUI/Cards/migration.md
UG content added for card control.
=> MAUI-857049-CardAPILink-API links updated.

MAUI/Autocomplete/Selection.md, MAUI/ComboBox/Selection.md, MAUI/NumericEntry/UpDown-Button.md
Add the API links for Autocomplete, ComboBox, and NumericEntry.
=> 862772 - Add the API links for Autocomplete, ComboBox, and NumericEntry. [development]

MAUI/Autocomplete/Selection.md, MAUI/ComboBox/Selection.md, MAUI/NumericEntry/UpDown-Button.md
Add the API links for Autocomplete, ComboBox, and NumericEntry.
=> 862772 - Add the API links for Autocomplete, ComboBox, and NumericEntry. [hotfix]

MAUI/Pull-to-Refresh/customization.md, MAUI/Pull-to-Refresh/getting-started.md, MAUI/Pull-to-Refresh/migration.md, MAUI/Pull-to-Refresh/mvvm.md, MAUI/Pull-to-Refresh/overview.md, MAUI/Pull-to-Refresh/pulltorefresh-events.md
Added CR links in APIs for MAUI SfPulltoRefresh
=> Added CR links in APIs for MAUI SfPulltoRefresh

MAUI/PDF-Viewer/Annotations-Overview.md
Newly supported types of annotation is updated in the annotation overview document
=> Update the newly supported types of annotation in MAUI PDF Viewer documentation

MAUI/Autocomplete/Migration.md, MAUI/ComboBox/Migration.md, MAUI/NumericEntry/Migration.md
Remove the provided support titles from the UG documentation.
=> 864206-Remove the provided support titles from the UG documentation. [hotfix]

MAUI/PDF-Viewer/Form-Filling.md, MAUI/PDF-Viewer/Import-Export-Annotations.md, MAUI/PDF-Viewer/Overview.md, MAUI/PDF-Viewer/Page-Navigation.md
Updated the PDF Viewer existing UG documentation with the following changes.
1. Updated the outdated overview PDF contents with the new features.
2. Updated note for not advising to use PDF Viewer inside a scroll viewer.
=> 865918: Update the OverView page, 865917: Update note for avoid using PDF viewer inside a ScrollView

MAUI/ImageEditor/migration.md
I have added a known issue in the image editor UG document.
=> MAUI 864455 - Added known issue in image editor

MAUI/CheckBox/Visual-States.md, MAUI/NumericEntry/UpDown-Button.md, MAUI/Radio-Button/Getting-Started.md, MAUI/Segmented-Control/accessibility.md
Hi @MallikaRK,
I have worked on missing H1, please review
=> SEO-178959-Missing H1

MAUI/PDF-Viewer/Page-Navigation.md, MAUI/PDF-Viewer/Scrolling.md, maui-toc.html
Added UG for detecting the end of the document by introducing a new page named **Scrolling**
Content review (completed): https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/868419
=> 868410: Publish UG for detecting the end of the document

MAUI/ListView/selection.md
=> 866853 :Need to update the Selection UG for SfListView

MAUI/Badge-View/Getting-Started.md, MAUI/Badge-View/Migration.md, MAUI/Badge-View/Predefined-symbols.md
|--|--|
|Task Category| .NET MAUI Badge View
|Content Task Link/Mail Screenshot | https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/764224/ |
|UX task|NA|
|Interlinking | PR -  https://github.com/syncfusion-content/maui-docs/pull/1844|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/175691/|
|Excel/SharePoint link | https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI---Money-Keywords.aspx|
|.net maui badge view|0-10 |5FT|To move FT to the first position |Changed the content alignment, improved some content|
|.net maui badge view example|0-10 |2UG |To improve the FT …
=> SEO-174657-NET-MAUI-Badge-View

MAUI/ComboBox/Getting-Started.md, MAUI/ComboBox/Selection.md
Hi @Girija-Rajendran 
|--|--|
|Task Category| .NET MAUI ComboBox|
|UX task| NA|
|master PR link| master -https://github.com/syncfusion-content/featuretour-maui/pull/724|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/179543/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-ComboBox---Money-Keywords(1).aspx|
|.net maui combobox|10-100 |1FT|To improve our FT experience |added CSS classes, alignment format, images aligned in zigzag form, added documentation & example links, unwanted space removed. |
|.net maui combobox …
=> SEO-179493 .NET MAUI ComboBox Interlinking

MAUI/Accordion/getting-started.md, MAUI/Accordion/overview.md
|--|--|
|Task Category| .NET MAUI Accordion|
|Content Task Link/Mail Screenshot|  |
|UX task| NA|
|Interlinking PR link| Interlinking - https://github.com/syncfusion-content/maui-docs/pull/1853 |
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/179549/ |
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Accordion--Money-keywords.aspx |
|.net maui accordion|0-10 |6UG|To improve our FT experience |added CSS classes, alignment format, renamed and aligned images in zigzag form, added documentation, and code example |
|.net maui accordion example|0-10 |5GitHub|To …
=> SEO-178424-Maui-Accordion-Interlinking

MAUI/Shimmer/getting-started.md
|--|--|
|Task Category| .NET MAUI Shimmer|
|Content Task Link/Mail Screenshot||
|UX task| NA|
|Interlinking PR link| Int - https://github.com/syncfusion-content/maui-docs/pull/1838|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/179381/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Shimmer---Money-Keywords.aspx|
Worked on 17 keywords in the .NET MAUI Shimmer and am keeping track of all keyword details in the link below:-
[https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/Keyword-Plan---.NET-MAUI-Shimmer.aspx]
=> SEO-179389-NET-MAUI-Shimmer-Int

MAUI/TreeView/expand-collapse.md
Prepared UG documentation for IsExpanded bindable property in .NET MAUI TreeView.
=> 864515- UG documentation for IsExpanded bindable property

MAUI/DataGrid/export-to-excel.md, MAUI/DataGrid/export-to-pdf.md
###Description##
*1.Added SaveService class in excel and PDF.*
=> changed the excel and PDF file

MAUI/Scheduler/appointments.md
Hi @saiganesh-sakthivel ,
I have updated the content for the appointment appearance customization in the user guide. Kindly review it and inform me if any changes required.
UG link - https://help.syncfusion.com/maui/scheduler/appointments?cs-save-lang=1&cs-lang=xaml#customize-appointment-appearance-using-datatemplate
Regards,
Rishvanth Kumaresan
=> 869514- Update the appointment appearance customization content.

MAUI/Radio-Button/Getting-Started.md
I corrected the mistake in the SfRadioButton UG.
=> Updated the SfRadioButton UG-Hotfix

MAUI/DataGrid/export-to-excel.md
Resolved Exporting to Excel and PDF errors
=> MAUI - 871873 - Resolved Exporting to Excel and PDF errors

maui-toc.html
Updated .toc file for PullToRefresh UG topic of ListView.
=> Updated .toc file for ListView UG

MAUI/Picker/migration.md
I have updated the upcoming features topics in UG.
Regards,
Indumathi R
=> MAUI-871351-UGPicker-Upcoming feature updated.

MAUI/StepProgressBar/getting-started.md, MAUI/StepProgressBar/migration.md, MAUI/StepProgressBar/overview.md, maui-toc.html
- Added UG content for the newly releasing SfStepProgressBar control in NET MAUI.
- Overview
- Getting started
- Migration
=> MAUI-871321-Dev-UG documentation added for .NET MAUI SfStepProgressBar control

MAUI/Chat/migration.md, maui-toc.html
Migration from Xamarin document for .NET MAUI Chat.
=> Migration from Xamarin document for .NET MAUI Chat

maui-toc.html
Update UG toc file for parallax view control
=> MAUI 869416 Update UG toc file for parallax view control

MAUI/PDF-Viewer/Add-Remove-Modify-Annotations.md, MAUI/PDF-Viewer/Form-Filling.md
**Description :**
UG documentation has been added for the CustomData property in form field and annotation support in the .NET MAUI PDF Viewer.
=> UG documentation added for the CustomData property in form field and annotation support in the .NET MAUI PDF Viewer.

MAUI/Themes/Keys.md
Added the theme key in UG document for below controls.
1. SfExpander
2. SfAccordion
=> 875797 - Added theme keys for SfAccordion and SfExpander

MAUI/Themes/Keys.md
I have added the theme key in UG document for below controls.
- Calendar
- Backdrop
- Barcode
- StepProgressbar
- Cards
- LinerarGauge
- Radialgauge
**Content team task: 
https://dev.azure.com/Syncfusion-General/Documentation/_workitems/edit/765176**
Regards,
Indumathi R
=> MAUI-871351-ThemeMAUI-Content team corrections added.

MAUI/Themes/Keys.md
Added theme key in UG document for SfPullToRefresh control
=> 875797 - Added Theme Keys for SfPullToRefresh control.

MAUI/DataForm/DataForm-settings.md, MAUI/DataForm/floating-label-layout.md
UG documentation for for DataForm new features.
- Added the changes in the floating-label-layout for supported editors and unsupported.
- Added the new feature label view customization in DataForm-settings
- Content Review PR - (https://github.com/syncfusion-content/maui-docs/pull/1975)
=> 871784- UG documentation for DataForm new features 

MAUI/Themes/Keys.md
I have updated the theme name.
Regards,
Indumathi R
=> MAUI-871351-ThemeUGCalendar-Changes updated.

MAUI/PDF-Viewer/Printing-a-Document.md
Update content review changes for print feature .NET MAUI PDF Viewer.
=> 875203-Update content review changes for print feature .NET MAUI PDF Viewer.

MAUI/DataForm/floating-label-layout.md
Hi @MallikaRK,
Worked on description too long.
Regards,
Sharly A.
=> SEO-180850-.NET-MAUI-Changes

MAUI/ImageEditor/serialization.md, maui-toc.html
UG documentation for Serialization in MAUI Image Editor
Content reviewed and closed as duplicate PR : https://github.com/syncfusion-content/maui-docs/pull/1965
Content review Task : https://dev.azure.com/Syncfusion-General/Documentation/_workitems/edit/765187
=> MAUI 874348 - UG documentation for Serialization in MAUI Image Editor

MAUI/Cartesian-Charts/migration.md, MAUI/Circular-Charts/migration.md, MAUI/Funnel-Charts/migration.md, MAUI/Pyramid-Charts/migration.md
Below mentioned controls migration UG was updated.
- SfCartesian Chart
- SfCircular Chart
- SfFunnel Chart
- SfPyramid Chart
=> MAUI-875929 Updated cartesian, circular, pyramid, funnel migration UG

MAUI/Rotator/Adding-Looping-and-Delays.md, MAUI/Rotator/Migration.md, MAUI/Rotator/Navigation-Modes.md
Hi Team,
I change the content in Migration page of SfRotator Control.
Regards,
Hariharan C
=> Maui 874730 - Changes in Migration Page of SfRotator Control

MAUI/StepProgressBar/accessibility.md, MAUI/StepProgressBar/customization.md, MAUI/StepProgressBar/events.md, maui-toc.html
I have updated the content tem review corrections. Following is the content team task link.
Task: https://dev.azure.com/Syncfusion-General/Documentation/_workitems/edit/765211
Regards,
Indumathi R
=> MAUI-871351-UGFinalDocStepProgressBar-Content team review corrections added.

MAUI/StepProgressBar/getting-started.md, MAUI/StepProgressBar/migration.md, MAUI/StepProgressBar/overview.md
- Added the content changes for the  .NET MAUI SfStepProgressBar control
=> MAUI-871321-Dev-UG content changes added for .NET MAUI SfStepProgressBar control

MAUI/StepProgressBar/accessibility.md, MAUI/StepProgressBar/customization.md, MAUI/StepProgressBar/events.md, maui-toc.html
Added content for the following topics
-  Accessibility
- Events
- Customization
=> MAUI-871321-UG documentation added for .NET MAUI SfStepProgressBar control

MAUI/Rotator/Getting-started.md, MAUI/TextInputLayout/Events.md
Hi  Team,
I  had Resolved the build error while  building Rotator and TextInputLayout
Regards,
Hariharan C
=> Maui 874730 - Resolved Build Error

MAUI/ListView/viewappearance.md, MAUI/Themes/Keys.md
Resolved alignment issues in Themes Key UG for SfListView
=> Resolved alignment issues in Themes Key UG for SfListView

MAUI/Themes/Keys.md
UG Documentation for DataGrid and DataPager themes.
=> MAUI-[Others]-UG Documentation for DataGrid and DataPager themes. 

MAUI/DataGrid/column-resizing.md, MAUI/DataGrid/migration.md
Addressed the review corrections in column resizing UG.
=> Addressed the review corrections in column resizing UG.

MAUI/Chat/data-binding.md, MAUI/Chat/getting-started.md, MAUI/Chat/messages.md, MAUI/Chat/migration.md
Prepared samples for - .NET MAUI Chat.
=> Prepare samples for - .NET MAUI Chat

MAUI/Themes/Keys.md
Added below listed controls theme key to .NET MAUI UG.
- SfCartesian Chart
- SfCircular Chart
- SfPyramid Chart
- SfFunnel Chart
- SfPolar Chart
=> MAUI-875270 Added theme key for all chart controls in .NET MAUI

MAUI/DataForm/floating-label-layout.md
UG documentation for DataForm conflicts
- Added the changes in the floating-label-layout.
- Content Review PR - (https://github.com/syncfusion-content/maui-docs/pull/1975)
=> 871784- Updated DataForm floating layout md file

MAUI/StepProgressBar/accessibility.md, MAUI/StepProgressBar/customization.md, MAUI/StepProgressBar/events.md
I have corrected the corrections in staging UG.
Regards,
Indumathi R
=> MAUI871351-UGCorrections-Updated the UG corrections.

MAUI/StepProgressBar/accessibility.md, MAUI/StepProgressBar/customization.md, MAUI/StepProgressBar/events.md
I have corrected the corrections in staging UG.
Regards,
Indumathi R
=> MAUI-871351-ImageCorrectionsMaster-Review corrections addressed.

MAUI/ImageEditor/serialization.md, MAUI/TreeMap/getting-started.md
Updated build error in image editor and tree map UG
=> MAUI 874348 - Updated build error in MAUI UG

MAUI/Radial-Menu/migration.md
- Updated the RadialMenu Migration document.
=> 874597 - Updated the RadialMenu Migration document.

MAUI/DataGrid/Unbound-Column.md, MAUI/DataGrid/selection.md
Added UG document for MAUI Data Grid Unbound column
=>  MAUI - 870300 - Prepare the UG documentation for the unbound column support

MAUI/StepProgressBar/description.md, MAUI/StepProgressBar/migration.md, MAUI/StepProgressBar/overview.md
- MAUI StepProgressBar UG content updated
=> MAUI-871321- MAUI StepProgressBar UG content updated

MAUI/StepProgressBar/description.md, MAUI/StepProgressBar/migration.md, MAUI/StepProgressBar/overview.md
- MAUI StepProgressBar UG content updated
=> MAUI-871321-Master- MAUI StepProgressBar UG content updated

MAUI/DataForm/floating-label-layout.md
UG documentation for DataForm conflicts
- Added the changes in the floating-label-layout.
- Content Review PR - (https://github.com/syncfusion-content/maui-docs/pull/1975)
=> 871784- Updated DataForm floating layout md file 

MAUI/PDF-Viewer/Migration.md, MAUI/PDF-Viewer/Overview.md
Updated the key features page of PDF Viewer
=> Key features update for PDF Viewer

MAUI/Themes/Keys.md
In this PR, I sorted the .NET Maui controls on the Keys page of the Theme UG content.
=> In Theme UG sorted controls keys list in Keys page.

MAUI/DataForm/DataForm-settings.md, MAUI/DataForm/getting-started.md, MAUI/ImageEditor/custom-view.md, MAUI/ImageEditor/customview.md, MAUI/ImageEditor/shape.md, MAUI/ImageEditor/text.md, MAUI/Scheduler/cell-selection.md, maui-toc.html
Updated UG correction in MAUI Image editor, DataForm and schedular controls
=> MAUI 874348 : Updated UG correction in MAUI Scheduler controls.

MAUI/TreeMap/getting-started.md, MAUI/TreeMap/migration.md, MAUI/TreeMap/overview.md
Fixed syntax issue for Maui TreeMap
=> 871811 - Maui TreeMap syntax issues fixed

MAUI/Themes/Themes.md
In this PR modified SyncfusionThemeDictionary to SyncfusionThemeResourceDictionary in the Themes page of Maui Theme UG.
=> Addresssed Changes in Maui Theme UG.

MAUI/Themes/Keys.md
Added below listed controls theme key to .NET MAUI UG.
- SfSlider
- SfRangeSelector
=> MAUI-875929-Added theme key for slider, range selector controls in .NET MAUI

MAUI/NavigationDrawer/Swipe-Gesture.md, MAUI/NavigationDrawer/Toggling-Drawer.md, MAUI/TabView/Tab-Item-Customization.md
Update UG documentation corrections for new features in the Maui Navigation drawer.
=> 874593 - Update UG documentation corrections for new features in the Maui Navigation drawer. [development]

MAUI/Themes/Keys.md
In this PR I have added RadialMenu and Rotator theme key list in Maui Theme UG Keys page.
=> Added RadialMenu and Rotator theme keys list in Maui Theme UG content.

MAUI/TreeMap/leaf-item-settings.md, MAUI/TreeMap/selection-and-highlights.md, maui-toc.html
Added leaf item content for tree map control.
=> 871811 - Added leaf item content for tree map control.

MAUI/TreeMap/brush-settings.md, MAUI/TreeMap/getting-started.md, MAUI/TreeMap/layouts.md, maui-toc.html
Added brush setting content for tree map control.
=> 871811 - Added brush setting content for tree map control.

MAUI/PDF-Viewer/Print-a-Document.md, maui-toc.html
Addressed the title content changes in print page.
=> Addressed the title content changes in print page.

MAUI/StepProgressBar/customization.md, MAUI/StepProgressBar/description.md, MAUI/StepProgressBar/events.md, MAUI/StepProgressBar/getting-started.md, MAUI/StepProgressBar/migration.md, MAUI/StepProgressBar/orientation.md, MAUI/StepProgressBar/overview.md
Added API link for stepprogressbar control.
Dev PR link: https://github.com/syncfusion-content/maui-docs/pull/2124
=> MAUI-871134-Add API Link For StepProgressBar

MAUI/DataForm/getting-started.md, MAUI/ImageEditor/custom-view.md, MAUI/ImageEditor/serialization.md, MAUI/ImageEditor/shape.md, MAUI/ImageEditor/text.md, MAUI/ImageEditor/z-ordering.md, MAUI/Scheduler/cell-selection.md, MAUI/Scheduler/month-view.md
Added API links to the below MAUI controls.
1. Image Editor.
2. Data Form
3. Schedular
=> 874842 - Added a API links to the MAUI controls.

MAUI/StepProgressBar/customization.md, MAUI/StepProgressBar/description.md, MAUI/StepProgressBar/events.md, MAUI/StepProgressBar/getting-started.md, MAUI/StepProgressBar/migration.md, MAUI/StepProgressBar/orientation.md, MAUI/StepProgressBar/overview.md
Added API link for stepprogressbar.
Dev PR link: https://github.com/syncfusion-content/maui-docs/pull/2124
Master PR link: https://github.com/syncfusion-content/maui-docs/pull/2133
=> MAUI-871134-Added API Link StepProgressBar

MAUI/Themes/Keys.md, MAUI/Themes/Themes.md
In this PR removed unused theme keys in the Theme UG keys page.
=> 877035 - Removed unused theme keys in Theme UG keys page.

MAUI/PDF-Viewer/Page-Navigation.md
Task : https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/875166/
Title : Documenting User Guide for PageLayout mode
Issue : XAML and C# code was not working
Fix: Added method to Switch PageLayoutMode
=> Documenting User Guide for PageLayout mode

MAUI/PDF-Viewer/Page-Navigation.md
Task : https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/875166/
Title : Documenting User Guide for PageLayout mode
Issue : XAML and C# code was not working
Fix: Added method to Switch PageLayoutMode
=> 875166 - Documenting User Guide for Page Layout mode

MAUI/PDF-Viewer/Page-Navigation.md
Reverts syncfusion-content/maui-docs#2148
**Note: Reverting the changes as it is already available in master branch**
=> Revert "Documenting User Guide for PageLayout mode"

MAUI/TreeMap/accessibility.md, MAUI/TreeMap/brush-settings.md, MAUI/TreeMap/events.md, MAUI/TreeMap/getting-started.md, MAUI/TreeMap/leaf-item-settings.md, MAUI/TreeMap/legend.md, MAUI/TreeMap/levels.md, MAUI/TreeMap/migration.md, MAUI/TreeMap/overview.md, MAUI/TreeMap/selection-and-highlights.md, MAUI/TreeMap/tooltip.md, maui-toc.html
Added API links for Maui TreeMap control
=> 871811- [master]Added API links for Maui TreeMap control

MAUI/TreeMap/accessibility.md, MAUI/TreeMap/brush-settings.md, MAUI/TreeMap/events.md, MAUI/TreeMap/getting-started.md, MAUI/TreeMap/leaf-item-settings.md, MAUI/TreeMap/legend.md, MAUI/TreeMap/levels.md, MAUI/TreeMap/migration.md, MAUI/TreeMap/overview.md, MAUI/TreeMap/selection-and-highlights.md, MAUI/TreeMap/tooltip.md, maui-toc.html
Maui Treemap control changes Moved from master to development
=> 877636 - Maui Treemap control changes updated from master

MAUI/StepProgressBar/overview.md
Add changes for step progress bar
Dev PR link: https://github.com/syncfusion-content/maui-docs/pull/2163
=> MAUI-871134-Hotfix_AddChanges_StepProgressBar

MAUI/StepProgressBar/overview.md
Add changes for step progress bar.
=> MAUI-871134-Add Changes For Step Progress Bar

MAUI/Themes/Keys.md
=> MAUI-[Others]-Themes_UG_Changes.

MAUI/Themes/HowTo.md, MAUI/Themes/Keys.md, MAUI/Themes/Themes.md
Added UG documents for below features in mentioned controls.
- Changed the theme key from SfAutoCompleteTheme to SfAutocompleteTheme.
- Changed the API name for theme from SfVisualTheme to VisualTheme.
=> 877116: Modified the theme element names

MAUI/Effects-View/Getting-Started.md
|--|--|
|Task Category| .NET MAUI Effects View|
|Content Task Link/Mail Screenshot|https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/764384|
|UX task| NA|
|PR link| https://github.com/syncfusion-content/maui-docs/pull/1867|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/176383|
|Excel/SharePoint link|https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Effects-View---Money-Keywords.aspx|
|.net maui effects view|0-10 |3FT|To improve our FT experience |added CSS classes alignment format, images aligned in zigzag form, added documentation & Example links, unwanted space …
=> SEO-176383-.NET-MAUI-Effects-View-Interlinking

maui-toc.html
In this PR I modified the mistake in Rotator name in maui-toc-html file.
=> Addressed the Change in UG Content

maui-toc.html
In this PR I modified the mistake in Rotator name in maui-toc-html file.
=> Development - Addressed the Change in UG Content.

MAUI/Themes/HowTo.md, MAUI/Themes/Keys.md
In this PR I modified the property name SfVisualTheme to VisualTheme in Theme UG page.
=> Addressed changes in Theme UG content.

MAUI/TabView/Tab-Item-Customization.md
Update the code snippet for the TabHeaderPadding property in SfTabView.
=> 879456 - Update the code snippet for the TabHeaderPadding property in SfTabView. [development]

MAUI/TabView/Tab-Item-Customization.md
Update the code snippet for the TabHeaderPadding property in SfTabView.
=> 879456 - Update the code snippet for the TabHeaderPadding property in SfTabView. [hotfix]

MAUI/Shimmer/getting-started.md
Updated the UG document of shimmer control.
Regards,
Indumathi R
=> MAUI-871351-ShimmerUG-Document updated.

MAUI/SignaturePad/getting-started.md
|--|--|
|Task Category| .NET MAUI SignaturePad|
|Content Task Link/Mail Screenshot|  |
|UX task| NA|
|Interlinking PR link| Interlinking -https://github.com/syncfusion-content/maui-docs/pull/2199 |
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/182222/ |
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Signature-Pad--Money-keywords.aspx |
=> SEO-178901-Maui-Signature-Pad-Interlinking

MAUI/DataGrid/Column-types.md
Added key values for Renderers.
=> MAUI - 883536 - Added key values for Renderers.

MAUI/Calendar/migration.md, MAUI/Cards/getting-started.md
Hi @MuniappanSubramanian,
UG migration topic updated. Kindly review and share your suggestions.
**Content review task: https://dev.azure.com/Syncfusion-General/Documentation/_workitems/edit/765833**
Regards,
Indumathi R
=> MAUI-867227-MigrationUG-Document updated.

MAUI/Calendar/migration.md
Hi @MuniappanSubramanian,
UG migration topic updated. Kindly review and share your suggestions.
Content review task: https://dev.azure.com/Syncfusion-General/Documentation/_workitems/edit/765833
Regards,
Indumathi R
=> MAUI-867227-HotFixCalendarUG-Changes committed.

MAUI/PDF-Viewer/Migration.md
Updated the popup and freetext annotation events in Migration page.
=> 884137 - Include Popup and FreeText Annotation Events in UG Documentation.

MAUI/Calendar/migration.md
Migration document updated. Kindly merge this.
Regards,
Indumathi R
=> MAUI-867277-HotfixCalendarUG-Migration document updated.

MAUI/Calendar/migration.md
Migration document updated. Kindly merge this.
Regards,
Indumathi R
=> MAUI-867227-DevMigrationUG-Document updated.

MAUI/CheckBox/Visual-Customization.md, MAUI/Radio-Button/Visual-Customization.md
Prepared UG for ControlSize feature in .NET MAUI SfRadioButton and SfCheckBox Controls.
=> MAUI - Added ControlSize Feature Content in .NET MAUI SfRadioButton and SfCheckBox Controls.

MAUI/DataGrid/Column-types.md, MAUI/DataGrid/grid-events.md, MAUI/DataGrid/migration.md, MAUI/DataGrid/selection.md
- Included the Migration guidelines for the Commands 
- Added the Commands and Command Parameter
- Provided the Delete Key support for deleting the row
- Included the disable support for the Keyboard Navigation.
=> Added the Helper Methods, Deleting and Keyboard Navigation

MAUI/DataGrid/Column-types.md, MAUI/DataGrid/grid-events.md, MAUI/DataGrid/migration.md, MAUI/DataGrid/selection.md
- Added the API link for Commands, delete key, keyboard navigation, allow null value.
- Added the API link in Migration guidelines.
=> Provided the API link for Commands

MAUI/DatePicker/getting-started.md
|--|--|
|Task Category|.NET MAUI Date Picker
|Content Task Link/Mail Screenshot|https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/765397|
|UX task|NA|
|Interlinking|PR - https://github.com/syncfusion-content/maui-docs/pull/2219|
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/178481|
|Excel/SharePoint link|https://syncfusion.sharepoint.com/:u:/r/sites/GH/SEO/SitePages/NET-MAUI-Date-Picker---Finalized-Money-Keywords-Status.aspx?csf=1&web=1&e=uUJaQy|
|.net maui date picker|0-10 |1FT|To move FT to the first position |Changed the content alignment, improved some content|
|.net maui date …
=> SEO-178481-.NET-MAUI-Date-Picker-Interlinking

MAUI/DataGrid/Column-types.md, MAUI/DataGrid/export-to-pdf.md, MAUI/DataGrid/grouping.md, MAUI/DataGrid/styling.md
- Added a note to Column Styling.
- Set the allow null value as subtopic for DataGrid Numeric column.
- Changed the Key in grouping.
=> Added note to Column styling

MAUI/TabView/Tab-Item-Customization.md
Description:
I have corrected the mistake in the tab view UG document.
=> Updated the SfTabView UG- Hotfix

MAUI/TabView/Tab-Item-Customization.md
Description:
I have corrected the mistake in the tab view UG document.
=> Updated the SfTabView UG-Dev

MAUI/Cards/getting-started.md
|--|--|
|Task Category| .NET MAUI Cards|
|Content Task Link/Mail Screenshot|  |
|UX task| NA|
|Interlinking PR link| Interlinking - https://github.com/syncfusion-content/maui-docs/pull/1871 |
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/179919/ |
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Cards---Money-keywords.aspx |
Worked on 16 keywords in the .NET MAUI Cards and am keeping track of all keyword details in the link below:-
[https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/Keyword-Plan---.NET-MAUI-Cards.aspx]
=> SEO-179919-Maui-Cards-Interlinking

MAUI/Picker/events.md, MAUI/Picker/getting-started.md
|--|--|
|Task Category| .NET MAUI Picker |
|Content Task Link/Mail Screenshot|  |
|UX task| NA|
|Interlinking PR link| Interlinking - https://github.com/syncfusion-content/maui-docs/pull/2224 |
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/179919/ |
|Excel/SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/Interlinking---.NET-MAUI-Picker-money-keywords.aspx |
Worked on 19 keywords in the .NET MAUI Picker and am keeping track of all keyword details in the link below:-
[https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Picker---Money-keywords.aspx]
=> SEO-182623-maui-picker-interlinking

MAUI/PDF-Viewer/Migration.md
**Description :** 
Included the custom stamp Methods to the Migration page in the UG documentation for SfPdfViewer.
Task : https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/886233
=> 886233 - Include custom stamp Methods to the Migration page in the UG documentation.

MAUI/TreeView/selection.md, MAUI/TreeView/working-with-treeview.md
Prepared UG for Key down feature in .NET MAUI SfTreeView
=> 882039: [Maui - SfTreeView] Prepare UG for Key down feature

MAUI/Calendar/getting-started.md
- Added Corner radius UG content for .NET MAUI Calendar control
=> MAUI-886798-Added Corner radius UG content for .NET MAUI Calendar control

MAUI/DatePicker/getting-started.md, MAUI/DateTimePicker/getting-started.md, MAUI/TimePicker/getting-started.md
- Added clear selection support for below controls
- SfDatePicker
- SfTimePicker
- SfDateTimePicker
=> MAUI-886798-Added clear selection support in .NET MAUI Picker controls

maui-toc.html
**Description :** 
Changed the TOC for print page.
=> 886233 - Changed the TOC for print page.

MAUI/Chat/suggestions.md
The Feature provides support to handle the automatic message sending action of suggestions.
=> 882220 - UG documentation for Cancel suggestion send message in .NET MAUI Chat

MAUI/DataForm/Editors.md
Changed the name and link for Check Box in dataform
Changed the name and link for Switch in dataform
Changed the name and link for RadioButton in dataform
=> UG Documentation for editors in DataForm 

MAUI/TreeView/scrolling.md
Added the UG for Horizontal Scrolling feature in .NET MAUI SfTreeView control.
=> [Maui - SfTreeview] UG for Horizontal scrolling support.

MAUI/Cartesian-Charts/Trackball.md, MAUI/Cartesian-Charts/Zooming-and-panning.md
- I have removed the indentation of Xaml and CS code in the trackball file.
- I have added a note for activation mode long press.
=> MAUI-886932 UG documentation for Activation mode, Maximum Zoom level in  Maui Cartesian Chart

MAUI/StepProgressBar/customization.md
Updated the highlight tag in the Step progress bar UG
=> Updated the highlights for the Step progress bar UG

MAUI/DataForm/grouping.md
UG documentation for the group header customization in dataform.
Added the group header customization in the UG
=> UG documentation for the group header customization in dataform

MAUI/DataGrid/selection.md
- Added the Selection Controller behavior
=> 888711-Prepare the UG documentation for the selection controller

MAUI/DataGrid/performance.md, maui-toc.html
Prepared the UG documentation for SfDataGrid scrolling performance.
=> 888728: Prepare the UG documentation for SfDataGrid scrolling performance.

MAUI/ImageEditor/custom-view.md, MAUI/ImageEditor/events.md, MAUI/ImageEditor/shape.md, MAUI/ImageEditor/text.md, MAUI/ImageEditor/toolbar-customization.md
UG documentation for the toolbar in ImageEditor
Added the tool bar text customization
=> UG documentation for the toolbar in ImageEditor

MAUI/Picker/dealing-with-columns.md, MAUI/StepProgressBar/right-to-left.md
=> MAUI-884326-UG Alignment Change For MAUI Controls

MAUI/Autocomplete/No-Results-Found.md, MAUI/ComboBox/No-Results-Found.md, MAUI/Masked-Entry/Show-Password-Character.md, MAUI/Masked-Entry/Validation.md
Hi Team,
I've resloved the conflicts in UG for NET MAUI. , Kindly review and merge the content.
Regards,
Hariharan C
=> Maui 889708 Resloved the conflicts in UG for NET MAUI. 

MAUI/ImageEditor/crop.md, MAUI/ImageEditor/getting-started.md, MAUI/ImageEditor/imagefilter.md, MAUI/ImageEditor/overview.md, MAUI/ImageEditor/shape.md, MAUI/Maps/custom-shape.md, MAUI/Maps/getting-started.md, MAUI/Maps/markers.md, MAUI/Maps/shape.md, MAUI/Scheduler/appointments.md, MAUI/Scheduler/day-week-views.md, MAUI/Scheduler/getting-started.md, MAUI/Scheduler/month-view.md, MAUI/Scheduler/overview.md, MAUI/Scheduler/timeline-views.md
Added  SEO keywords for MAUI controls below
**Controls**
1. ImageEditor
2. Scheduler
3. Maps
=> MAUI 884683 - Added keywords for MAUI controls

MAUI/Cartesian-Charts/Legend.md, MAUI/Circular-Charts/Legend.md, MAUI/Funnel-Charts/Legend.md, MAUI/Polar-Charts/Legend.md, MAUI/Pyramid-Charts/Legend.md, maui-toc.html
Description:
Added the legend UG section for maui charts
=> 886645- Added the legend UG section for MAUI Charts

MAUI/Autocomplete/No-Results-Found.md, MAUI/ComboBox/No-Results-Found.md
Hi Team,
I've addressed changes in  NoResultFound Content in UG for NET MAUI. , Kindly review and merge the content.
Regards,
Hariharan C
=> Maui 889708 Addressed changes in  NoResultFound Content in UG for NET MAUI.

MAUI/DatePicker/date-picker-text-display-mode.md, MAUI/DateTimePicker/date-time-picker-text-display-mode.md, MAUI/Picker/picker-text-display-mode.md
Picker, DatePicker and DateTimePicker content mistakes are updated.
=> MAUI 889852 - Picker Text Display Mode content mistakes updated

MAUI/DataGrid/conditional-styling.md
=> MAUI-888121 - Resolved the CI failures in the Conditional Styling UG document

MAUI/Cartesian-Charts/Legend.md, MAUI/Circular-Charts/Legend.md, MAUI/DataGrid/conditional-styling.md, MAUI/Funnel-Charts/Legend.md, MAUI/Polar-Charts/Legend.md, MAUI/Pyramid-Charts/Legend.md, maui-toc.html
Updated the tags for .NET MAUI Chart Legend UG
=> Task-886645 Updated the tags for .NET MAUI Chart Legend UG

MAUI/DataGrid/conditional-styling.md
Reverted the grid file Changes - https://github.com/syncfusion-content/maui-docs/pull/2361
=> Task-886645 Reverted the file Changes 

MAUI/StepProgressBar/customization.md, MAUI/StepProgressBar/tooltip.md
Updated API links for MAUI Step Progress Bar
=> Master-Updated API links for MAUI Step Progress Bar

MAUI/StepProgressBar/customization.md, MAUI/StepProgressBar/tooltip.md
Updated API Link for MAUI Step ProgressBar
=> Updated API Link for MAUI Step ProgressBar

MAUI/DigitalGauge/Customization.md, MAUI/DigitalGauge/overview.md
Updated the corrections for the digital gauge
=> 886555-UG documentation for the digital gauge control

MAUI/DigitalGauge/Customization.md, MAUI/DigitalGauge/overview.md
Updated the corrections for the digital gauge
=> 886555-Master-UG documentation for the digital gauge control 

MAUI/Picker/dealing-with-columns.md, MAUI/Picker/dealing-with-header-footer-and-selection-view.md, MAUI/Picker/migration.md
Added API link for picker control.
=> MAUI-884326-API Link Added For Picker UG

MAUI/Picker/dealing-with-columns.md, MAUI/Picker/dealing-with-header-footer-and-selection-view.md, MAUI/Picker/migration.md
=> MAUI-884326-API Link Added For Picker

MAUI/Calendar/calendar-mode.md, MAUI/Calendar/footer.md, MAUI/DatePicker/date-picker-text-display-mode.md, MAUI/DateTimePicker/date-time-picker-text-display-mode.md, MAUI/Picker/picker-text-display-mode.md, MAUI/TimePicker/time-picker-text-display-mode.md
API links for Volume 2 UG content are updated
=> MAUI 872476 - [Master]Updated API links for Volume 2 UG Content

MAUI/DigitalGauge/Character-Display-Types.md, MAUI/DigitalGauge/Customization.md, MAUI/DigitalGauge/Events.md, MAUI/DigitalGauge/Getting-Started.md, MAUI/DigitalGauge/migration.md, MAUI/DigitalGauge/overview.md
Added the api link for the digital gauge ug documentation.
=> 886555-Master-UG documentation for the digital gauge control API Link

MAUI/DigitalGauge/Character-Display-Types.md, MAUI/DigitalGauge/Customization.md, MAUI/DigitalGauge/Events.md, MAUI/DigitalGauge/Getting-Started.md, MAUI/DigitalGauge/migration.md, MAUI/DigitalGauge/overview.md
Added the api link for the digital gauge ug documentation
=> 886555-UG documentation for the digital gauge control API Link

MAUI/PDF-Viewer/Form-Filling.md, MAUI/PDF-Viewer/Signature.md, MAUI/PDF-Viewer/Stamps.md
MAUI-890348 Support to disable built-in dialogs and use custom dialogs
=> MAUI-890348 Support to disable built-in dialogs and use custom dialogs

MAUI/Calendar/getting-started.md
API added for calendar corner radius.
=> MAUI-884326-API Added For Calendar Corner Radius

maui-toc.html
Fixed the conflict in TOC file.
=> Fixed the conflict in TOC file.

MAUI/PDF-Viewer/Magnification.md, MAUI/PDF-Viewer/Migration.md, MAUI/PDF-Viewer/Sticky-Notes.md
Fixed the mistakes found on the staging link(Sticky note, Migration).
=> Fixed the mistakes found on the staging link(Sticky note, Migration and Magnification).

MAUI/DataForm/Editors.md, MAUI/DataForm/grouping.md, MAUI/DataForm/layout.md, MAUI/ImageEditor/custom-view.md, MAUI/ImageEditor/shape.md, MAUI/ImageEditor/text.md, MAUI/Scheduler/agenda-view.md, MAUI/Scheduler/month-view.md
Added the API Link for the dataform ug.
Added the API Link for the Scheduler ug.
Added the API Link for the ImageEditor ug.
=> UG documentation for the dataform API Link

MAUI/PDF-Viewer/Getting-Started.md, MAUI/PDF-Viewer/Magnification.md, MAUI/PDF-Viewer/Migration.md, MAUI/PDF-Viewer/Show-Hide.md, MAUI/PDF-Viewer/Sticky-Notes.md, MAUI/PDF-Viewer/Toolbar.md, MAUI/Themes/Keys.md
Fixed the conflict in Sticky notes, Migration, and Magnification
=> Fixed the conflict in Sticky note, Migration and Magnification

MAUI/PDF-Viewer/Getting-Started.md, MAUI/PDF-Viewer/Show-Hide.md, MAUI/PDF-Viewer/Toolbar.md, MAUI/Themes/Keys.md
i have modified the themes table
=> changing the corrections in the files

MAUI/DataForm/Editors.md, MAUI/DataForm/grouping.md, MAUI/DataForm/layout.md, MAUI/ImageEditor/custom-view.md, MAUI/ImageEditor/shape.md, MAUI/ImageEditor/text.md, MAUI/Scheduler/agenda-view.md, MAUI/Scheduler/month-view.md
Added the ug api link for hotfix
=> UG documentation for New features hotfix

MAUI/PDF-Viewer/Toolbar.md, maui-toc.html
=> Fixed the conflict in toolbar

MAUI/PDF-Viewer/Getting-Started.md, MAUI/PDF-Viewer/Magnification.md, MAUI/PDF-Viewer/Migration.md, MAUI/PDF-Viewer/Show-Hide.md, MAUI/PDF-Viewer/Sticky-Notes.md, MAUI/PDF-Viewer/Toolbar.md, MAUI/Themes/Keys.md, maui-toc.html
Missing changes in the hotfix branch(Sticky note, Migration, and Magnification).
=> Missing changes in the hotfix branch(Sticky note, Migration and Magnification). 

MAUI/Autocomplete/No-Results-Found.md, MAUI/ComboBox/No-Results-Found.md, MAUI/ComboBox/UI-Customization.md, MAUI/Masked-Entry/Basic-Features.md, MAUI/Masked-Entry/Show-Password-Character.md, MAUI/Masked-Entry/Validation.md
Hi Team,
I've added API reference for new feature API in .NET MAUI.
Regards,
Hariharan C
=> Maui 889708 Added API reference for new feature API in .NET MAUI.

MAUI/Autocomplete/No-Results-Found.md, MAUI/ComboBox/No-Results-Found.md, MAUI/ComboBox/UI-Customization.md, MAUI/Masked-Entry/Basic-Features.md, MAUI/Masked-Entry/Show-Password-Character.md, MAUI/Masked-Entry/Validation.md
Hi Team,
I've added API reference for new feature API in .NET MAUI.
Regards,
Hariharan C
=> Maui 889708 [Hotfix] Added API reference for new feature API in .NET MAUI.

MAUI/Autocomplete/Maximum-display-item-with-Expander.md, MAUI/Autocomplete/Searching-Filtering.md, MAUI/ComboBox/Maximum-display-item-with-Expander.md, MAUI/ComboBox/Searching.md
Hi team,
I have added API links for added MinimumPrefixCharacters and LoadMore features in SfAutocomplete and SfComboBox controls in .NET MAUI.
Regards,
Sivaranjith N.
=> 888835-Referenced API links for added features.

MAUI/Autocomplete/Maximum-display-item-with-Expander.md, MAUI/Autocomplete/Searching-Filtering.md, MAUI/ComboBox/Maximum-display-item-with-Expander.md, MAUI/ComboBox/Searching.md
Hi team,
I have added API links for added MinimumPrefixCharacters and LoadMore features in SfAutocomplete and SfComboBox controls in .NET MAUI.
Regards,
Sivaranjith N.
=> 888835-Referenced the API links for added features in UG

MAUI/ImageEditor/accessibility.md
Hi @Aishwarya-Ganesan ,
Have worked on Missing H1.
Regards,
Yvone.
=> SEO-183463 MAUI Missing H1

MAUI/Autocomplete/Migration.md, MAUI/ComboBox/Migration.md
Hi team,
I have updated the UG contents for migration page in .NET MAUI controls. Kindly review and merge the same.
Regards,
=> MAUI - 891167 - Modified Migration Page Content in .NET MAUI SfAutoComplete and SfComboBox Controls - Hotfix

MAUI/Autocomplete/Migration.md, MAUI/ComboBox/Migration.md
Hi team,
I have updated the UG contents for migration page in .NET MAUI controls. Kindly review and merge the same.
Regards,
=> MAUI - 891167 - Modified Migration Page Content in .NET MAUI SfAutoComplete and SfComboBox Controls - Development

MAUI/Button/Customization.md
** Description **
In this PR I have added API link for Button LineBreakMode support.
=> 890172 - Added LineBreakMode API link in SfButton UG content

MAUI/DataGrid/Column-types.md, MAUI/DataGrid/column-drag-and-drop.md, MAUI/DataGrid/editing.md, MAUI/DataGrid/migration.md, MAUI/DataGrid/performance.md, MAUI/DataGrid/selection.md
- The API link has been added for the DataGrid features provided in the 2024 volume 2 release.
=> 882121 - DataGrid UG document changes.

MAUI/Calendar/migration.md, MAUI/Cards/getting-started.md
- Migration tag corrections resolved
=> MAUI-886798-Updated MAUI Calendar Control Migration content

MAUI/TreeView/Item-height-customization.md, MAUI/TreeView/scrolling.md, MAUI/TreeView/working-with-treeview.md
Providing API Link for the following features in SfTreeView:
1.. NodeSizeMode 
2. KeyDown 
3. Horizontal Scrolling
=> [HotFix] Providing API Link for HorizontalScrolling, NodeSizeMode, KeyDown support in [MAUI - SfTreeView].

MAUI/Common/migration.md
=> Updated Maui migration.md

MAUI/Common/migration.md
updated MAUI/Common/migration.md
=> updated MAUI/Common/migration.md

MAUI/Polar-Charts/Getting-Started.md
Added the YouTube video in polar chart UG  - https://www.youtube.com/watch?v=Ga9mytwCo_s&t=4s
=> Task-889685 Added the YouTube video in polar chart UG

MAUI/Chat/getting-started.md, MAUI/Chat/suggestions.md, MAUI/Popup/popup-positioning.md, MAUI/Popup/styles.md
Adding link for FooterButtonCornerRadius , AutoCloseDuration and CancelSendMessage API.
=> Changes in FooterButtonCornerRadius , AutoCloseDuration and CancelSendMessage

MAUI/DataGrid/Column-types.md, MAUI/DataGrid/column-drag-and-drop.md, MAUI/DataGrid/editing.md, MAUI/DataGrid/migration.md, MAUI/DataGrid/performance.md, MAUI/DataGrid/selection.md
- The API link has been added for the DataGrid features provided in the 2024 volume 2 release.
=> MAUI - [DataGrid] DataGrid UG document changes.

MAUI/ComboBox/AutoSizing.md, MAUI/ComboBox/Editing.md, MAUI/ComboBox/Filtering.md, MAUI/ComboBox/Getting-Started.md, MAUI/ComboBox/Header-and-Footer.md, MAUI/ComboBox/Highlighting-matched-text.md, MAUI/ComboBox/Maximum-display-item-with-Expander.md, MAUI/ComboBox/Migration.md, MAUI/ComboBox/No-Results-Found.md, MAUI/ComboBox/Overview.md, MAUI/ComboBox/Searching.md, MAUI/ComboBox/Selection.md, MAUI/ComboBox/UI-Customization.md, MAUI/TextInputLayout/Assistive-Labels.md, MAUI/TextInputLayout/Container-Type.md, MAUI/TextInputLayout/Custom-Font.md, MAUI/TextInputLayout/Custom-Icons.md, MAUI/TextInputLayout/Events.md, MAUI/TextInputLayout/Fixed-Hint-Position.md, MAUI/TextInputLayout/Getting-Started.md, MAUI/TextInputLayout/How-To.md, MAUI/TextInputLayout/Migration.md, MAUI/TextInputLayout/Overview.md, MAUI/TextInputLayout/States-And-Colors.md, MAUI/TextInputLayout/Supported-input-views.md, MAUI/TextInputLayout/right-to-left.md
Hi Team,
I've added the keywords to .NET MAUI ComboBox and TextInputLayout control documents. Please review and merge this content.
Regards,
Prithis I.
=> [Hotfix] Added Keywords to .NET MAUI ComboBox and TextInputLayout controls.

MAUI/ComboBox/AutoSizing.md, MAUI/ComboBox/Editing.md, MAUI/ComboBox/Filtering.md, MAUI/ComboBox/Getting-Started.md, MAUI/ComboBox/Header-and-Footer.md, MAUI/ComboBox/Highlighting-matched-text.md, MAUI/ComboBox/Maximum-display-item-with-Expander.md, MAUI/ComboBox/Migration.md, MAUI/ComboBox/No-Results-Found.md, MAUI/ComboBox/Overview.md, MAUI/ComboBox/Searching.md, MAUI/ComboBox/Selection.md, MAUI/ComboBox/UI-Customization.md, MAUI/TextInputLayout/Assistive-Labels.md, MAUI/TextInputLayout/Container-Type.md, MAUI/TextInputLayout/Custom-Font.md, MAUI/TextInputLayout/Custom-Icons.md, MAUI/TextInputLayout/Events.md, MAUI/TextInputLayout/Fixed-Hint-Position.md, MAUI/TextInputLayout/Getting-Started.md, MAUI/TextInputLayout/How-To.md, MAUI/TextInputLayout/Migration.md, MAUI/TextInputLayout/Overview.md, MAUI/TextInputLayout/States-And-Colors.md, MAUI/TextInputLayout/Supported-input-views.md, MAUI/TextInputLayout/right-to-left.md
Hi Team,
I've added the keywords to .NET MAUI ComboBox and TextInputLayout control documents. Please review and merge this content.
Regards,
Prithis I.
=> Added Keywords to .NET MAUI ComboBox and TextInputLayout controls.

MAUI/Common/migration.md, MAUI/TabView/Migration.md, MAUI/TabView/Visual-State-Managers.md
Modified the TabView UG and added the C-sharp for VSM.
=> Modified the TabView UG- Master

MAUI/DataGrid/Column-sizing.md, MAUI/DataGrid/Column-types.md, MAUI/DataGrid/Getting-started.md, MAUI/DataGrid/Row-height-Customization.md, MAUI/DataGrid/Stacked-Header.md, MAUI/DataGrid/Unbound-Column.md, MAUI/DataGrid/column-drag-and-drop.md, MAUI/DataGrid/column-resizing.md, MAUI/DataGrid/columns.md, MAUI/DataGrid/conditional-styling.md, MAUI/DataGrid/data-binding.md, MAUI/DataGrid/editing.md, MAUI/DataGrid/export-to-excel.md, MAUI/DataGrid/export-to-pdf.md, MAUI/DataGrid/filtering.md, MAUI/DataGrid/freeze-panes.md, MAUI/DataGrid/grid-events.md, MAUI/DataGrid/grouping.md, MAUI/DataGrid/load-more.md, MAUI/DataGrid/migration.md, MAUI/DataGrid/overview.md, MAUI/DataGrid/paging.md, MAUI/DataGrid/performance.md, MAUI/DataGrid/pull-to-refresh.md, MAUI/DataGrid/scrolling.md, MAUI/DataGrid/selection.md, MAUI/DataGrid/sorting.md, MAUI/DataGrid/styling.md, MAUI/DataGrid/summaries.md, MAUI/DataGrid/unbound-row.md
=> MAUI DataGrid SEO keywords

MAUI/Themes/Themes.md
Added the API reference link for the Syncfusion Theme UG.
=> Added the API reference link for the Syncfusion Theme UG- Hotfix

MAUI/Themes/Themes.md
Added the API reference link for the Syncfusion Theme UG.
=> Added the API reference link for the Syncfusion Theme UG- Development

MAUI/TabView/Events.md, MAUI/TabView/Tab-Item-Customization.md
Update the UG document for TabView Maui control.
=> 889165 - Update the UG document for TabView Maui control.

MAUI/TabView/Events.md, MAUI/TabView/Tab-Item-Customization.md
Update the UG document for TabView Maui control.
=> 889165 - Update the UG document for TabView Maui control. 

MAUI/PDF-Viewer/Toolbar.md
PDF Viewer UG corrections are done in the toolbar section
=> PDF Viewer UG corrections

MAUI/ComboBox/Maximum-display-item-with-Expander.md
Hi team,
I have updated Development to Hotfix branch changes.
Regards,
=> MAUI - Development to Hotfix branch changes

MAUI/Chips/Customization.md
Hi Team,
I've Updated the SfChip Background Content in UG for NET MAUI. , Kindly review and merge the content.
Regards,
Hariharan C
=> 608651 - Update the API Reference in SfChip .NET MAUI control.

MAUI/Chips/Customization.md
Hi Team,
I've Updated the SfChip Background Content and API reference in UG for NET MAUI, Kindly review and merge the content.
Regards,
Hariharan C
=> 608651 - [Hotfix] Update the API Reference in SfChip .NET MAUI control.

MAUI/Autocomplete/Basic-Features.md, MAUI/Autocomplete/Getting-Started.md, maui-toc.html
Hi Team,
I have updated the Getting-Started page of .NET MAUI SfAutocomplete control .
Regards,
Sivaranjith N.
=> Updated the Getting-started page of SfAutocomplete control.

MAUI/Autocomplete/Basic Features.md, MAUI/Autocomplete/Basic-Features.md, MAUI/Autocomplete/Getting-Started.md, maui-toc.html
Hi Team,
I have updated the Getting-Started page of .NET MAUI SfAutocomplete control .
Regards,
Sivaranjith N.
=> 892777-.NET MAUI UG corrections

MAUI/PDF-Viewer/Toolbar.md
=> [PDF Viewer] Toolbar UG corrections/Improvements

MAUI/PDF-Viewer/Coordinates-Conversion.md, MAUI/PDF-Viewer/Open-a-Password-Protected-Document.md, MAUI/PDF-Viewer/Scrolling.md, MAUI/PDF-Viewer/Stamps.md
1. Updated password document file - Added contents to handle correct password
2. Updated scrolling document file - Mentioned the units.
3. Updated coordinate conversion file - Modified the header
=> [PDF Viewer] UG corrections and improvements

maui-toc.html
Added tags for accessibility and localization in toc file
=> Added tags for accessibility and localization in toc file

MAUI/Avatar-view/Content-type.md, MAUI/Avatar-view/customization.md, MAUI/Avatar-view/visualstyles.md, MAUI/CheckBox/Getting-Started.md
Updated Avatar-view/customization.md and CheckBox/Getting-Started.md
=> Updated AvatarView and CheckBox documentation- Hotfix

MAUI/Avatar-view/Content-type.md, MAUI/Avatar-view/Getting-Started.md, MAUI/Avatar-view/how-to.md
Updated Avatar-view documentation.
=> Updated AvatarView documentation- Hotfix

MAUI/ImageEditor/save.md
Updated the .NET MAUI SfImageEditor UG regarding the `CompressionQuality` parameter in the `ImageSaving` event
=> 896965-CompressionQuality parameter details added in UG

MAUI/PDF-Viewer/Toolbar.md
Task Link - https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/898689/
Title  - Improve UG documentation for MAUI PDF Viewer toolbars
I have updated the toolbar UG with below order
=> 898689  Improve UG documentation for MAUI PDF Viewer toolbars

MAUI/PDF-Viewer/Toolbar.md
Corrected Alignment in Code snippet
=> 902724 -  Feedback addressing for updated toolbar UG documentation 

MAUI/DataGrid/grid-events.md
- Changed the LongPressedCommand to LongPressCommand.
=> Changed the LongPressCommand

MAUI/Themes/Themes.md
=> Updated the Themes.md

MAUI/Badge-View/Badge-customization.md, MAUI/Busy-Indicator/Set-Header.md, MAUI/CheckBox/Visual-Customization.md, MAUI/Radial-Menu/CenterButton-Customization.md, MAUI/Radial-Menu/SfRadialMenuItem-Customization.md, MAUI/Radio-Button/Visual-Customization.md, MAUI/TabView/Tab-Item-Customization.md
Hi @naveenkumar-sanjeevirayan,
I have prepared UG documentation for the Font autoscaling-enabled feature. 
Regards,
Arunachalam K
=> 902719 - Prepare UG documentation for the Font autoscaling enabled feature. 

MAUI/DatePicker/formatting.md, MAUI/DateTimePicker/formatting.md, MAUI/TimePicker/formatting.md
Added UG Documentation for Culture Support on Below Components
-Date Picker
-Time Picker
-Date Time Picker
=> 900341 Prepare UG for vol 3 features-Culture Support

MAUI/Cartesian-Charts/SplineRangeArea.md, maui-toc.html
**Description** 
Prepared UG document for the spline range area series in .NET MAUI
=> 835239-UG document for the spline range area series in .NET MAUI 

MAUI/Kanban-Board/Cards.md, MAUI/Kanban-Board/Column.md, MAUI/Kanban-Board/Events.md, MAUI/Kanban-Board/Getting-Started.md, MAUI/Kanban-Board/Overview.md, MAUI/Kanban-Board/Placeholder.md, MAUI/Kanban-Board/Workflows.md, MAUI/Kanban-Board/migration.md, maui-toc.html
Added the UG document for .NET MAUI Kanban-Board control. I have added the following sections.
- Overview
- Getting Started
- Column
- Workflows
- Cards
- Placeholder
- Events
=> 903604-UG document for .NET MAUI Kanban-Board control

MAUI/Calendar/headers.md
Changed the calendar control highlights.
=> MAUI-900342-Added Vol3 Calendar Highlights

MAUI/Calendar/date-navigation.md, MAUI/Calendar/events.md
Corrected Content Changes for the following feature
-Tapped Event Support
=> 900341-Prepare-Ug-for-Vol-3-features-Corrected Changes

MAUI/CheckBox/Events.md, MAUI/Radio-Button/Events.md, MAUI/TabView/Tab-Item-Customization.md
=> Resolved the alignment issue.

MAUI/NumericEntry/Basic-Features.md
Hi Team,
I have updated the Notes added in MaximumNumberDecimalDigits feature UG content.
Regards,
Sivaranjith N.
=> 904698-Prepared UG document for volume 3 moved features

MAUI/ImageEditor/save.md
Added the ug content for image editor
=> 903354 - UG Documentation for SfImageEditor

MAUI/Cartesian-Charts/Area.md, MAUI/Cartesian-Charts/BarChart.md, MAUI/Cartesian-Charts/BoxAndWhisker.md, MAUI/Cartesian-Charts/Bubble.md, MAUI/Cartesian-Charts/Candle.md, MAUI/Cartesian-Charts/Column.md, MAUI/Cartesian-Charts/Errorbar-Chart.md, MAUI/Cartesian-Charts/Fastline.md, MAUI/Cartesian-Charts/Histogram.md, MAUI/Cartesian-Charts/Line.md, MAUI/Cartesian-Charts/OHLC.md, MAUI/Cartesian-Charts/RangeArea.md, MAUI/Cartesian-Charts/Scatter.md, MAUI/Cartesian-Charts/StackedArea.md, MAUI/Cartesian-Charts/StackedArea100.md, MAUI/Cartesian-Charts/StackedColumn.md, MAUI/Cartesian-Charts/StackedLine.md, MAUI/Cartesian-Charts/StackedLine100.md, MAUI/Cartesian-Charts/StepArea.md, MAUI/Cartesian-Charts/Waterfall-Chart.md, MAUI/Funnel-Charts/Legend.md, MAUI/Pyramid-Charts/Legend.md
Marker Customization: Added a reference to the ShapeType API in the marker customization section to provide additional clarity and options for customization.
Chart Titles: Added titles to the necessary charts to enhance readability and provide context.
Funnel Chart Legend: Made minor adjustments to the funnel chart legend section for improved accuracy and presentation.
Content Alignment: Ensured proper content alignment in the user guide (UG) for a more consistent and polished appearance.
=> MAUI 892140 - Add API References, Chart Titles and Content Alignment Fixes in the UG Documentation

MAUI/Scheduler/date-navigation-restriction.md
Added ug documentation for SfScheduler imahe size
=> 903354 - UG Documentation for SfScheduler 

maui-toc.html
Task - https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/187726/
=> 187726 - Syncfusion License Validation Page Location Updated - Live

MAUI/TabView/Swiping.md
Add the limitation details about the EnableSwiping feature in the UG documentation.
=> 902719 - Add the limitation details about the EnableSwiping feature in the UG documentation.

MAUI/Accordion/events.md
Title | Description
-- | --
|Task Category | Site Audit|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/maui-docs/pull/2610|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187689|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B0C07BBB1-1233-47A7-818C-275A98FD0063%7D&file=Faith-%20Site%20Audit.xlsx&action=default&mobileredirect=true|
Changes Made | Reason for change |
|-- | -- |
|Changed-H1 Missing | To improve performance of the page |
=> SEO-188026--NET-MAUI-Accordion-events-H1-Missing

MAUI/Cartesian-Charts/SplineRangeArea.md, MAUI/Kanban-Board/Column.md, MAUI/Kanban-Board/Events.md, MAUI/Kanban-Board/Getting-Started.md, MAUI/Kanban-Board/Overview.md, MAUI/Kanban-Board/Workflows.md, MAUI/Kanban-Board/migration.md, maui-toc.html
**Description** 
Updated review changes for Kanban control UG document.
=> 903604-UG document for  .NET-MAUI Kanban control

MAUI/Scheduler/getting-started.md
Modified MAUI Scheduler getting started content
=> Modified MAUI Scheduler getting started content

MAUI/Avatar-view/Getting-Started.md, MAUI/Busy-Indicator/Getting-Started.md, MAUI/Effects-View/Getting-Started.md, MAUI/NavigationDrawer/Getting-Started.md, MAUI/TabView/Getting-Started.md
Updated the Getting-Started page for Tab view, Navigation drawer, Busy indicator and effects view controls
=> 909942 - Updated the Getting-Started page for Tab view, Navigation drawer, Busy indicator and effects view controls

MAUI/CheckBox/Getting-Started.md, MAUI/Radial-Menu/Getting-Started.md, MAUI/Radio-Button/Getting-Started.md, MAUI/Switch/Getting-Started.md
Update the Getting-Started page for Radio button, Check box, Radial menu and Switch controls
=> Update the Getting-Started page for Radio button, Check box, Radial menu and Switch controls

MAUI/Cards/getting-started.md, MAUI/DatePicker/getting-started.md, MAUI/Linear-Gauge/getting-started.md, MAUI/Picker/getting-started.md, MAUI/Shimmer/getting-started.md, MAUI/StepProgressBar/getting-started.md, MAUI/TimePicker/getting-started.md
Modified MAUI calendar team side control getting started content.
- Picker
- Linear Gauge
- StepProgressBar
- Shimmer
- Cards
- Date Picker
- Time Picker
=> Modified MAUI Calendar Team Side Control Getting Started Content

MAUI/Parallax-View/Getting-started.md, MAUI/SunburstChart/Getting-Started.md
I have followed common getting started file format and updated the content as discussed with PLO. Modified the following the getting started file for the ParallaxView control
=> Modified Parallax View getting started content

MAUI/TreeMap/getting-started.md
Modified MAUI TreeMap getting started content
=> Modified MAUI TreeMap getting started content

MAUI/ImageEditor/getting-started.md
Modified MAUI ImageEditor getting started content
=> Modified MAUI ImageEditor getting started content

MAUI/DataForm/getting-started.md
Modified MAUI DataForm getting started content
=> Modified MAUI DataForm getting started content

MAUI/Scheduler/getting-started.md, MAUI/Segmented-Control/getting-started.md
Modified MAUI Segmented Control getting started content
=> Modified MAUI Segmented Control getting started content

MAUI/DigitalGauge/Getting-Started.md
Modified MAUI Digital gauge getting started content
=> Modified MAUI Digital gauge getting started content 

MAUI/DataGrid/Getting-started.md
Updated the SfDataGrid Getting-started.md file as per the documentation format.
=> Update DataGrid Getting-started.md file as per the documentation format.

MAUI/Autocomplete/Getting-Started.md, MAUI/Carousel-View/getting-started.md, MAUI/ComboBox/Getting-Started.md, MAUI/DateTime-Slider/getting-started.md, MAUI/Masked-Entry/Getting-Started.md, MAUI/NumericEntry/Getting-Started.md, MAUI/SignaturePad/getting-started.md
Hi Team, 
I've updated the Getting Started UG content for the controls mentioned below.
- Autocomplete
- Carousel 
- ComboBox 
- MaskedEntry
- NumericEntry
- SfDateTimeSlider
- SignaturePad
Regards,
Prithis I.
=> 910330 [Dev] Updated the Getting Started UG content for the Maui Tools controls.

MAUI/Kanban-Board/Cards.md, MAUI/Kanban-Board/Column.md, MAUI/Kanban-Board/Getting-Started.md, MAUI/Kanban-Board/migration.md
Modified Kanban getting started version as Kanban supports from .NET 8 and done code snippet alignment changes
=> 903604 Modified Kanban getting started version and alignment changes

MAUI/DataGrid/migration.md, MAUI/DataGrid/overview.md, MAUI/DataGrid/performance.md
- Modified the migration and overview documentation based on the current available features
=> Modified the migration and overview documentation

MAUI/DataForm/getting-started.md, MAUI/ImageEditor/getting-started.md, MAUI/Maps/getting-started.md, MAUI/Scheduler/getting-started.md, MAUI/Segmented-Control/getting-started.md, MAUI/TreeMap/getting-started.md
Scheduler UG review corrections updated
=> 910528- Scheduler UG review corrections updated

MAUI/Accordion/getting-started.md, MAUI/Chat/getting-started.md, MAUI/Expander/getting-started.md, MAUI/ListView/getting-started.md, MAUI/Popup/getting-started.md, MAUI/Pull-to-Refresh/getting-started.md, MAUI/TreeView/getting-started.md
Resolved the typo mistakes and modified the content.
=> MAUI ListView - Resolved the typo mistakes.

MAUI/Autocomplete/Getting-Started.md, MAUI/Button/Getting-Started.md, MAUI/Carousel-View/getting-started.md, MAUI/Chips/Getting-Started.md, MAUI/ComboBox/Getting-Started.md, MAUI/DateTime-Range-Selector/getting-started.md, MAUI/DateTime-Range-Slider/getting-started.md, MAUI/DateTime-Slider/getting-started.md, MAUI/Masked-Entry/Getting-Started.md, MAUI/NumericEntry/Getting-Started.md, MAUI/Range-Selector/getting-started.md, MAUI/Range-Slider/getting-started.md, MAUI/Rating/Getting-Started.md, MAUI/Rotator/Getting-started.md, MAUI/SignaturePad/getting-started.md, MAUI/Slider/getting-started.md, MAUI/TextInputLayout/Getting-Started.md
Hi Team,
I've improved the Existing getting started UG content for the Maui Tools controls. Please review and merge these changes.
Regards,
Prithis I.
=>  910330 [Development] Updated the Getting Started UG content for the Maui Tools controls.

MAUI/Backdrop/getting-started.md, MAUI/Barcode-Generator/getting-started.md, MAUI/Calendar/getting-started.md, MAUI/Cards/getting-started.md, MAUI/CircularProgressBar/getting-started.md, MAUI/DatePicker/getting-started.md, MAUI/DateTimePicker/getting-started.md, MAUI/Linear-Gauge/getting-started.md, MAUI/LinearProgressBar/getting-started.md, MAUI/Picker/getting-started.md, MAUI/Radial-Gauge/getting-started.md, MAUI/Shimmer/getting-started.md, MAUI/StepProgressBar/getting-started.md, MAUI/TimePicker/getting-started.md
Calendar team control UG review correction added.
=> MAUI-903350: Calendar Team Control UG Review Correction Added

MAUI/Effects-View/Getting-Started.md
Resolve conflicts in the effects view getting started page.
=> Resolved conflicts in effects view

MAUI/Avatar-view/Getting-Started.md, MAUI/Badge-View/Getting-Started.md, MAUI/Busy-Indicator/Getting-Started.md, MAUI/CheckBox/Getting-Started.md, MAUI/Effects-View/Getting-Started.md, MAUI/NavigationDrawer/Getting-Started.md, MAUI/Radial-Menu/Getting-Started.md, MAUI/Radio-Button/Getting-Started.md, MAUI/Switch/Getting-Started.md, MAUI/TabView/Getting-Started.md
Updated getting started page of core controls
=> Updated getting started page of core controls

MAUI/DataGrid/migration.md
* Resolved the reported CI failures in DataGrid UG documentation by the following link,
=> Resolved the CI failures in DataGrid UG documentation

MAUI/AIAssistView/header.md, MAUI/AIAssistView/items.md
Added changes in AssistItems of AIAssistView
=> Added changes in AssistItems of AIAssistView

MAUI/PDF-Viewer/Magnification.md, MAUI/PDF-Viewer/Migration.md
Fixed syntax errors in Migration and Magnification
=> Fixed syntax errors in Migration and Magnification

MAUI/Kanban-Board/Cards.md, MAUI/Kanban-Board/Column.md, MAUI/Kanban-Board/Events.md, MAUI/Kanban-Board/Getting-Started.md, MAUI/Kanban-Board/Localization.md, MAUI/Kanban-Board/Workflows.md, MAUI/Kanban-Board/migration.md
- Added API links to kanban features
- Updated Kanban know issue content
=> MAUI-903604 Updated Kanban UG and added links 

MAUI/Kanban-Board/Cards.md, MAUI/Kanban-Board/Column.md, MAUI/Kanban-Board/Events.md, MAUI/Kanban-Board/Getting-Started.md, MAUI/Kanban-Board/Localization.md, MAUI/Kanban-Board/Workflows.md, MAUI/Kanban-Board/migration.md
Updated API links to Kanban features
Updated Kanban know issue content
=> MAUI Kanban UG API URL link updated hotfix

MAUI/ListView/viewappearance.md, MAUI/TreeView/appearance.md
Added UG content for removing the ripple background when clicking a item.
=> ListView - Added UG for disabling the ripple effect.

MAUI/DataGrid/pull-to-refresh.md, MAUI/DataGrid/row-drag-and-drop.md
Updated the API links for SfDataGrid Row Drag and Drop Properties.
=> Included the API links to the new features of MAUI DataGrid

MAUI/Calendar/events.md, MAUI/DatePicker/events.md, MAUI/DateTimePicker/events.md, MAUI/Picker/events.md, MAUI/TimePicker/events.md
API links updated in UG document.
Regards,
Indumathi R
=> MAUI-910572-APILinksUpdation-API links updated in UG.

MAUI/AIAssistView/data-binding.md, MAUI/AIAssistView/getting-started.md, MAUI/AIAssistView/header.md, MAUI/AIAssistView/items.md
Added API Links for AI AssistView merged UGs
=> Added API Links for AI AssistView merged UGs

MAUI/Avatar-view/Getting-Started.md, MAUI/Badge-View/Badge-customization.md, MAUI/Badge-View/Getting-Started.md, MAUI/Busy-Indicator/AnimationType.md, MAUI/Busy-Indicator/Getting-Started.md, MAUI/CheckBox/Events.md, MAUI/CheckBox/Getting-Started.md, MAUI/CheckBox/Visual-Customization.md, MAUI/Effects-View/Getting-Started.md, MAUI/NavigationDrawer/Getting-Started.md, MAUI/Radial-Menu/CenterButton-Customization.md, MAUI/Radial-Menu/Getting-Started.md, MAUI/Radial-Menu/SfRadialMenuItem-Customization.md, MAUI/Radio-Button/Events.md, MAUI/Radio-Button/Getting-Started.md, MAUI/Radio-Button/Grouping.md, MAUI/Radio-Button/Visual-Customization.md, MAUI/Switch/Getting-Started.md, MAUI/TabView/Getting-Started.md, MAUI/TabView/Header-Display-Mode.md, MAUI/TabView/Selection-Indicator-Customization.md, MAUI/TabView/Tab-Bar-Customization.md, MAUI/TabView/Tab-Item-Customization.md
Update the Getting Started page and the API links for Volume 3 features
=> Update the Getting Started page and the API links for Volume 3 features

MAUI/Avatar-view/Getting-Started.md, MAUI/Badge-View/Badge-customization.md, MAUI/Badge-View/Getting-Started.md, MAUI/Busy-Indicator/AnimationType.md, MAUI/Busy-Indicator/Getting-Started.md, MAUI/CheckBox/Events.md, MAUI/CheckBox/Getting-Started.md, MAUI/CheckBox/Visual-Customization.md, MAUI/Effects-View/Getting-Started.md, MAUI/NavigationDrawer/Getting-Started.md, MAUI/Radial-Menu/CenterButton-Customization.md, MAUI/Radial-Menu/Getting-Started.md, MAUI/Radial-Menu/SfRadialMenuItem-Customization.md, MAUI/Radio-Button/Events.md, MAUI/Radio-Button/Getting-Started.md, MAUI/Radio-Button/Grouping.md, MAUI/Radio-Button/Visual-Customization.md, MAUI/Switch/Getting-Started.md, MAUI/TabView/Getting-Started.md, MAUI/TabView/Header-Display-Mode.md, MAUI/TabView/Selection-Indicator-Customization.md, MAUI/TabView/Tab-Bar-Customization.md, MAUI/TabView/Tab-Item-Customization.md
Update the getting-started page
=> Update the getting-started page

MAUI/Accordion/getting-started.md, MAUI/Chat/getting-started.md, MAUI/Expander/getting-started.md, MAUI/ListView/getting-started.md
Added changes in Getting Started md files in SfChat,SfAccordion,SfExpander,SfListview
=> Added changes in Getting Started md files in SfChat,SfAccordion,SfExpander,SfListview

MAUI/CheckBox/Getting-Started.md
Update the CheckBox Getting-Started page
=> Update the CheckBox Getting-Started page

MAUI/Carousel-View/getting-started.md, MAUI/ComboBox/Filtering.md
Hi Team,
I have revamped the UG contents in .NET MAUI SfComboBox and SfCarousel controls.
Regards,
Sivaranjith N.
=> 910330-Revamped the SfComboBox and SfCarousel UG contents.

MAUI/Carousel-View/getting-started.md, MAUI/ComboBox/Filtering.md
Hi Team,
I have revamped the UG contents in .NET MAUI SfComboBox and SfCarousel controls.
Regards,
Sivaranjith N.
=> 910330-Revamped the UG contents in SfComboBox and SfCarousel controls.

MAUI/AIAssistView/suggestions.md, maui-toc.html
Added UG document for AIAssistView Suggestions
=> Added UG document for AIAssistView Suggestions

MAUI/AIAssistView/events.md, maui-toc.html
Added UG document for AIAssistView Events and Commands
=> Added UG document for AIAssistView Events and Commands 

MAUI/Backdrop/getting-started.md, MAUI/Barcode-Generator/getting-started.md, MAUI/Calendar/getting-started.md, MAUI/Cards/getting-started.md, MAUI/CircularProgressBar/getting-started.md, MAUI/DataForm/getting-started.md, MAUI/DatePicker/getting-started.md, MAUI/DateTimePicker/getting-started.md, MAUI/DigitalGauge/Getting-Started.md, MAUI/ImageEditor/getting-started.md, MAUI/Linear-Gauge/getting-started.md, MAUI/LinearProgressBar/getting-started.md, MAUI/Maps/getting-started.md, MAUI/Picker/getting-started.md, MAUI/Radial-Gauge/getting-started.md, MAUI/Scheduler/getting-started.md, MAUI/Segmented-Control/getting-started.md, MAUI/Shimmer/getting-started.md, MAUI/StepProgressBar/getting-started.md, MAUI/TimePicker/getting-started.md, MAUI/TreeMap/getting-started.md
Modified all calendar and scheduler team side content changes.
- Backdrop
- Barcode
- Calendar
- Cards
- CircularProgressBar
- DataForm
- DatePicker
- DateTimePicker
- DigitalGauge
- ImageEditor
- LinearGauge
- LinearProgressBar
- Maps
- Picker
- RadialGauge
- Scheduler
- Segment control
- Shimmer
- StepProgressBar
- TimePicker
- TreeMap
=> MAUI-903350-Modified All Calendar And Scheduler Team Side Control Content Changes

MAUI/ComboBox/Filtering.md
Hi Team,
I have revamped the UG contents in .NET MAUI SfComboBox control.
Regards,
Sivaranjith N.
=> 910330-Revamped the CustomFiltering UG contents in SfComboBox.

MAUI/Popup/styles.md
Added Content for Popup Dynamic style changes
=> Added Content for Popup Dynamic style changes

MAUI/PDF-Viewer/Localization.md
Updated the localization table since customer has reported as default names are missing following names:
StandardStamps
CustomStamps
Enter
=> Update the localization table 

MAUI/AIAssistView/styles.md, MAUI/AIAssistView/suggestions.md, MAUI/Themes/Keys.md, maui-toc.html
Added UG document for AIAssistView Keys for Styles
=> Added UG document for AIAssistView Keys for Styles 

MAUI/DatePicker/getting-started.md
|--|--|
|Task Category|Money Keywords .NET MAUI Date Picker|
|Content Task Link/Mail Screenshot| https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/765397/ https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/765939|
|UX task|NA|
|Dev |PR - https://github.com/syncfusion-content/featuretour-maui/pull/1308|
|Master |PR - https://github.com/syncfusion-content/featuretour-maui/pull/1309|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/189916|
|SharePoint link| https://syncfusion.sharepoint.com/:u:/r/sites/GH/SEO/SitePages/NET-MAUI-Date-Picker---Finalized-Money-Keywords-Status.aspx?csf=1&web=1&e=uUJaQy|
|---|---|---|
|.net maui date picker|10-100|4UG|
|Changes made| …
=> SEO-189916-.NET-MAUI-Date-Picker-MK-Interlinking

MAUI/Radio-Button/Getting-Started.md
|--|--|
|Task Category|Money Keywords .NET MAUI Radio Button|
|Content Task Link/Mail Screenshot| https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/768535|
|UX task|NA|
|Dev PR| https://github.com/syncfusion-content/featuretour-maui/pull/1300|
|Master PR| https://github.com/syncfusion-content/featuretour-maui/pull/1301|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/188929|
|SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Radio-Button---Finalized-Money-Keywords-Status.aspx|
|---|---|---|
|.net maui radio button|10-100|5UG|
|Changes made| Reason for change|
| ---| ---|
|Added Note Section | To stuff the keyword along with interlinking in …
=> SEO-188993-.NET-MAUI-Radio-Button-MK-Interlinking

MAUI/DateTimePicker/getting-started.md
|--|--|
|Task Category|Money Keywords .NET MAUI DateTimePicker|
|Content Task Link/Mail Screenshot| https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/765397/ https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/765939|
|UX task|NA|
|Dev |PR - https://github.com/syncfusion-content/featuretour-maui/pull/1293|
|Master |PR - https://github.com/syncfusion-content/featuretour-maui/pull/1294|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/189916|
|SharePoint link| https://syncfusion.sharepoint.com/:u:/r/sites/GH/SEO/SitePages/Keyword-Plan---.NET-MAUI-Date-Time-Picker-Money-Keywords.aspx?csf=1&web=1&e=z0P7cb|
|---|---|---|
|.net maui datetimepicker|10-100|5UG| …
=> SEO-189770-.NET-MAUI-DateTimePicker-MK-Interlinking

MAUI/DataForm/migration.md, MAUI/ImageEditor/migration.md, MAUI/Scheduler/migration.md, MAUI/TreeMap/migration.md
Removed the upcoming features in ug for maui features that are added.
=> 903354-Updated the upcoming features

MAUI/AIAssistView/getting-started.md
Modified namespace in GettingStarted in UG .
=> config:Modified the namespace in getting-started.md.

MAUI/ImageEditor/getting-started.md
|--|--|
|Task Category|Money Keywords .NET MAUI Image Editor|
|Content Task Link/Mail Screenshot| https://dev.azure.com/Syncfusion-General/Content/_workitems/edit/768537/|
|UX task|NA|
|Dev |PR - https://github.com/syncfusion-content/featuretour-maui/pull/1337|
|Master|PR - https://github.com/syncfusion-content/featuretour-maui/pull/1311|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/188914|
|SharePoint link| https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/NET-MAUI-Radio-Button---Finalized-Money-Keywords-Status.aspx|
|---|---|---|
|.net maui image editor|10-100|5UG|
|Changes made| Reason for change|
| ---| ---|
|Added note section | To add the keyword in the UG page along …
=> SEO-189914-.NET-MAUI-Image-Editor-MK-Interlinking

MAUI/PDF-Viewer/Migration.md
updated the PageChanged event in migration UG document
=> 916507 - Enhance Migration Documentation by Adding Information on the PageChanged Event

MAUI/Avatar-view/customization.md, MAUI/TabView/Selection-Indicator-Customization.md, MAUI/TabView/Swiping.md, MAUI/TabView/Tab-Item-Customization.md
Added API links for the following features :
-Scroll button customization in Maui Tab view
-Indicator stroke thickness in Maui Tab view
-Font auto-scaling mode in Maui Avatar view
=> Added API links for the new features.

MAUI/DigitalGauge/Getting-Started.md
|--|--|
|Task Category|Money Keywords .NET MAUI Digital Gauge|
|Content Task Link/Mail Screenshot| https://syncfusion-content.bolddesk.com/support/tickets/2335|
|UX task|NA|
|Dev |PR - https://github.com/syncfusion-content/featuretour-maui/pull/1364|
|Master |PR - https://github.com/syncfusion-content/featuretour-maui/pull/1365|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/192106|
|SharePoint link| https://syncfusion.sharepoint.com/:u:/r/sites/GH/SEO/SitePages/NET-MAUI-Digital-Gauge---Finalized-Money-Keywords-Status.aspx?csf=1&web=1&e=uUJaQy|
|---|---|---|
|.net maui digital gauge|10-100|1FT, 2UG|
|Changes made| Reason for change|
| ---| ---|
|Added Note section | To stuff the …
=> SEO-192106-MAUI-Digital-Gauge-MK-Interlinking

MAUI/Scheduler/getting-started.md
Scheduler Getting Started UG Correction.
=> MAUI-921441-Scheduler Getting Started UG Correction

MAUI/ImageEditor/save.md
Add MacCatalyst save file permission details in SfImageEditor
=> Update save.md Content in SfImageEditor

MAUI/DataGrid/Column-types.md, MAUI/DataGrid/performance.md
Included the details of Header line break mode and LoadUIView as false support for ImageColumn of DataGrid in the UG.
=> MAUI - 926461-Included HeaderLineBreakMode property

MAUI/Button/Getting-Started.md, MAUI/Button/Overview.md, MAUI/Carousel-View/getting-started.md, MAUI/Carousel-View/overview.md, MAUI/Chips/Getting-Started.md, MAUI/Chips/Overview.md, MAUI/NumericEntry/Getting-Started.md, MAUI/NumericEntry/Overview.md
Hi team, 
I have added Notice content on Overview and Getting Started page Top in a box for Carousel, Chip, Button, NumericEntry controls
Regards,
Hemalatha
=> Added Notice content on Overview and Getting Started page

MAUI/DataGrid/conditional-styling.md, MAUI/DataGrid/data-binding.md
Included the UseBindingValue property and conditional styling changes.
=> Included the UseBindingValue property

MAUI/UIKit/GettingStarted.md, MAUI/UIKit/page-and-template-dependencies.md, MAUI/visual-studio-integration/Essential-UI-Kit.md, maui-toc.html
Description:
Made Corrections Based On Staging
=> 925387-Made Corrections Based On Staging

MAUI/visual-studio-integration/Essential-UI-Kit.md
=> Updated Links

MAUI/AIAssistView/working-with-aiassistview.md, MAUI/Chat/styles.md, MAUI/Themes/Keys.md
Add theme keys for interaction - .NET MAUI Chat
=> 910286: Add theme keys for interaction - .NET MAUI Chat

MAUI/Autocomplete/Selection.md, MAUI/ComboBox/Selection.md, MAUI/NumericEntry/UpDown-Button.md
Hi team,
I have revamped the contents in .NET MAUI Autocomplete, ComboBox and NumericEntry controls.
Regards,
Sivaranjith N.
=> 927723-Revamped the UG contents in .NET MAUI tools editor controls.

MAUI/TextInputLayout/Events.md
Hi team,
I have updated the Events md file type to UTF-8 encoding in TextInputLayout control.
Regards,
Sivaranjith N.
=> 927723-Updated UTF-8 encoding in TextInputLayout

MAUI/Calendar/migration.md, MAUI/UIKit/GettingStarted.md, MAUI/visual-studio-integration/Essential-UI-Kit.md
=> 925387-Fixed-Errors

MAUI/Calendar/migration.md, MAUI/UIKit/GettingStarted.md, MAUI/visual-studio-integration/Essential-UI-Kit.md
=> 925387-Fixed Error-Dev

MAUI/UIKit/GettingStarted.md, MAUI/visual-studio-integration/Essential-UI-Kit.md
=> 925387-Cleared Error

MAUI/UIKit/GettingStarted.md, MAUI/visual-studio-integration/Essential-UI-Kit.md
=> 925387-Cleared Error-Dev

MAUI/TextInputLayout/Events.md
Hi team,
I have updated the Events md file type to UTF-8 encoding in TextInputLayout control.
Regards,
Sivaranjith N.
=> 927723-Updated UTF-8 encoding in TextInputLayout 

MAUI/PDF-Viewer/Magnification.md, MAUI/PDF-Viewer/Migration.md
Fixed the exception in MAUI PDF Viewer Documents
=> Fixed the exception in MAUI PDF Viewer Documents 

MAUI/UIKit/GettingStarted.md, MAUI/visual-studio-integration/Essential-UI-Kit.md
Description:
Made Correction on UI Kit UG
=> 925387-UI kit correction dev

MAUI/UIKit/GettingStarted.md, MAUI/visual-studio-integration/Essential-UI-Kit.md
Description:
Added Corrections
=> 925387-UI kit correction hotfix

MAUI/CheckBox/Visual-Customization.md, MAUI/Radio-Button/Visual-Customization.md, MAUI/TabView/Tab-Item-Customization.md
- Added API links for RadioButton,CheckBox and TabView features.
=> Added API links for RadioButton,CheckBox and TabView features.

MAUI/CheckBox/Visual-Customization.md, MAUI/Radio-Button/Visual-Customization.md, MAUI/TabView/Tab-Item-Customization.md
- Added API links for RadioButton,CheckBox and TabView features.
=> Added API links for RadioButtton,CheckBox and TabView.

MAUI/Autocomplete/Selection.md, MAUI/ComboBox/Selection.md, MAUI/NumericEntry/UpDown-Button.md
Hi team,
I have Updated API Links - Volume 4 Features
Regards,
Hemalatha
=> Updated API Links - Volume 4 Feature

MAUI/AIAssistView/working-with-aiassistview.md
Added API links for working with AIAssistView - working-with-aiassistvew
=> Added API links for working with AIAssistView - working-with-aiassistvew

MAUI/UIKit/Overview.md
Description:
Updated Play Store Link for UI Kit
Related Task : https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/925387
=> 925387-Updated Play Store Link UI Kit-hotfix

MAUI/UIKit/Overview.md
Description:
Updated Play Store Link for UI Kit
Related Task : https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/925387
=> 925387-Updated Play Store Link UI Kit

MAUI/DataGrid/grouping.md
- Update video in grouping section
=> Update video in Grouping 

MAUI/DataForm/floating-label-layout.md, MAUI/ImageEditor/text.md, MAUI/Scheduler/month-view.md, MAUI/Scheduler/resource-view.md
Included video links in the UG document for the controls MAUI SfDataForm, SfImageEditor and SfScheduler.
=> Added Video Links in UG Documentation

MAUI/Calendar/customizations.md, MAUI/Calendar/getting-started.md
Hi @MuniappanSubramanian,
Youtube video link updated.
Regards,
Indumathi R
=> MAUI-933015-YoutubeVideoLink-Link updated for calendar customization.

MAUI/Cartesian-Charts/Annotation.md, MAUI/Cartesian-Charts/DataLabels.md, MAUI/Cartesian-Charts/Tooltip.md, MAUI/Kanban-Board/Getting-Started.md, MAUI/Parallax-View/Getting-started.md, MAUI/Polar-Charts/Getting-Started.md
This PR updates the UG documentation with new YouTube video links for the MAUI Charts, Kanban, and ParallaxView Controls.
**Charts:**
- How to Add and Customize Annotations in .NET MAUI Cartesian Charts - [v1u774lp9pQ](https://youtu.be/v1u774lp9pQ)
- How to Customize the Tooltip in .NET MAUI Charts - [tDwQ7h9jwWk](https://youtu.be/tDwQ7h9jwWk)
- How to Customize the Data Labels in .NET MAUI Charts - [tDwQ7h9jwWk](https://youtu.be/tDwQ7h9jwWk)
- Getting Started with .NET MAUI Polar and Radar Charts - [Ga9mytwCo_s](https://youtu.be/Ga9mytwCo_s)
**Parallax View:**
- Getting Started with the .NET MAUI Parallax View Control - [ezzIDWYYrUc](https://youtu.be/ezzIDWYYrUc)
**Kanban Board:**
- Getting Started with the .NET MAUI Kanban Board - [Mq55vjT7ZEA](https://youtu.be/Mq55vjT7ZEA)
=> Update the YouTube video links for MAUI Charts, Kanban, and ParallaxView UG Document

MAUI/DataGrid/Getting-started.md
Implemented tabbed content in the Getting Started page of the UG, providing two tabs for Visual Studio and Visual Studio Code instructions.
=> Added the tab support to the Getting Started page in MAUI DataGrid

MAUI/PDF-Viewer/Getting-Started.md
Updated the getting started page with two tabs for visual studio and visual studio code
=> 934831 - Update the getting started page with two tabs for visual studio and visual studio code

MAUI/AIAssistView/getting-started.md, MAUI/Chat/getting-started.md, MAUI/ListView/getting-started.md, MAUI/Popup/getting-started.md, MAUI/TreeView/getting-started.md
Updating UG for ListView, Popup, TreeView, AIAssistView and Chat
=> Updating UG for ListView, Popup, TreeView, AIAssistView and Chat

MAUI/Backdrop/getting-started.md, MAUI/Barcode-Generator/getting-started.md, MAUI/Calendar/getting-started.md, MAUI/Cards/getting-started.md, MAUI/CircularProgressBar/getting-started.md, MAUI/DataForm/getting-started.md, MAUI/DatePicker/getting-started.md, MAUI/DateTimePicker/getting-started.md, MAUI/DigitalGauge/Getting-Started.md, MAUI/ImageEditor/getting-started.md, MAUI/Linear-Gauge/getting-started.md, MAUI/LinearProgressBar/getting-started.md, MAUI/Maps/getting-started.md, MAUI/Picker/getting-started.md, MAUI/Radial-Gauge/getting-started.md, MAUI/Scheduler/getting-started.md, MAUI/Segmented-Control/getting-started.md, MAUI/Shimmer/getting-started.md, MAUI/StepProgressBar/getting-started.md, MAUI/TimePicker/getting-started.md, MAUI/TreeMap/getting-started.md
As per the suggestions, updated the Getting started UG document.
Regards,
Indumathi R
=> MAUI-914189-UGUpdation-Updated the Getting-Started.md

MAUI/AIAssistView/getting-started.md, MAUI/Chat/getting-started.md, MAUI/ListView/getting-started.md, MAUI/Popup/getting-started.md
Adding Taps to the VS and VS Code for Popup, ListView, Ai AssistView and Chat.
=> Adding Taps to the VS and VS Code for Popup, ListView, Ai AssistView and Chat.

MAUI/Accordion/getting-started.md, MAUI/DataGrid/Getting-started.md, MAUI/Expander/getting-started.md, MAUI/Pull-to-Refresh/getting-started.md
Description:
Adding tabs for Datagrid,Accordion,Expander and PullToRefresh
=> Adding tabs for Datagrid,Accordion,Expander and PullToRefresh

MAUI/Autocomplete/Getting-Started.md, MAUI/Button/Getting-Started.md, MAUI/Carousel-View/getting-started.md, MAUI/Chips/Getting-Started.md, MAUI/ComboBox/Getting-Started.md, MAUI/DateTime-Range-Selector/getting-started.md, MAUI/DateTime-Range-Slider/getting-started.md, MAUI/DateTime-Slider/getting-started.md, MAUI/Masked-Entry/Getting-Started.md, MAUI/NumericEntry/Getting-Started.md, MAUI/Range-Selector/getting-started.md, MAUI/Range-Slider/getting-started.md, MAUI/Rating/Getting-Started.md, MAUI/Rotator/Getting-started.md, MAUI/SignaturePad/getting-started.md, MAUI/Slider/getting-started.md, MAUI/TextInputLayout/Getting-Started.md
Hi team,
I have added tab support for Visual Studio and Visual Studio code in getting started page
SfAutocomplete
SfComboBox
SfMaskedEntry
SfNumericEntry
SfTextInputLayout
SfChip
SfCarousel
SfRotator
SfButton
SfRating
SfSignaturePad
SfSlider
SfRangeSlider
SfRangeSelector
SfDateTimeSlider
SfDateTimeRangeSlider
SfDateTimeRangeSelector
=> 935343 [Dev] Add tab support for Visual Studio and Visual Studio code in getting started page 

MAUI/Autocomplete/Getting-Started.md, MAUI/Button/Getting-Started.md, MAUI/Carousel-View/getting-started.md, MAUI/Chips/Getting-Started.md, MAUI/ComboBox/Getting-Started.md, MAUI/DateTime-Range-Selector/getting-started.md, MAUI/DateTime-Range-Slider/getting-started.md, MAUI/DateTime-Slider/getting-started.md, MAUI/Masked-Entry/Getting-Started.md, MAUI/NumericEntry/Getting-Started.md, MAUI/Range-Selector/getting-started.md, MAUI/Range-Slider/getting-started.md, MAUI/Rating/Getting-Started.md, MAUI/Rotator/Getting-started.md, MAUI/SignaturePad/getting-started.md, MAUI/Slider/getting-started.md, MAUI/TextInputLayout/Getting-Started.md
Update the following changes in tabcontent
- ComboBox still not changed.
- Trademark symbol is missing for Syncfusion in new PR changes
- Some controls the Add a Basic Rotator is not added properly inside the tab
- In handler code the highlight is missinga
- Changed all Tools control Visual Studio Code Step 2
=> 935343 [Hotfix] Address UG tabcontent Changes in Maui Tools

MAUI/Autocomplete/Getting-Started.md, MAUI/Button/Getting-Started.md, MAUI/Carousel-View/getting-started.md, MAUI/Chips/Getting-Started.md, MAUI/ComboBox/Getting-Started.md, MAUI/DateTime-Range-Selector/getting-started.md, MAUI/DateTime-Range-Slider/getting-started.md, MAUI/DateTime-Slider/getting-started.md, MAUI/Masked-Entry/Getting-Started.md, MAUI/NumericEntry/Getting-Started.md, MAUI/Range-Selector/getting-started.md, MAUI/Range-Slider/getting-started.md, MAUI/Rating/Getting-Started.md, MAUI/Rotator/Getting-started.md, MAUI/SignaturePad/getting-started.md, MAUI/Slider/getting-started.md, MAUI/TextInputLayout/Getting-Started.md
Update the following changes in tabcontent
- ComboBox still not changed.
- Trademark symbol is missing for Syncfusion in new PR changes
- Some controls the Add a Basic Rotator is not added properly inside the tab
- In handler code the highlight is missinga
- Changed all Tools control Visual Studio Code Step 2
=> 935343 [Dev] Address UG tabcontent Changes in Maui Tools

MAUI/Cartesian-Charts/Getting-Started.md, MAUI/Circular-Charts/Getting-Started.md, MAUI/Funnel-Charts/Getting-Started.md, MAUI/Polar-Charts/Getting-Started.md, MAUI/Pyramid-Charts/Getting-Started.md
Updated the project and package installation, registering the handler and chart creation sections in the Getting-Started.md files for the chart controls.
=> Update Charts Getting Started

MAUI/Backdrop/getting-started.md, MAUI/Barcode-Generator/getting-started.md, MAUI/CircularProgressBar/getting-started.md, MAUI/Linear-Gauge/getting-started.md, MAUI/LinearProgressBar/getting-started.md, MAUI/Maps/getting-started.md, MAUI/Picker/getting-started.md, MAUI/StepProgressBar/getting-started.md, MAUI/TimePicker/getting-started.md
Review corrections updated.
Regards,
Indumathi R
=> MAUI-934394-HotfixUGUpdation-Updated the UG.

MAUI/Backdrop/getting-started.md, MAUI/Barcode-Generator/getting-started.md, MAUI/CircularProgressBar/getting-started.md, MAUI/Linear-Gauge/getting-started.md, MAUI/LinearProgressBar/getting-started.md, MAUI/Maps/getting-started.md, MAUI/Picker/getting-started.md, MAUI/StepProgressBar/getting-started.md, MAUI/TimePicker/getting-started.md
Updated the corrections.
Regards,
Indumathi R
=> MAUI-934422-UGUpdation-Updated the Rated symbol.

MAUI/Avatar-view/Getting-Started.md
Added JetBrains Rider tab content in avatar view
=> Added JetBrains Rider tab content in avatar view

MAUI/Rotator/DataTemplateSelector.md, MAUI/Rotator/Populating-Data.md
Hi team,
I have updated SfRotator UG images and source code
=> 930435 [Hotfix] - Revamp the UG documentation of .NET MAUI Rotator.

MAUI/CheckBox/Getting-Started.md, MAUI/Icons/Icons.md, MAUI/TabView/Migration.md, MAUI/TabView/Tab-Item-Customization.md, maui-toc.html
=> Updated the core controls UG- Hotfix

MAUI/Icons/Icons.md
Removed the Note and added the content normally in the Icons.md file.
=> Updated the Icons.md file-Hotfix

MAUI/Accordion/getting-started.md, MAUI/DataGrid/Getting-started.md, MAUI/Expander/getting-started.md, MAUI/Pull-to-Refresh/getting-started.md
=> 931816: Change highlighted lines.

MAUI/Icons/Icons.md
Updated the trademark symbol in the title of the Icons. md file.
=> Updated the trademark symbol in the title- Hotfix

MAUI/Accordion/getting-started.md, MAUI/DataGrid/Getting-started.md, MAUI/Expander/getting-started.md, MAUI/Pull-to-Refresh/getting-started.md
- Mentioned the package names instead core package in the Getting Stared content.
=> 931816: Mentioned the package names instead core package in the Getting Stared content. 

MAUI/Icons/Icons.md
Removed the unwanted lines in Icons.md file.
=> Removed the unwanted lines in Icons.md file- Hotfix

MAUI/Cartesian-Charts/Getting-Started.md, MAUI/Circular-Charts/Getting-Started.md, MAUI/Funnel-Charts/Getting-Started.md, MAUI/Kanban-Board/Getting-Started.md, MAUI/Parallax-View/Getting-started.md, MAUI/Polar-Charts/Getting-Started.md, MAUI/Pyramid-Charts/Getting-Started.md, MAUI/SunburstChart/Getting-Started.md
Added Syncfusion.Maui.Core package reference in the register the handler section in GettingStarted.md files for the chart controls, sunburst, parallax view and kanban control.
=> Update GettingStarted.md File for Chart controls

MAUI/Cartesian-Charts/Getting-Started.md, MAUI/Circular-Charts/Getting-Started.md, MAUI/Funnel-Charts/Getting-Started.md, MAUI/Kanban-Board/Getting-Started.md, MAUI/Parallax-View/Getting-started.md, MAUI/Polar-Charts/Getting-Started.md, MAUI/Pyramid-Charts/Getting-Started.md, MAUI/SunburstChart/Getting-Started.md
Added Syncfusion.Maui.Core package reference in the register the handler section in GettingStarted.md files for the chart controls, sunburst, parallax view and kanban control.
=> Update GettingStarted.md File

MAUI/DateTimePicker/getting-started.md, MAUI/DigitalGauge/Getting-Started.md, MAUI/Segmented-Control/getting-started.md, MAUI/TreeMap/getting-started.md
*Cleared the step5 and added as a separated topic in the TreeMap 
*Changed the Segmented-Control as Buttons in the step2 in Segmented-Control
*Changed the DigitalGuage as Guages in the step2 in DigitalGuages -
*Changed the DateTimePicker as Picker in the step2 in DateTimePicker
=> 939268 - clear UG alignment issue task

MAUI/Accordion/getting-started.md, MAUI/DataGrid/Getting-started.md, MAUI/Expander/getting-started.md
* Modified package related contents in JetBrains tab content for DataGrid, Accordian and Expander packages.
=> Modified package related contents in JetBrains tab content

MAUI/Autocomplete/Getting-Started.md, MAUI/ComboBox/Getting-Started.md
Hi team,
I have resolved build issue in Autocomplete and ComboBox
=> 939136 [Hotfix] Resolved build issue in Autocomplete ComboBox

MAUI/DataGrid/column-drag-and-drop.md, MAUI/DataGrid/row-drag-and-drop.md
Tutorial video link was added for both column and row drag and drop
=> Added tutorial video link for drag and drop

MAUI/ComboBox/Getting-Started.md
Hi team,
Resolved build issue in ComboBox/Getting-Started.md
=> 939136 [Hotfix] Resolved build issue in ComboBox 

MAUI/Cartesian-Charts/Legend.md
This PR updates the UG documentation with new YouTube video links for the MAUI Cartesian Chart Control.
Charts: How to Add and Customize the Legend in .NET MAUI Cartesian Charts - [5YG_kwZu6is](https://youtu.be/5YG_kwZu6is)
=>  Update the YouTube video links in the MAUI Cartesian Chart UG document

MAUI/Cartesian-Charts/Legend.md
This PR updates the UG documentation with new YouTube video links for the MAUI Cartesian Chart Control.
Charts: How to Add and Customize the Legend in .NET MAUI Cartesian Charts - [5YG_kwZu6is](https://youtu.be/5YG_kwZu6is)
=> Update the YouTube video links in the MAUI Cartesian Chart UG document

MAUI/Accordion/appearance.md, MAUI/Accordion/getting-started.md
Code updated  regarding the UG corrections in the Accordian.
UG corrections is based on the customer suggestion https://support.syncfusion.com/agent/tickets/687683 in the ticket attached. It seems frame work documentation also states the changes customer described in the ticket https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.layoutoptions.fillandexpand?view=net-maui-9.0.
=> [HotFix] Code updated regarding the UG corrections in the Accordian.

maui-toc.html
Resolved material icons page rendering issue.
=> Resolved material icons page rendering issue

MAUI/Badge-View/Badge-customization.md, MAUI/TabView/Tab-Item-Customization.md
Updated the API reference links in the Badge-customization.md and Tab-Item-Customization.md files.
=> Updated the API reference links in the BadgeView and TabView -Hotfix

MAUI/ListView/viewappearance.md
**Task ID:**
- [UG documentation 940511](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/940511): [Maui - SfListView] Prepare UG for Visual States Selected and Pressed
- Included Visual states for Selected and Pressed.
=> UG documentation 940511: [Maui - SfListView] Prepare UG for Visual States Selected and Pressed

MAUI/DatePicker/date-picker-mode.md
Description:
Fixed build Failure
=> 943227-Fixed Failure

MAUI/Scheduler/day-week-views.md, MAUI/Scheduler/timeline-views.md
Included video links in the UG document for the MAUI SfScheduler control.
=> Added YouTube Video Links in UG For Customizing Special Time Regions in MAUI SfScheduler

MAUI/DateTimePicker/date-time-picker-mode.md, MAUI/TimePicker/time-picker-mode.md
Description:
Cleared MD Validation Error
=> 937500-Cleared MD Error

MAUI/DataGrid/export-to-pdf.md
Tutorial video link was added for exporting to PDF
=> Added tutorial video link for Export to PDF

MAUI/DataGrid/scrolling.md
**Description:** 
Updated the User Guide (UG) document to include details about the DiagonalScrolling feature in the Scrolling page. This update provides insights into its functionality, usage, and configuration options.
=> MAUI-947112-[others]-Documentation Update for Diagonal Scrolling Feature

MAUI/Radial-Menu/Events.md
Added the space and resolved the spelling error.
=> MAUI-946812 - [Staging Fix]: Added the space and resolved the spelling error.

MAUI/Toolbar/getting-started.md
Added Fix getting started documentation for .Net Maui Toolbar control
=> 936919 - Added Fix getting started documentation for .Net Maui Toolbar control

MAUI/AIAssistView/styles.md, MAUI/AIAssistView/working-with-aiassistview.md
To resolve issues in SfAIAssistView UG.
=> To resolve issues in UG

MAUI/Toolbar/getting-started.md, maui-toc.html
Updated the toc file for the issue
=> 936919 - Updated getting started documentation for .Net Maui Toolbar control

MAUI/Toolbar/getting-started.md
Added UG documentation for .Net Maui Toolbar control
=> 936919 - Added UG content changes for .Net Maui Toolbar control

MAUI/Picker/picker-mode.md
MAUI Picker build fail Syntax error issue resolved.
=> 934415 - [Dev] MAUI Picker build fail Syntax error issue resolved

MAUI/PDF-Viewer/Form-Filling.md
Description :
UG documentation has been added for the IsHidden,BorderColor,BackgroundColor,BorderWidth,ForegroundColor property in form field support in the .NET MAUI PDF Viewer.
=> 946336: Publish UG documentation for 2025 Volume 1 release for SfPdfViewer

MAUI/DataGrid/master-details-view.md
- Reviewed the MasterDetailsView UG document and identified mistakes.
- Corrected errors in content, formatting, and structure.
- Ensured proper alignment with UG guidelines.
- Committed the necessary changes for better clarity and accuracy.
=> Maui-[947109]-Reviewed and Corrected MasterDetailsView UG Documentation.

MAUI/Toolbar/orientation.md, MAUI/Toolbar/overflow-mode.md, MAUI/Toolbar/tooltip.md
Updated the fix changes for the toolbar content
=> 947788-Updated the fix changes for the toolbar content

MAUI/Scheduler/appointments.md
Updated fix for the scheduler content
=> 947788-Updated fix for the scheduler content

MAUI/Themes/Keys.md
Updated theme content for the scheduler.
=> 947788-Updated theme content for the scheduler.

MAUI/Themes/Keys.md, MAUI/Toolbar/toolbar-items.md
Updated the theme issue and toolbar changes
=> 947788-Updated changes for toolbar ug

MAUI/Button/Getting-Started.md, MAUI/Carousel-View/getting-started.md, MAUI/Chips/Getting-Started.md, MAUI/ComboBox/Getting-Started.md, MAUI/DateTime-Range-Slider/getting-started.md, MAUI/Masked-Entry/Getting-Started.md, MAUI/NumericEntry/Getting-Started.md, MAUI/Range-Slider/getting-started.md, MAUI/Rating/Getting-Started.md, MAUI/Rotator/Getting-started.md, MAUI/TextInputLayout/Getting-Started.md
Hi Team,
I have updated the Nuget package related steps in the .NET MAUI Tools controls UG documentation
Regards,
Sivaranjith N
=> 703018-Updated the Nuget package related steps in MAUI Tools controls

MAUI/ComboBox/UI-Customization.md
Hi Team,
Added ComboBox Dropdown Closing Workaround in UG Documentation.
=> [Hotfix] Added ComboBox Dropdown Closing Workaround in UG Documentation

MAUI/ComboBox/UI-Customization.md
Hi Team,
Added ComboBox Dropdown Closing Workaround in UG Documentation.
=> 941381 [Development] Added ComboBox Dropdown Closing Workaround in UG Documentation

MAUI/UIKit/release-notes.md
Description:
Updated UI Kit Version
=> 943421-Updated Version

MAUI/Cartesian-Charts/migration.md, MAUI/Circular-Charts/migration.md
This PR to development removes the known issue stated in the Migration.md files for cartesian and circular charts.
* https://github.com/syncfusion-content/maui-docs/pull/3168
=> Update Chart Content - Development

MAUI/DataGrid/scrolling.md
Added an API reference for AllowDiagonalScrolling, providing detailed documentation on its functionality and usage within the scrolling behavior.
=> Added API Reference for AllowDiagonalScrolling

MAUI/Calendar/localization.md
Description:
Updated Alignment for Localization
Task [#909362](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/909362/)
=> 909362-Updated Alignment-Dev

MAUI/Calendar/localization.md
Description:
Updated Alignment for Localization
Task [#909362](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/909362/)
=> 909362-Updated Alignment

MAUI/Autocomplete/Selection.md, MAUI/ComboBox/Selection.md
Hi team,
I've added the API links for Selection changing event for SfAutocomplete and SfComboBox
Regards,
Hemalatha K
=> Added API links for Selection changing event for SfAutocomplete and SfComboBox in .NET Maui

MAUI/AIAssistView/data-binding.md, MAUI/AIAssistView/styles.md, MAUI/AIAssistView/suggestions.md, MAUI/AIAssistView/working-with-aiassistview.md
Added API reference link for new features in SfAIAssistView.
=> [Hotfix] MAUI - Added API reference link for new features in SfAIAssistView

MAUI/Badge-View/Animation.md, MAUI/Busy-Indicator/AnimationType.md, MAUI/Radial-Menu/Events.md, MAUI/Radial-Menu/Populating-Items.md
Added API reference link for newly implemented features in SfBadgeView, SfBusyIndicator and SfRadialMenu.
=> Updated the API reference for the newly implemented features.

MAUI/DataGrid/Column-types.md, MAUI/DataGrid/grouping.md, MAUI/DataGrid/sorting.md, MAUI/DataGrid/summaries.md, MAUI/DataGrid/swiping.md
A note for template selector was added in the features which use template selector.
=> MAUI - Add note for template selector in DataGrid

MAUI/Common/migration.md
=> Updated migration.md file

MAUI/Picker/dealing-with-header-footer-and-selection-view.md
Description:
Updated Spelling Mistake
=> 951714-Picker-Spelling-Mistake

MAUI/Picker/dealing-with-header-footer-and-selection-view.md
Description:
Updated Spelling Mistake
=> 951714-Picker-Spelling-Mistake-dev

MAUI/DataGrid/selection.md
Hi @MallikaRK 
|--|--|
|Task Category| Site Audit-Incorrect URL-format
|UX task| NA|
|Hotfix|https://github.com/syncfusion-content/maui-docs/pull/3229
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/200110/
|Excel/SharePoint link| NA| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B20474523-6AF0-4D8C-9BF4-5AF6C037651B%7D&file=Duplicate%20Title.xlsx&action=default&mobileredirect=true
|Changes made|Reason for changes|
|--|--|
|![image](https://github.com/user-attachments/assets/a052b1e7-1008-48d3-99e2-cca79afd93d4)| To avoide redirection issue link of the page
Regards,
Mercy A.
=> SEO-200110-SEO-Site-Audit-Incorrect-URL-Format-MaUI-Grid

MAUI/PDF-Viewer/Form-Filling.md
Updated the content errors in the note for the form fields behavior about the background color in the form filling md file.
=> 951924 - Update note about the form fields background color behavior

MAUI/DataGrid/sorting.md
* Added the live data update changes in the sorting document.
=> MAUI - [DataGrid] Added the live data update changes in sorting documentation

MAUI/Button/Getting-Started.md
Resolved the tab issue in Getting-Started page in SfButton UG
=> [Hotfix] 930801 - Resolved the tab issue in Getting-Started page 

MAUI/Button/Getting-Started.md
Resolved the tab issue in Getting-Started page in SfButton UG
=> [Dev] 930801 - Resolved the tab issue in Getting-Started page

MAUI/ComboBox/AutoSizing.md, MAUI/ComboBox/Editing.md, MAUI/ComboBox/Filtering.md, MAUI/ComboBox/Getting-Started.md, MAUI/ComboBox/Header-and-Footer.md, MAUI/ComboBox/Highlighting-matched-text.md, MAUI/ComboBox/Maximum-display-item-with-Expander.md, MAUI/ComboBox/No-Results-Found.md, MAUI/ComboBox/Searching.md, MAUI/ComboBox/Selection.md, MAUI/ComboBox/UI-Customization.md
Hi team,
I've revamp the UG documentation of .NET MAUI SfComboBox
=> [Hotfix] 930424 - Revamp the UG documentation of .NET MAUI SfComboBox

MAUI/Button/how-to/Add-the-custom-view-for-button.md
Hi Team, 
I've made a few minor corrections in the SfButton UG.
=> 928065 [Hotfix] - Revamp the UG documentation of .NET MAUI SfButton.

MAUI/Licensing/how-to-register-in-an-application.md
Updated the UG documentation for Syncfusion License key registering.
=> Updated the UG documentation for Syncfusion License key registering.

MAUI/Kanban-Board/Events.md
Maui Kanban CardTapped event UG content added.
=> 955918 - Maui Kanban CardTapped event UG content added

MAUI/PDF-Viewer/UI-Customization.md
Updated the themes sample in the customization user guide.
=> 896838 - Publish a GitHub sample for theming the PDF Viewer using theme keys 

MAUI/DataGrid/Column-sizing.md, MAUI/DataGrid/Column-types.md, MAUI/DataGrid/Unbound-Column.md, MAUI/DataGrid/columns.md, MAUI/DataGrid/data-binding.md, MAUI/DataGrid/filtering.md, MAUI/DataGrid/grouping.md, MAUI/DataGrid/master-details-view.md, MAUI/DataGrid/performance.md, MAUI/DataGrid/search.md, MAUI/DataGrid/selection.md, MAUI/DataGrid/sorting.md, MAUI/DataGrid/styling.md, MAUI/DataGrid/swiping.md, MAUI/DataGrid/unbound-row.md
* Defined control names constantly for all the topics in both xaml and c# files.
=> Defined control names constantly for all the topics in MAUI DataGrid UG documentations

MAUI/Calendar/customizations.md
Based on custom view of selection cell template support implemented in month view and selection mode is single.
=> Add UG Document for SelectionCellTemplate Support

MAUI/Introduction/Overview.md
Corrected the spelling error in the Overview file located in the Introduction folder.
=> Updated the spell error

MAUI/DataGrid/serialization.md
Code changes regarding UI corrections of Serialization UG content.
=> Code changes regarding UI corrections of Serialization UG content.

MAUI/Calendar/calendar-mode.md, MAUI/Calendar/customizations.md, MAUI/Scheduler/agenda-view.md, MAUI/Segmented-Control/selection.md, MAUI/Toolbar/customization.md
Updated the corrections for the ug content for scheduler, segmented control and toolbar.
=> 964696-Updated the corrections for the ug content of scheduler team

MAUI/DockLayout/Features.md, MAUI/DockLayout/getting-started-docklayout.md
Updated the syncfusion.maui.core initialization name from dx to sf.
=> MAUI-962529 Modified namespace initialization of .NET MAUI DockLayout.

MAUI/AIAssistView/data-binding.md, MAUI/AIAssistView/emptyview.md, MAUI/Chat/messages.md, MAUI/TreeView/drag-and-drop.md
Added API links and Sample link for the following features
1.EmptyView{SfAIAssistView}
2.ItemsSource{SfAIAssistView}
3. Delivery States{SfChat}
4. DragAndDrop {SfTreeView}
=> Added API links for the Features

MAUI/Autocomplete/UI-Customization.md, MAUI/ComboBox/UI-Customization.md, MAUI/NumericEntry/UpDown-Button.md
Hi team, 
I have update API links for volume 2 release features
=> Updated API links for volume 2 release features

MAUI/Autocomplete/UI-Customization.md, MAUI/ComboBox/UI-Customization.md
Hi team,
I update the Values chsnged event link for SfAutocomplete and SfcomboBox
=> Update the Values changed event API link for SfAutocomplete and SfcomboBox

MAUI/Autocomplete/Selection.md, MAUI/Autocomplete/UI-Customization.md, MAUI/ComboBox/Selection.md, MAUI/ComboBox/UI-Customization.md, MAUI/NumericEntry/UpDown-Button.md
Update API links for volume2 features
=> Update API links for volume2 features

MAUI/Autocomplete/Selection.md, MAUI/Autocomplete/UI-Customization.md, MAUI/ComboBox/Selection.md, MAUI/ComboBox/UI-Customization.md
Hi team,
I've moved the value changed event content from UI-Customization.md to selection.md. reverted #3409
=> Moved value changed content from UI-Customization.md to selection.md

MAUI/DockLayout/Features.md, MAUI/DockLayout/Overview.md, MAUI/DockLayout/getting-started-docklayout.md
**Description** 
Updated API links for DockLayout UG
=> Update API links for DockLayout UG

MAUI/Picker/migration.md
##Description
Updated Migration Document
=> 948368-Updated-Migration-Document [Development]

MAUI/Picker/migration.md
=> 948368-Updated-Migration-Document[Hotfix]

MAUI/UIKit/GettingStarted.md
##Description
Updated UG Links
=> 969598-Updated Links [Hotfix]

MAUI/ListView/getting-started.md
Addressed the typo mistakes and API mistakes in GettingStarted UG of ListView controls.
=> ListView - resolved GettingStarted UG mistakes.

MAUI/PDF-Viewer/Stamps.md
Addition of notes about the color change limitation of stamp annotation while editing
=>  953973 - Update note about the color changes limitation of stamp annotation 

MAUI/PDF-Viewer/Annotations-Overview.md, MAUI/PDF-Viewer/Magnification.md, MAUI/PDF-Viewer/Overview.md
Update the zoom modes details in OverView.md file and update the default zoom actor range for the desktop platforms for .NET MAUI PdfViewer.
=> 950710 - [.NET MAUI PdfViewer] Update the missing information in the UG documentation

MAUI/PDF-Viewer/Annotations-Overview.md
Corrected the you tube link added in the annotation overview UG
=> 974325 - Update the YouTube link in Annotations UG

maui-toc.html
Removed the contents of MAUI PDF Viewer from TOC file
=> 976545 - Change the UG for PDF Viewer controls

MAUI/Segmented-Control/customization.md
The title added for the ShowSeparator Property UG was incorrect. Added the correct title name.
=> Changed the title for the UG Content about ShowSeparator Property in the MAUI SegmentedControl - Master

MAUI/Chat/messages.md
- added topic for target views
- added sub-topic for template selector to return base template
- added note for initials
=> 977149: Added UG for Targetable views, return base templates for .NET MAUI Chat

MAUI/Kanban-Board/Cards.md
MAUI Kanban UG notes content (related to `CardTemplate`) added in Cards.md file.
This is the follow-up of https://github.com/syncfusion-content/maui-docs/pull/3556 and https://github.com/syncfusion-content/maui-docs/pull/3575
=> 977013-[Dev] MAUI Kanban UG notes content added in Cards.md

MAUI/Kanban-Board/Column.md
MAUI Kanban UG notes content (related to `Background`, `NoCardTemplate` and `PlaceholderStyle`) added in Column.md file. Based on review corrections in this PR https://github.com/syncfusion-content/maui-docs/pull/3556.
This is the follow-up of https://github.com/syncfusion-content/maui-docs/pull/3556 and https://github.com/syncfusion-content/maui-docs/pull/3574
=> 977013-[Dev] MAUI Kanban UG notes content added in Column.md

MAUI/Rich-Text-Editor/Basic-Features.md
Update HTML text API content in SFRichTextEditor
=> Update HTML text API content in SFRichTextEditor

MAUI/Rich-Text-Editor/Migration.md
Update the Limitations in Migration.md
=> Update the Limitations in Migration.md

MAUI/Scheduler/resource-view.md
=> Added API links for newly added features

MAUI/Kanban-Board/Column.md, MAUI/Kanban-Board/Getting-Started.md
MAUI Kanban UG code snippet highlighted.
Dev PR - https://github.com/syncfusion-content/maui-docs/pull/3620.
=> 977013-[Hotfix] MAUI Kanban UG code snippet highlighted

MAUI/Kanban-Board/Column.md, MAUI/Kanban-Board/Getting-Started.md
MAUI Kanban UG code snippet highlighted.
=> 977013-[Dev] MAUI Kanban UG code snippet highlighted

MAUI/Scheduler/resource-view.md
Updated improper API links that were not added properly
=> API links Corrections

MAUI/DataGrid/addNew-row.md, MAUI/DataGrid/scrolling.md
Addressed the below corrections in the UG documents of MAUI SfDataGrid
- image width and titile correction in AddNewRow document
- modified the name from SfDatagrid to SfDataGrid in Scrolling mode section in the scrolling document
=> MAUI- Modified some changes in the UG of SfDataGrid

MAUI/DataGrid/styling.md, MAUI/ListView/viewappearance.md
Added API links for DisplayMemberPath in SfListView & RowMouseHover In SfDataGrid UG
=> Added API links for DisplayMemberPath & RowMouseHover

MAUI/Masked-Entry/Migration.md
Updated the contents in MaskedEntry UG documentation.
=> Update MaskedEntry UG content hotfix

MAUI/Demos.md
Added Maui demo for the Mac platform.
=> Added Maui demo for Mac platform

MAUI/Kanban-Board/Getting-Started.md
Maui kanban content changes updated.
=> 980536 - [hotfix] Maui kanban content changes updated

MAUI/DatePicker/events.md
##Description
Updated UG Changes
Task ID: https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/976803/
=> 976803-Update-Events-UG[Hotfix]
