syncfusion-content/maui-docs

MAUI/Cartesian-Charts/Getting-Started.md, MAUI/Cartesian-Charts/Scatter.md, MAUI/Cartesian-Charts/Selection.md, MAUI/Cartesian-Charts/Tooltip.md, MAUI/Cartesian-Charts/Zooming-and-panning.md, MAUI/Circular-Charts/DoughnutChart.md, MAUI/Circular-Charts/Getting-Started.md, MAUI/Circular-Charts/PieChart.md, MAUI/Circular-Charts/Selection.md, MAUI/Circular-Charts/Tooltip.md
Have to clear the issue by adding the API reference to the highlighted property fields in the Chart UG Content. So on clicking the field it has to navigate to its own API reference page in UG Content. But some of the fields didn't navigate we have to clear this issue.
The reason for this issue is those fields does not have set the API reference link to them due to wait for release roll out. 
Nil
**Guidelines/documents are not followed**
Nil
**Guidelines/documents are not given**
Nil
**Reason:**
Nil
**Action taken:**
Nil
**Related areas:**
Nil
Nil
Since, the issue is because it doesn't navigate  to the API reference page of the UG Content, I have added their own property field's API reference link to the Highlighted field in the UG Content source code.
Nil
**Before changes:**
Nil
**After …
=> MAUI-1882-Added API Reference

MAUI/Scheduler/migration.md
- Assembly Name
- Namespaces
- Properties
- Events
- Enums
- Classes
- Methods
- SchedulerAppointment
- SchedulerAppointmentMapping
- MonthView
- DayView
- TimelineView
- SchedulerTimeRegion
- AppointmentTextStyle
- CellStyle
- HeaderView
- ViewHeaderSettings
- WeekNumberStyle
Regards,
Muniappan S
=> MAUI-1844 Migrating MAUI SfScheduler from Xamarin SfSchedule

MAUI/Common/migration.md, MAUI/Introduction/maui-cross-platform-ui.md, maui-toc.html
Hi Team,
I have done the following changes to the Maui UG documentation.
* Removed multiple times DateTime Sliders topics which have been added in the Maui-doc.
* Added the SignaturePad and updated the DateTime Range Selector migration links.
* Added DateTime Sliders and SignaturePad in the cross-platform UI section.
Please check the above changes and merge it.
Regards,
Praveen G.
=> MAUI-2385-Updated cross platform, migration and maui-doc files in hotfix/20.2.0.36

MAUI/Autocomplete/Getting-Started.md, MAUI/ComboBox/Getting-Started.md
Liquid Exception thrown in Autocomplete and ComboBox Getting started page
Didn't close the highlight tag
Closed the endhighlight tag.
=> MAUI-3102 Fixed the Autocomplete ComboBox UG syntax error in getting started page

MAUI/Maps/migration.md
I removed unwanted bracket for the MAUI Maps Sublayer UG. Could you please review it?
Regards,
Shalini Ashokan.
=> MAUI-3166 : Removed the bracket in maps migration document..

MAUI/CircularProgressBar/migration.md, MAUI/LinearProgressBar/migration.md
I have added the asterisk for the renamed API in migration document for both the linear and circular progress bar control.
Regards,
Balachandar.
Output image
=> MAUI-3155 : Asterisk added for the renamed API in migration document for MAUI progress bar control.

MAUI/Common/migration.md
* In Pdf Viewers there is no Migration document page so removed the link syntax.
=> MAUI-2819 Error Correction in the Migration Documentation Page.

MAUI/DataGrid/Getting-started.md
Remove   ColumnSizer="Star"
Add  ColumnWidthMode="Fill"
Ref https://help.syncfusion.com/maui/datagrid/column-sizing
=> ColumnSizer not aplicable for Maui

MAUI/Common/migration.md, MAUI/Introduction/MAUI-cross-platform-UI.md
=> MAUI-4213 Fixed the Syntax Error in the .NET MAUI Introduction and Migration Page.

MAUI/Cartesian-Charts/Errorbar-Chart.md, MAUI/Cartesian-Charts/Waterfall-Chart.md
User Guide for the Error Bar Series and Waterfall Series in MAUI Platform
All about the Error bar Series feature and its types. And Initialising the error Bar Series was explained here.
All about the waterfall Series feature And Initialising the waterfall Series was explained here.
- I Created the UG Document in md Format named as ErrorBar.md
- I attached a folder contains the Chart_types Images for Error Bar Series
- I attached the images to the md file
- I Created the UG Document in md Format named as Waterfall.md
- I attached a folder contains the Chart_types Images for Waterfall Series
- I attached the images to the md file
- I added the Waterfall Series in the html List file
=> MAUI-4918-Create-UG-for-Error-Bar-and-waterfall-Series-in-MAUI__Modification

MAUI/PDF-Viewer/Keyboard-Shortcuts.md, MAUI/PDF-Viewer/Text-Selection.md, maui-toc.html
Added the UG documentation for text selection feature in .NET MAUI PDF Viewer
The topics that are covered in this documentation are below.
1. Header changes
2. Introduction (Selecting text from a PDF document)
3. Selecting text using mouse.
4. Selecting text using touch
5. Customising text highlight color.
6. Handling selected text from the application level.
7. Known limitations 
8. Keyboard shortcuts.
Additional Notification: @ramkumarsync
=> 823731: UG documentation for text selection feature in .NET MAUI PDF Viewer

MAUI/Accordion/events.md, MAUI/Accordion/getting-started.md, maui-toc.html
Fixed the ug corrections.
1) **"Walk-through the entire process of creating the real world of this control."** is needed. Referred in other controls. Used in some controls like, popup, listview, datagrid and dataform. Thus this content is needed for Accordion.
2) **Control name is wrong as highlighted**- Changed SfPopup to SfAccordion.
3) T**he SfAccordion is a layout control with a vertically stacked list of accordion items that comprise a header and content. You can load any view in the header and content sections. Users can expand or collapse the content view by tapping the header.
In this example, a Grid is loaded in both the header and content of accordion items.** - Changed the Items, Header and content first letter to lower case.
4) **For this we must show c# code separately. tabs …
=> Fixed the Accordion ug corrections

maui-toc.html
Add the HTML tag link for .NET MAUI NavigationDrawer UG documentation.
=> 859492 - Add the HTML tag link for .NET MAUI NavigationDrawer UG documentation.

MAUI/PDF-Viewer/Migration.md
Task Link : https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/875166/
Title : Xamarin Migration document content changing
Issue : Unexpected character ` in "{{`FlattenOnSave`| markdownify }}" in maui/PDF-Viewer/Migration.md[0m
Fix : Changed the FlattenOnSave into ( ' ) single quote
=> 875166-Resolved Unexpected character error in Migration document-(SfPdfViewer)

MAUI/PDF-Viewer/Localization.md
Title : Update Localisation default name of .NET MAUI PDF Viewer
Task ID - [897701](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/897701/)
Newly Added Default Names :
- SaveSignature
- MatchCase
- SearchPlaceholder
- Apply
=> 897701-Update Localisation default name of .NET MAUI PDF Viewer

MAUI/Cartesian-Charts/Area.md, MAUI/Cartesian-Charts/RangeArea.md, MAUI/Cartesian-Charts/StackedArea.md, MAUI/Cartesian-Charts/StackedArea100.md, MAUI/Cartesian-Charts/StepArea.md, MAUI/Cartesian-Charts/migration.md, MAUI/Circular-Charts/migration.md, MAUI/Funnel-Charts/Legend.md, MAUI/Funnel-Charts/migration.md, MAUI/Polar-Charts/PolarArea.md, MAUI/Polar-Charts/PolarLine.md, MAUI/Polar-Charts/migration.md, MAUI/Pyramid-Charts/Legend.md, MAUI/Pyramid-Charts/migration.md
This PR updates the User Guide (UG) to include new content regarding the following features:
•	**Legend Toggle Support**: Added instructions and examples on how to use the legend toggle feature in the following charts, allowing users to easily show or hide legends as needed.
o	SfPyramidChart
o	SfFunnelChart
•	**Marker Support**: Included details on how to utilize marker support for the following charts, enabling users to add and customize markers for better data visualization.
o	Stacked Area Chart
o	Stacked Area 100 Chart
These additions aim to enhance the documentation and provide clearer guidance on leveraging these features effectively.
Changes Made:
•	Updated UG sections related to chart customization.
•	Added examples and usage scenarios for legend toggle and marker features.
=> MAUI-892140 Add Legend Toggle and Stacked Area Marker Support content to UG Documentation

MAUI/PDF-Viewer/Toolbar.md
I have removed the following toolbar names
**Reason** : Below mentioned toolbar are dropdown toolbar of TopToolbar's icon and it is also not given the toolbar list for desktop. For Mobile platform 20 toolbars are listed and Desktop has 17 toolbars are listed. I have cross checked all the toolbar with source
| Toolbar Name        | Description                                                     |
|---------------------|-----------------------------------------------------------------|
| SearchToolbar       | The toolbar for text search appears at the top of the mobile PDF viewer. |
| MoreOptionToolbar   | The toolbar for more options appears at the top of the mobile PDF viewer. |
=> 898689 - Update the toolbar names in MAUI PDF Viewer

MAUI/Badge-View/Getting-Started.md
Resolve Liquid syntax error in Badge-View/Getting-Started.md
=> Resolve Liquid syntax error in Badge-View/Getting-Started.md

MAUI/AIAssistView/data-binding.md, MAUI/AIAssistView/getting-started.md
Added changes in the SfAIAssistview - Getting started and Data binding
=> Added changes in the SfAIAssistview - Getting started and Data binding

MAUI/Cartesian-Charts/Area.md, MAUI/Cartesian-Charts/Legend.md, MAUI/Cartesian-Charts/Line.md, MAUI/Cartesian-Charts/RangeArea.md, MAUI/Cartesian-Charts/SplineRangeArea.md, MAUI/Cartesian-Charts/StackedArea.md, MAUI/Cartesian-Charts/StackedArea100.md, MAUI/Cartesian-Charts/StackedLine.md, MAUI/Cartesian-Charts/StackedLine100.md, MAUI/Cartesian-Charts/StepArea.md, MAUI/Cartesian-Charts/StepLine.md, MAUI/Circular-Charts/Legend.md, MAUI/Funnel-Charts/Legend.md, MAUI/Polar-Charts/Legend.md, MAUI/Polar-Charts/PolarArea.md, MAUI/Polar-Charts/PolarLine.md, MAUI/Pyramid-Charts/Legend.md
The following changes have been made to the MAUI Chart Control UG Documentation:
- Adjusted content section for the StackedLine100 chart.
- Corrected API reference for ShapeType.Circle in the appropriate charts.
- Given API reference for the following cartesian charts:
- StackingLineSeries
- StackingLine100Series
- SplineRangeAreaSeries
- Updated the APIs for the following sections for all five charts:
- Legend label customization section
- Event - LegendItemCreated section
=> 910813: Update the API link for .NET MAUI Chart Controls - Volume 3, 2024.

MAUI/PDF-Viewer/Magnification.md, MAUI/PDF-Viewer/Migration.md
Fixed the exception in MAUI PDF Viewer Documents
Change 1 : Removed the keyword in migration.md and magnification.md files
Reason : Exception in migration.md and magnification.md files
=> Fixed the exception in MAUI PDF Viewer Documents

MAUI/TabView/Visual-State-Managers.md
Corrected the code error in TabView UG.
=> Corrected the code error in TabView UG- Hotfix

MAUI/Themes/Keys.md
Updated the missing themes key in the keys.md file
- SfPdfViewerControlBackgroundColor 
- SfPdfViewerLoadingIndicatorColor
=> 931298 - Update the missing keys in the theme UG

MAUI/Autocomplete/Getting-Started.md, MAUI/Button/Getting-Started.md, MAUI/Carousel-View/getting-started.md, MAUI/Chips/Getting-Started.md, MAUI/ComboBox/Getting-Started.md, MAUI/DateTime-Range-Selector/getting-started.md, MAUI/DateTime-Range-Slider/getting-started.md, MAUI/DateTime-Slider/getting-started.md, MAUI/Masked-Entry/Getting-Started.md, MAUI/NumericEntry/Getting-Started.md, MAUI/Range-Selector/getting-started.md, MAUI/Range-Slider/getting-started.md, MAUI/Rating/Getting-Started.md, MAUI/Rotator/Getting-started.md, MAUI/SignaturePad/getting-started.md, MAUI/Slider/getting-started.md, MAUI/TextInputLayout/Getting-Started.md
I have added tab support for Visual Studio and Visual Studio code in getting started page
SfAutocomplete
SfComboBox
SfMaskedEntry
SfNumericEntry
SfTextInputLayout
SfChip
SfCarousel
SfRotator
SfButton
SfRating
SfSignaturePad
SfSlider
SfRangeSlider
SfRangeSelector
SfDateTimeSlider
SfDateTimeRangeSlider
SfDateTimeRangeSelector
=> 935343 [Hotfix] Add tab support for Visual Studio and Visual Studio code in getting started page

MAUI/PDF-Viewer/Getting-Started.md
Updated the .net version in Prerequisites in both the tabs visual studio and visual studio code
=> 934831-Update the getting started page with two tabs for visual studio and visual studio code

MAUI/PDF-Viewer/Getting-Started.md
Updated the getting started page with .net 8 link in prerequisites of both the tabs visual studio and visual studio code
=> 934831 - Update the getting started page with two tabs for visual studio and visual studio code

MAUI/Popup/popup-positioning.md
Included API refrence for IgnoreActionBar popup
=> Included API refrence for IgnoreActionBar popup

MAUI/Cartesian-Charts/migration.md, MAUI/Circular-Charts/migration.md
This PR to hotfix-v28.2.3 removes the known issue stated in the migration.md files for cartesian and circular charts.
* https://github.com/syncfusion-content/maui-docs/pull/3167
=> Update Chart Content - Hotfix

MAUI/PDF-Viewer/Free-Text.md
The form filling UG has been updated with guidance on how to hide the border of free text annotations.
=> 932479 - How to hide the border of free text annotation?

maui-toc.html
Hi Team,
For the SfChip, the header format "Datatemplateselector" was changed to "Data Template Selector".
=> Corrected the Datatemplateselector heading format for the SfChip.

MAUI/Picker/picker-mode.md
Description:
Added WebPage of the UG Document for PopupSize support for the Picker Controls(SfPicker, SfDatePicker, SfDateTimePicker and SfTimePicker) and SfCalendar. Removed the open text button in the picker control.
Related PR:
Picker - https://github.com/essential-studio/maui-picker/pull/393
Calendar - https://github.com/essential-studio/maui-calendar/pull/484
=> 955746 - Removed the OpenText Button in Picker

MAUI/Accordion/appearance.md, MAUI/DataForm/Validation.md, MAUI/Scheduler/agenda-view.md, MAUI/Segmented-Control/selection.md, MAUI/Toolbar/customization.md
**Description**:
The User Guide (UG) documentation for the following controls has been reviewed and updated as per the standard review criteria reviewed Controls:
- Dataform
- Scheduler
- Segmented Control
=> New release UG

MAUI/DataForm/Data-annotations.md, MAUI/DataForm/Editors.md, MAUI/DataForm/getting-started.md, MAUI/Scheduler/appointments.md, MAUI/Scheduler/getting-started.md, MAUI/Scheduler/reminders.md, MAUI/Scheduler/resource-view.md, MAUI/TreeMap/getting-started.md
Updated notes for business objects for scheduler, treemap and dataform.
=> 964696- Updated notes for business objects for scheduler team ug.

MAUI/Chat/messages.md, MAUI/Chat/styles.md, MAUI/Themes/Keys.md, MAUI/TreeView/drag-and-drop.md, maui-toc.html
Adding review corrections for Delivery State in SfChat control.
=> Adding review corrections for Delivery States in .NET MAUI SfChat

MAUI/ImageEditor/getting-started.md
Hotfix PR for https://github.com/syncfusion-content/maui-docs/pull/3484
ImageEditor URI image iOS platform related notes added.
=> 967983-[Hotfix] ImageEditor URI image iOS platform related notes added

MAUI/PDF-Viewer/Migration.md
Updated the migration document for the below Xamarin APIs :
1. AnnotationMode.HandwrittenSignature
2. AnnotationSettings.HandwrittenSignature
3. DocumentSaveInitiated
=> 972286 - Update the missing API in the migration document

MAUI/Cartesian-Charts/Getting-Started.md, MAUI/DockLayout/getting-started-docklayout.md, MAUI/SunburstChart/Selection.md, maui-toc.html
Task - [973016](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/973016)
**Description** 
- Added UG Document for .NET MAUI Sunburst Selection support
=> 973016-UG Document for .NET MAUI Sunburst Selection support

MAUI/Segmented-Control/customization.md
The title added for the ShowSeparator Property UG was incorrect. Added the correct title name.
=> Changed the title for the UG Content about ShowSeparator Property in the MAUI SegmentedControl - Hotfix
